### ISSUE TITLE
Ability to scroll when you push the mouse to the rightmost edge of the screen (last pixel).

### ISSUE THREAD

**Issue by trancephorm** [nicotine-plus/nicotine-plus#1517] opened 2021-09-02 05:15 UTC
Right now, there is probably one or few pixels and you can't drag scrollbar when you go to the screen edge. Scrollbar drag area should be extended right to the last rightmost pixel on screen, it would much more usable.

I'm using Linux version and maybe such thing does interfere with desktop manager (I'm using KDE), but I doubt it's impossible.

**Comment by slook** [comment] 2021-09-02 10:07
On my Linux version of Nicotine+ 3.1.1 (GTK 3.22.11) on XFCE, the scrollbars are working at the very edge.

Perhaps there is some problem with your KDE theme maybe? What is your version @trancephorm ?

**Comment by trancephorm** [comment] 2021-09-02 15:03
![image](https://user-images.githubusercontent.com/5833909/131868100-f2179b68-af5e-4c64-954a-ae10a56fd307.png)

**Comment by trancephorm** [comment] 2021-09-02 15:03
3.1.1  •  GTK 3.24.20

**Comment by slook** [comment] 2021-09-02 17:14
@mathiascode Please can you escalate this Enhancement to a Bug, given that the scrollbar does not behave like it should.

@trancephorm Thank you for this information, it will be very useful. It may take a while to figure this one out, as we don't currently have a KDE testing box to hand. What distro are you running please?

**Comment by trancephorm** [comment] 2021-09-02 19:09
Ubuntu 20.04 with KDE Plasma (not Kubuntu).

**Comment by mathiascode** [comment] 2021-09-03 20:06
This seems to be a bug in the Breeze theme (if you're using it), which affects other GTK applications as well.

**Comment by trancephorm** [comment] 2021-09-03 20:24
Thanks for this info!

**Comment by slook** [comment] 2021-09-03 21:31
If @mathiascode 's discovery will resolve the issue for you @trancephorm , then please do let us know once you've had a chance to try another theme.

Also, please do not hesitate to post again should you find any other issues, or if you ever have any questions etc, as any feedback is very welcomed on here.

**Comment by trancephorm** [comment] 2021-09-04 05:17
Tried several other themes, still not working. Although I didn't try those Kvantum themes, because I've read this: https://www.reddit.com/r/kde/comments/95ubre/what_do_i_need_to_know_to_use_kvantum/, I concluded I'm not going to install which seems to be a 3rd party unsupported engine... so guys, I guess I'm not much of the help here anymore and I'm pretty sure it's possible to make it work in default Breeze theme because for example Firefox's scroll is working as it should.

**Comment by slook** [comment] 2021-09-04 09:03
Then indeed @trancephorm this indicates a deeper issue with the KDE Plasma environment compatibility that @mathiascode may want to do some further testing on, the scrollbar issue sounds like a really horrible glitch. Thank you for raising this issue.

**Comment by mathiascode** [comment] 2021-09-04 23:42
> Tried several other themes, still not working. Although I didn't try those Kvantum themes, because I've read this: https://www.reddit.com/r/kde/comments/95ubre/what_do_i_need_to_know_to_use_kvantum/, I concluded I'm not going to install which seems to be a 3rd party unsupported engine... so guys, I guess I'm not much of the help here anymore and I'm pretty sure it's possible to make it work in default Breeze theme because for example Firefox's scroll is working as it should.

Can you try some other GTK applications with scrollbars, and check how they behave?

**Comment by slook** [comment] 2021-09-11 11:45
Hello @trancephorm please can you verify whether or not this issue occurs with other GTK apps on your system. Thanks.

**Comment by trancephorm** [comment] 2021-09-12 09:42
Beside Nicotine, I think don't have any GTK app installed. Can you maybe recommend some that has a scrollbar feature and that is small?

**Comment by slook** [comment] 2021-09-12 10:25
Gedit

**Comment by trancephorm** [comment] 2021-09-12 13:18
Installed Gedit, I can confirm it acts the same as in Nicotine+, scrollbar not working properly.

**Comment by slook** [comment] 2021-09-12 14:54
I don't know where in upstream this bug comes from, KDE, Kwin, X11, GTK, etc, nor how a workaround could be developed for it, if that would even be possible since the mouse events are not being passed to the Nicotine+ application window in the first place.

The following possibly related KDE bugs may be of interest for further investigation...

[Bug 419318 - Click and drag scroll doesn't work when mouse leaves scrollbar if initial click was in right-most pixel](https://bugs.kde.org/show_bug.cgi?id=419318)

[Bug 387775 - KWin touch screen edge creates a 1 pixel dead zone on that edge that doesn't accept mouse clicks or scrolls outside of full-screen mode](https://bugs.kde.org/show_bug.cgi?id=387775)

[Bug 423390 - [X11] Bottom Plasma panel and desktop are not fully adjacent to screen border (1 pixel on the right and bottom)](https://bugs.kde.org/show_bug.cgi?id=423390)

[Bug 428895 - [x11] Maximized windows don't fill 1px of screen on HiDPI](https://bugs.kde.org/show_bug.cgi?id=428895)

However, if the non-GTK apps on your system are not affected, then most of the above are irrelevant. I couldn't seem to find a bug specifically relating to GTK3, although the KDE bug tracker is very large so I may well be mistaken.

There are a wide range of various specific scenarios mentioned, such as multi-monitor, touch support, scaling, cursor size, etc... Some potential solutions are suggested therein, that may or may not be applicable to the GTK application(s) on your system.

If you set a bright wallpaper, can it be seen thorugh the 1px gap zone when a GTK app is maximized?

Try setting Nicotine+ > Menu > View > Use Header Bar > to Off

**Comment by trancephorm** [comment] 2021-09-12 15:19
> If you set a bright wallpaper, can it be seen thorugh the 1px gap zone when a GTK app is maximized?

No, it can't be seen through.

**Comment by slook** [comment] 2021-09-12 15:37
Thanks. Actually there is a [whole section in the KDE bug tracker](https://bugs.kde.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=CONFIRMED&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=NEEDSINFO&bug_status=VERIFIED&bug_status=CLOSED&component=gtk%20theme&product=Breeze&query_format=advanced&resolution=---&resolution=FIXED&resolution=INVALID&resolution=WONTFIX&resolution=LATER&resolution=REMIND&resolution=DUPLICATE&resolution=WORKSFORME&resolution=MOVED&resolution=UPSTREAM&resolution=DOWNSTREAM&resolution=WAITINGFORINFO&resolution=BACKTRACE&resolution=UNMAINTAINED) for a package called the "Breeze-GTK Theme", I found these:

[Bug 431930 - GTK4 apps cannot be maximized fully due to window shadow still being visible](https://bugs.kde.org/show_bug.cgi?id=431930) (gtk4 only)

[Bug 357314 - Scrollbar can not be dragged from far right](https://bugs.kde.org/show_bug.cgi?id=357314) (fixed)

Is the [Breeze-GTK theme package](https://github.com/KDE/breeze-gtk) actually installed on your system?

**Comment by trancephorm** [comment] 2021-09-12 17:12
It doesn't say Breeze-GTK, it just says Breeze... I don't get it, that theme is not listed in themes.

**Comment by Inso-m-niaC** [comment] 2021-09-12 17:50
It is just Breeze and Breeze-Dark

**Comment by slook** [comment] 2021-09-12 18:31
Try to find the package paste enter this command:
`sudo apt list --installed | grep -i 'breeze-gtk\|gtk3-engines-breeze\|gnome-breeze'`

If the above command shows no results, then you don't have the package that includes the fix for [KDE Bug 357314](https://bugs.kde.org/show_bug.cgi?id=357314) so I'm guessing that at present some buggy default fallback theme is used by GTK apps on your system...

Enter command `sudo apt install package_name` to install a one package called either...
- either `breeze-gtk`
- or `breeze-gtk-theme` <-- probably this one
- or `gtk3-engines-breeze`
- or `gnome-breeze`
- (sorry I don't know which it is called from your distro's repo)... or from link:
- https://invent.kde.org/plasma/breeze-gtk#install-instructions

Use `sudo apt remove package_name` to uninstall packages that aren't needed or don't work.

Then... "To set the theme in Plasma 5, enter...
- `sudo apt install kde-gtk-config` then to enable the GTK theme to use...
- System Settings > Application Style > GNOME Application Style.
- Also make sure to disable "apply colors to non-Qt applications" in System Settings > Colors > Options."

I haven't tested Ubuntu with KDE Plasma, so I don't know what it will look like, but it seems to be officially supported "A GTK 2 and 3 Theme Built to Match KDE's Breeze" so idk I would imagine that it comes bundled with Kubuntu? See links:
https://packages.ubuntu.com/focal/breeze-gtk-theme 
http://changelogs.ubuntu.com/changelogs/pool/universe/b/breeze-gtk/breeze-gtk_5.18.4.1-0ubuntu1/changelog

**Comment by trancephorm** [comment] 2021-09-12 19:08
I have breeze-gtk installed.

**Comment by slook** [comment] 2021-09-12 19:17
Alrite, what about `kde-gtk-config` ?

**Comment by trancephorm** [comment] 2021-09-12 19:28
Don't have that one.

**Comment by slook** [comment] 2021-09-12 19:49
Then perhaps breeze-gtk is installed but unconfigured.

**Comment by trancephorm** [comment] 2021-09-12 20:05
$ sudo apt install kde-gtk-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kde-gtk-config

**Comment by slook** [comment] 2021-09-12 20:08
`sudo apt install kde-config-gtk-style`

https://packages.ubuntu.com/focal/kde-config-gtk-style

**Comment by trancephorm** [comment] 2021-09-12 20:12
LOL :)

sudo apt install kde-config-gtk-style
Reading package lists... Done
Building dependency tree       
Reading state information... Done
kde-config-gtk-style is already the newest version (4:5.18.4.1-0ubuntu1).
kde-config-gtk-style set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by slook** [comment] 2021-09-12 20:15
System Settings > Application Style > GNOME Application Style

![image](https://user-images.githubusercontent.com/88614182/133001513-e080132a-20d6-441f-9d8f-57c3a2f81b6b.png)

You want to see if Select a GTK3 theme is selected Breeze-GTK

**Comment by trancephorm** [comment] 2021-09-12 20:23
Switched from GTK3 theme Breeze to Emacs, and now scroll is ok! Default theme is ok too. Thanks a lot for your support, nice workaround!

**Comment by slook** [comment] 2021-09-12 20:31
Hooray! I am glad we arrived at a suitable solution that resolves the problem :-)

Thank you for taking the time to post about this issue, hopefully this will help other KDE users who may have a similar issue with the buggy KDE Plasma Breeze-GTK theme.

If you ever have any other suggestions or bug reports please always feel free to open a new issue on here.

**Comment by slook** [comment] 2021-09-12 21:00
@mathiascode As this bug is not caused by Nicotine+ and no workaround is viable this Issue can be closed now.

Still unsure if the cause of the problem is related to a package mismatch ([breeze-gtk](https://github.com/nicotine-plus/nicotine-plus/issues/1517#issuecomment-917692730) vs [breeze-gtk-theme](https://packages.ubuntu.com/focal/breeze-gtk-theme)) specific to the affected Ubuntu system, or if this issue is widespread for all KDE Plasma installations using this/any version of the Breeze theme (in which case it might be a noteworthy Known Issue for the next release until/if ever this gets fixed upstream).

**Closed** 2021-09-12 21:39 UTC
Labels: enhancement

**Comment by mathiascode** [comment] 2021-09-12 21:47
The problem is here: https://github.com/KDE/breeze-gtk/blob/4db54ea909a7f36215546330f0212600352e2ee4/src/gtk3/widgets/_scrollbar.scss#L14

Breeze adds space around/outside the scrollbar, which breaks the hitbox near the edges.
