### ISSUE TITLE
Auto resume/retry

### ISSUE THREAD

**Issue by m3thm4th** [nicotine-plus/nicotine-plus#2555] opened 2023-06-27 06:35 UTC
When downloading a lot of files and the queue is filled, the remaining files get the "Too many files" status; if the uploader terminates the program the status changes to "User logged off". When the queue is empty again, or when the uploader logs back in, the download doesn't start automatically, the user must press the "Resume" button.

It would be very useful to have the program automatically resume all the files in the download list every X minutes, so the downloads can proceed unattended. The user should be able to set the time interval between every retry. A button named "Auto-Resume" or "Auto-Retry" could be placed beside the "Resume" button, so the user would be able to activate and disactivate this behavior without going in the settings.

**Comment by slook** [comment] 2023-06-27 20:17
It should already be the behaviour, unless you are experiencing some bug. What version of Nicotine+ are you running?

**Comment by cproensa** [comment] 2023-06-27 23:43
I dont know about the specific situation of the remote user disconnecting, and not resuming when he's back online.

But, At first i also suspected something wrong about the auto retry behavior, becasue after finishing the current downloads, those files in "too many files" took a noticeable time to be restarted. However, they will eventually will be restarted.
So yes, the auto-resume works as intended (eventhough the interval is not congurable?)

What i also noticed:
* The auto resume is not windowed. I mean, ideally, when one file gets to completion, the first (or a number of) "locally queued" files should be probed. Currently, when the allowed downloads have finished, you still have to wait X time for the auto-resume to kick in.
* Manual "resume" over the list to force immediate retry, seems to try to probe all files. For a long list this has a big performance hit (ui is unresponsive for some time)
* A better approach may be a lazier probing. So that once we receive a "too many files" response, keep all succesive files locally queued without probing. This helps improving perfomance, and would work nicely with the previous suggestions for a windowed retry

**Comment by slook** [comment] 2023-06-28 09:25
> the auto-resume works as intended (eventhough the interval is not congurable?)

As far as I know, the intervals are based on the behaviour of the official client, and they are non-configurable for reasons of overall network stability and predictability.

> Manual "resume" over the list to force immediate retry, seems to try to probe all files. For a long list this has a big performance hit (ui is unresponsive for some time)

Any actions which cause the UI to hang are considered to be a bug, and should be investigated as such.

> A better approach may be a lazier probing.

That might be a strategy to consider which could help to avoid unnecessarily invoking a large iteration.

**Comment by mathiascode** [comment] 2023-07-07 23:15
> When the queue is empty again, or when the uploader logs back in, the download doesn't start automatically, the user must press the "Resume" button.

Does the status change to "Queued" when the uploader connects again? What's the status when you press Resume?

**Comment by mathiascode** [comment] 2023-07-08 14:21
> > Does the status change to "Queued" when the uploader connects again? What's the status when you press Resume?
> 
> It switches from "Too many files" to "Transferring/Queued"

So you're saying that certain downloads get stuck in "Queued" mode, and that resuming them makes them start transferring?

**Comment by slook** [comment] 2023-07-10 07:26
> I have to manually press "Resume"

Are you certain that the items don't automatically start after 12 minutes (the duration of the automatic timer)?

**Comment by slook** [comment] 2023-07-11 02:01
All the peers are ideally having the same set timeouts to help determine when each client can expect, for example, to receive a retry request after some kind of failure or reaching a limit. This way, peers can more easily negotiate who should be doing what and when, to avoid conflicting requests.

There are 5 different (non-configurable) timers as such is commented in the transfers module here:

https://github.com/nicotine-plus/nicotine-plus/blob/d2107d2aebd0ad494aa534dfa576670a10c8c70d/pynicotine/transfers.py#L182-L197

> what's the difference if I push the "Resume" button several times per minute?

When you purposefully override the natural flow to jump a queue or evade a number of files/size limit, some clients might be configured to ban you, or place limits on the number/size of items you can queue at any one time.

The other difference for you as the user will experience more stress interacting with the client in this intensive way. Your effort might be better spent searching for your desperately wanted file from another user, or go elsewhere for a while.

> Do I make the network less stable?

It doesn't really matter as much nowadays as it used to, back in the days when the protocol was originally designed, these things were more relevant because connection speeds were considerably slower (often transfers took hours rather than minutes) so being misplaced in a queue was a much bigger inconvenience than it is now.

> If we could have a setting to configure the interval between retries it would be great.

It would seem desirable, but unfortunately doing so is unlikely to provide the remedy that you are seeking.

**Comment by DeathStalker77** [comment] 2023-10-20 06:27
It would seem this "stress", to me (not knowing the technicalities of the protocol), _should_ be no different than manually forcing a Re-Announce in BitTorrent.  There _should_ be a way to configure (any) client to be able to handle any such manual timing overrides.  Either that, or make the "wait" time shorter - to me, 12 mins is a rather long period.  Properly configuring the clients to auto-resume at a shorter interval (maybe 5 mins?) would therefore make any such manual "override" superfluous - like hitting an elevator button multiple times - it does nothing for/to the elevator or the timing, but it is psychological in nature. :-)

**Comment by mathiascode** [comment] 2023-10-20 16:12
The wait time won't be configurable, but I suppose we could bring it down to 5 minutes or similar without causing any larger issues. SoulseekQt happened to choose 12 minutes, but this was several years ago, and we mainly need to ensure clients aren't too aggressive with automatic requests (https://www.slsknet.org/news/comment/6045#comment-6045). I think a shorter interval could still fulfill this, as long as it's not, say, 1 minute.

**Comment by DeathStalker77** [comment] 2023-10-20 17:17
I can totally understand no wanting to "hammer" other clients! :-)

**Comment by slook** [comment] 2023-10-20 17:36
Rather than having the central 12 minute (or 5 min) timer for all transfers to be batch retried on mass, perhaps each transferring user should have its own timer instead.

**Comment by DeathStalker77** [comment] 2023-10-20 17:48
I like that idea - a "round-robin" for each file from the SAME user, BUT multiple files could still be requested on the same INTERVALS from DIFFERENT users!  :-)  Any potential negatives on that?

**Comment by slook** [comment] 2023-10-20 17:53
Well, that is supposed to be the intention of how it should already be working, but something is not right with the current implementation because occasionally something unexpected happens that makes everything either fall down or go bezurk.

**Closed** 2023-11-02 22:49 UTC
Labels: bug
