### ISSUE TITLE
Downloading a folder is complicated and worse experience than SoulseekQt

### ISSUE THREAD

**Issue by deicap** [nicotine-plus/nicotine-plus#2481] opened 2023-04-17 17:57 UTC
Tried to use Nicotine today (after 15 years of Soulseek) and was quickly disappointed with performing my usual routine of looking for rare albums.

SoulseekQt has this popup window that is for some reason missing in Nicotine+.

The window is useful because:

1. It allows to quickly download AN ENTIRE ALBUM (a folder) when only one or few songs (from that album) have been found in the search results.
2. It allows to rename a folder before it gets downloaded, to keep things well organized on my computer, according to my own folder naming conventions (in my case "artist - date - album name"). Nicotine, currently, simply forces you download a folder with its original name and all contents to your Dowloads folder.

Going to use SoulseekQt until this is fixed. 

![awerwer](https://user-images.githubusercontent.com/16666998/232570634-6019f956-3250-4161-b39d-878cd5a3f418.jpg)

**Comment by mathiascode** [comment] 2023-04-17 19:16
Duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/1659. This feature will be implemented in Nicotine+ 3.3.0: https://github.com/nicotine-plus/nicotine-plus/issues/2260

> that is for some reason missing in Nicotine+.

Nicotine+ was created before SoulseekQt existed, and the old Soulseek client didn't have the dialog. I agree that it's a good idea though, and it's something I've wanted to add for a while.

**Closed by mathiascode** 2023-04-17 19:16 UTC
Labels: enhancement
