### ISSUE TITLE
Left unattended just crashed on win 11 beta slow rinng

### ISSUE THREAD

**Issue by ztauras** [nicotine-plus/nicotine-plus#2151] opened 2022-08-11 18:35 UTC
Nicotine+ Version: 3.2.3
GTK Version: 3.24.34
Python Version: 3.10.5 (main, Aug  5 2022, 05:55:00)  [GCC 12.1.0 64 bit (AMD64)]

Type: <class 'TypeError'>
Value: 'PeerInit' object is not iterable
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py", line 1827, in _on_critical_error_threading
  File "D:/a/_temp/msys64/mingw64/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2006, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1874, in process_queue_messages
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1831, in process_internal_messages
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 650, in send_message_to_peer

**Comment by ztauras** [comment] 2022-08-11 18:36
I got these errors but nicotine is working after that, keep the good work guys!

**Comment by slook** [comment] 2022-08-11 19:29
This is a duplicate of #2148 which has been fixed today in the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md) 3.2.5.dev1 please do test it and let us know if you encounter any further issues @ztauras

**Closed by slook** 2022-08-11 19:29 UTC
