### ISSUE TITLE
Critical Error: UnicodeEncodeError

### ISSUE THREAD

**Issue by earwigcahootz** [nicotine-plus/nicotine-plus#2767] opened 2023-11-23 18:54 UTC
Nicotine+ version:  3.2.9
Operating System/Distribution:
unRaid v6.11.5 w/ Docker (v
20.10.21)

### Describe the bug
Application throws a Critical Error which persists through restarts. No connectivity is achieved while in error state. Full reinstall required to clear error.

I have Nicotine+ running in a Docker container on my unRaid server. For the past few months, I have been encountering repeated critical errors. The window (attached) pops up, and the app needs to be closed. If I restart the container, the error appears immediately and no connections are made (all in-progress uploads/downloads show as "User Logged Off". The only way to restore functionality is to trigger an update/reinstall of the container. This unfortunately wipes all of my settings and I have to update my share maps again as well as lose all of my in-progress transfers.

### Expected behavior
Not encountering error.

### Steps to reproduce the bug
So far I can't correlate a specific cause. It is triggered upon selecting "Download Folder" from search results. However, I can't determine if it is the specific file/folder that triggers, or if it is triggered because I am doing many searches and downloads in quick succession.

### Additional context
![nicotine+ error](https://github.com/nicotine-plus/nicotine-plus/assets/125619915/fcf7813d-f635-4c28-9231-3f0142b46678)

**Comment by darkstar1971** [comment] 2023-11-23 20:28
i am experiencing the same or very similar issues on a Synology NAS. same error but it doesn't always abort the app and require fresh install.

i get this error when attempting to download a folder with diacritical marks (accented characters) in the name. however, i can download individual files with diacritical marks.

after a certain number of these errors i'm kicked off server.slsknet.org and can't log back in. restarting nicotine+ doesn't fix the problem. i'm forced to delete then reinstall the nicotine+ container - and Web Station (which among other things assigns ports to containers).

supposedly the edits to source code below fixed the problem back in Oct 2021, but it appears to have been broken again. when i compared the file __init__.py in the current code base to the one referenced in this code there are many differences, so many that a non-coder like myself couldn't isolate the lines in __init__.py that might need editing (of course it could be other files that are to blame - like the two referenced in the error you posted a screenshot of: search.py and transfers.py. that said, my hunch is that they are merely the files that triggered an error in another file that handles Unicode.

https://github.com/nicotine-plus/nicotine-plus/commit/23d7d253bc63437271eeb0fdfcafc683e6468c73

**Comment by slook** [comment] 2023-11-24 00:14
> the same or very similar issues

@darkstar1971 It might be the same error but in a different place, please provide a copy of the stack trace from the Critical Error dialog if you can thanks.

> couldn't isolate the lines in init.py that might need editing (of course it could be other files that are to blame

The error can probably be avoided using `encode_path()` inside `os.statvfs()` on the actual line that raises the error, which in @hogbat 's trace would be needing a change on line 1827 in transfers.py:

`max_bytes = os.statvfs(encode_path(folder_path)).f_namemax`

_However, I don't know if that workaround would work or not (since I cannot test this) nor is it the best way to resolve the regression, or if this crash would warrant backporting a proper fix into the 3.2.x branch or not (another release of Nicotine+ 3.2.10 was not planned, since there's no CI in that branch anymore), but now there are a grand total 2 known Critical crashes in Nicotine+ 3.2.9 (this one and the "slsk://username" crash in the userbrowse module), then maybe @mathiascode could be tempted to consider, in the interests of the endevour to create a super-stable release for the history books, doing a legacy backport in the interim before releasing 3.3.0?_

Thank you both very much for your reports, please can you establish if the issue still exists in Nicotine+ 3.3.0.dev6 or not?...
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by hogbat** [comment] 2023-11-24 00:31
Unfortunately, I cannot test the new version as I am using a template for my container and do not know how to manually update to a different version.

**Comment by slook** [comment] 2023-11-24 00:36
Fair enough, I thought that might be the case. Please can you ask the author of your template to test Nicotine+ 3.3.0.dev6 (master) for us, since we currently have no Docker testers, the Release Candidate(s) will available during December.

**Comment by hogbat** [comment] 2023-11-24 01:01
Hmm, there doesn't seem to be a way to contact this author via Dockerhub. I found the user here on Git but they don't have any project related to this container or any other way for me to message them that I'm aware of.

**Comment by slook** [comment] 2023-11-24 01:15
See also discussion https://github.com/nicotine-plus/nicotine-plus/discussions/2312

**Comment by hogbat** [comment] 2023-11-24 01:24
> See also discussion #2312

I hadn't thought of looking into other clients to run in Docker. I'll have to read up on them. When I tried N+ and found the search result filter I was happy so I looked no further.
Thanks!

**Comment by slook** [comment] 2023-11-24 01:32
slskd does have search result filters, and it comes with its own docker container (in fact, that is the main way it is intended to be run). Of course it has no desktop UI, which is almost always an advantage for running applications remotely imo.

However, please do try N+ out again in a later version when you can!

**Comment by darkstar1971** [comment] 2023-11-24 08:18
i've tried multiple times to map a DSM share volume to a debug path in nicotine+ as docker run, docker compose and within Container Manager like so:

-v /volume1/docker/nicotine/config/data:/root/.local/share/nicotine

when I do that i can't log in to the slsk server, and get an error like this (the dialog box in the upper left is only partially visible and clicking on the button to "change login details" doesn't clear the dialog box ... i can't use tab to toggle between buttons / form fields either):

<img width="1327" alt="Screenshot 2023-11-22 at 10 38 05 PM" src="https://github.com/nicotine-plus/nicotine-plus/assets/151877462/8d68ae09-7b78-42bb-8b9c-cbf590c01d76">

the permissions on volume1/docker/nicotine/config/data are the same ones running the docker container.

the /root/.local/share/nicotine/logs folder has always been empty even after triggering the UnicodeEncodeError - though earlier i did find a log file /root/.local/share/nicotine/logs/private/somebuddy.log which contains the message i sent to "somebuddy."

the debug folder defined in n+'s logging settings is /root/.local/share/nicotine/logs/debug

so when it comes to the error which is generated when attempting to download a folder with diacritical marks in the name, i'm only able to provide a screenshot which is basically identical to hogbat's:

<img width="531" alt="Screenshot 2023-11-24 at 12 15 48 AM" src="https://github.com/nicotine-plus/nicotine-plus/assets/151877462/28809346-71e2-4ca8-866f-8f5bf8f69d83">

nothing is copied to the clipboard when clicking on "Copy & Report Bug."

thanks for your interest in troubleshooting this issue. i will say that now that since i figured out how to replicate the error and how to avoid it (downloading files instead of the folder, even when they also have diacritical marks, works fine) and nicotine has been very stable now for a little over 24 hours.

**Comment by darkstar1971** [comment] 2023-11-24 08:23
i spoke to soon.  after replicating the twice (maybe three times?) while trying to get a clean screenshot has apparently caused n+ to disconnect from the slsk server.  i'm not getting any results when searching.

this means i will have to delete the n+ container (and uninstall web station - an unrelated issue) and start from scratch. bummer.

**Comment by mathiascode** [comment] 2023-11-24 13:25
Duplicate of #2569, see this comment: https://github.com/nicotine-plus/nicotine-plus/issues/2569#issuecomment-1622096682

In short, the issue was worked around in the current unstable version, but your file system uses the wrong encoding, so non-ASCII characters crash Nicotine+ 3.2.9. Try setting the locale and see if it helps: https://stackoverflow.com/questions/27931668/encoding-problems-when-running-an-app-in-docker-python-java-ruby-with-u

@slook No more 3.2.x releases are possible, since Windows 7 support was dropped by MSYS2 (and CI is probably completely broken by now).

**Comment by darkstar1971** [comment] 2023-11-24 23:54
any advice on debug logging?

if i have the debug path set as /root/.local/share/nicotine/logs should a debug.log file be created any time there is an error?

**Comment by slook** [comment] 2023-11-24 23:58
Only if logging to file is on in Preferences > Logging

**Comment by darkstar1971** [comment] 2023-11-25 00:13
ah, ok, i didn't notice the checkboxes for different logging options.  i thought if i defined that log path in docker compose / container manager / portainer that it would use that folder to create a debug log.

**Comment by slook** [comment] 2023-11-25 00:20
Open the log with something like `nano` or `vim` instead.

**Comment by darkstar1971** [comment] 2023-11-25 00:23
vi shows the same text as cat.

**Comment by darkstar1971** [comment] 2023-11-25 02:19
i was able to get [cproensa's testing image](https://hub.docker.com/r/cproensa/nicotine-docker/) (3.3.0.dev6) and it works flawlessly when downloading folders w/ diacritical marks in the name.

the interface is much nicer than 3.2.9 - more responsive scrolling on my macbook (3.2.9 scrolling was too fast), for one thing. it's difficult to explain but all the components of the UI seem sturdies. i expect that many features have been debugged and streamlined.

great work by team nicotine!

**Comment by darkstar1971** [comment] 2023-11-25 18:41
> Open the log with something like `nano` or `vim` instead.
> 
> It's questionable whether or not nicotine might be unhappy about running as the root user in the container.

this is a sortof embarrassing question (because so basic), but how do I assign a different user to run the container? i thought it would run as my default DSM user.

thanks

**Comment by slook** [comment] 2023-12-10 13:47
I'm not sure whether or not in Docker it is best practice to create a regular user for security, because as a rule in linux don’t do everything in root.

That would involve having the `core-utils` and `sudo` packages (or equivalent) available to create a user called "user" or such using `useradd` and `groupadd` linux commands within the container, to create a restricted account, then installing the nicotine package under that user.

As such, the program should be run within an unprivileged userspace environment that is more like what it is designed for.

**Comment by mathiascode** [comment] 2023-12-15 15:16
Closing as duplicate, since the issue will be fixed/worked around in Nicotine+ 3.3.0 regardless.

**Closed by mathiascode** 2023-12-15 15:16 UTC
Labels: bug, duplicate

**Comment by slook** [comment] 2023-12-18 15:18
> how do I assign a different user to run the container?

@darkstar1971 I did find possibly useful information about this, see link:
https://github.com/fletchto99/nicotine-plus-docker#user--group-identifiers

**Comment by darkstar1971** [comment] 2023-12-19 07:17
yes that's exactly it, PUID and PGID are the way to control user permissions within the nicotine+ docker..
