### ISSUE TITLE
Download speed after restart

### ISSUE THREAD

**Issue by 82d** [Nicotine-Plus/nicotine-plus#918] opened 2020-12-27 17:28 UTC
Nicotine+ 2.2.2:  
Operating System/Distribution: Arch Linux

After restarting the program, the specified speed limit settings take effect after their reapplication.

**Comment by mathiascode** [comment] 2021-01-01 08:07
I can't reproduce this issue. Download speeds are applied for me at startup.

What is the value of "downloadlimit" under the [transfers] section in the config file?

**Comment by 82d** [comment] 2021-01-02 17:05
uploadlimit = 240
downloadlimit = 0

**Comment by mathiascode** [comment] 2021-01-03 03:17
If you're indeed talking about the _download_ speed, then "downloadlimit" should be non-zero after closing the preferences window. I'm not sure what could be wrong here. Could you check if the value is overwritten at some point?

**Comment by 82d** [comment] 2021-01-04 19:08
> If you're indeed talking about the _download_ speed, then "downloadlimit" should be non-zero after closing the preferences window. I'm not sure what could be wrong here. Could you check if the value is overwritten at some point?

I noticed that initially the configurations were in~/.config/nicotine then they moved to ~/.nicotine. But the situation has not changed.
I ran a new experience with speed. and set limits on upload and download at 25kb/s. After restarting the client, the restrictions immediately worked only for outgoing traffic. Values ​​were not cleared in the config file when checked.

**Comment by mathiascode** [comment] 2021-01-08 09:58
The move to the old ~/.nicotine folder can occur if you run Nicotine+ 1.4.1 or older, or have an old config file with download/log paths pointing to the folder.

I have no idea what's going on here, as the procedure for saving download and upload speeds to the config file is the same. Could you back up your current config file, and check if this also happens on a fresh install?

**Comment by 82d** [comment] 2021-01-09 08:43
Found that next to the ~/ .nicotine directory there are two more directories .nicotine (1) and .nicotine (2) of the same size and date of change. The directory tree looks like this:
`├── buddyfileindex.db
├── buddyfiles.db
├── buddymtimes.db
├── buddystreams.db
├── buddywordindex.db
├── config
├── config.old
├── fileindex.db
├── files.db
├── logs
│   ├── debug
│   ├── private
│   ├── rooms
│   └── transfers
├── mtimes.db
├── plugins
├── streams.db
├── transfers.pickle
└── wordindex.db
`
the program has not written to the config /.config/nicotine/ for a long time. 
I did cp ~/nicotine/* ~/.config/nicotine/ . The program started and picked up the settings. But the speed settings were not applied. They were also applied after clicking the "Apply" button. The download queue disappeared, but they came back when I moved the directory back.
 I did what you said, deleted the settings, the program created new ones in ~ / .config / nicotine / but the bug with the speed settings did not go away.

**Comment by mathiascode** [comment] 2021-01-09 09:53
`The download queue disappeared` That would be due to the transfers.pickle file being placed in ~/.config/nicotine instead of ~./local/share/nicotine. The "config" file is read from ~/.config/nicotine, while all other files are read from ~./local/share/nicotine.

Could you check if the unstable version also has this issue? See https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/RUNFROMGIT.md
If it's still an issue, do you think you could email me (see my GitHub profile) your nicotine-related folders, with any personal info snipped out?

**Comment by 82d** [comment] 2021-01-19 03:52
can't install, after the command: `sudo .env/bin/pip install .` also  `sudo .env/bin/pip install . --no-use-pep517`, returns an error.
   ```
 ERROR: Command errored out with exit status 1:
     command: /home/user/Desktop/BOX/git/nicotine-plus/.env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xd5hbilx/pygobject_18258ec8d3b842b5addd94a14c23d013/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xd5hbilx/pygobject_18258ec8d3b842b5addd94a14c23d013/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jkriedu6/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/Desktop/BOX/git/nicotine-plus/.env/include/site/python3.9/PyGObject
         cwd: /tmp/pip-install-xd5hbilx/pygobject_18258ec8d3b842b5addd94a14c23d013/
    Complete output (42 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/pygtkcompat
    copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-3.9/pygtkcompat
    copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-3.9/pygtkcompat
    copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-3.9/pygtkcompat
    creating build/lib.linux-x86_64-3.9/gi
    copying gi/types.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/pygtkcompat.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/module.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/importer.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/docstring.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_signalhelper.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_propertyhelper.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_ossighelper.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_option.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_gtktemplate.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_error.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/_constants.py -> build/lib.linux-x86_64-3.9/gi
    copying gi/__init__.py -> build/lib.linux-x86_64-3.9/gi
    creating build/lib.linux-x86_64-3.9/gi/repository
    copying gi/repository/__init__.py -> build/lib.linux-x86_64-3.9/gi/repository
    creating build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/__init__.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/Pango.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/Gio.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/GdkPixbuf.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/GObject.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/GLib.py -> build/lib.linux-x86_64-3.9/gi/overrides
    copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-3.9/gi/overrides
    running build_ext
    Package gobject-introspection-1.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'gobject-introspection-1.0', required by 'virtual:world', not found
    Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.46.0')' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/user/Desktop/BOX/git/nicotine-plus/.env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xd5hbilx/pygobject_18258ec8d3b842b5addd94a14c23d013/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xd5hbilx/pygobject_18258ec8d3b842b5addd94a14c23d013/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jkriedu6/install-record.txt --single-version-externally-managed --compile --install-headers /home/user/Desktop/BOX/git/nicotine-plus/.env/include/site/python3.9/PyGObject Check the logs for full command output.

```

**Comment by mathiascode** [comment] 2021-01-19 18:06
You need to install the "gobject-introspection" package. I'll update the instructions to reflect this.

**Comment by 82d** [comment] 2021-01-20 06:45
for convenience, you could mark with what privileges you need to perform each step of the installation. for example it is not immediately clear what action the last command carries
.env/bin/nicotine может это часть установки, а може быть запуск.

**Comment by 82d** [comment] 2021-01-20 07:00
now I have checked how the speed limit settings will work. after the launch, the speed was maximum. I had to go to the settings and click "apply".

**Comment by mathiascode** [comment] 2021-02-05 16:47
Has anything changed in the latest unstable build?

**Comment by zniavre** [comment] 2021-02-05 16:56
![Capture d’écran du 2021-02-05 17-54-53](https://user-images.githubusercontent.com/2409578/107063982-4cdd4380-67db-11eb-8eb8-f5899b5f6d17.png)
i always hav to "apply" to set limits after each start of nic +

**Comment by mathiascode** [comment] 2021-02-05 17:12
> i always hav to "apply" to set limits after each start of nic +

This should be fixed with my latest changes in master? Can you check?

**Comment by zniavre** [comment] 2021-02-06 10:09
fixed !!!   thank you

**Closed** 2021-02-17 01:08 UTC
Labels: bug
