### ISSUE TITLE
Nicotine+ crashes on Mac when browsing for buddy shares via Shares menu

### ISSUE THREAD

**Issue by Babbzzz** [nicotine-plus/nicotine-plus#3110] opened 2024-08-29 08:56 UTC
Nicotine+ Version: 3.3.4
GTK Version: 4.14.4
Python Version: 3.12.3 (darwin)

Type: <class 'OSError'>
Value: [Errno 22] Invalid argument
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/userbrowse.py", line 99, in _parse_local_shares
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3050, in parse_network_message
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3085, in _parse_network_message
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3075, in _parse_result_list
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3075, in <lambda>

**Comment by mathiascode** [comment] 2024-08-29 23:31
Duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/3063. Fixed in 3.3.5rc1: https://nicotine-plus.org/doc/TESTING.html#macos

**Closed by mathiascode** 2024-08-29 23:31 UTC
Labels: bug
