### ISSUE TITLE
Nicotine crashes when selecting a new share folder

### ISSUE THREAD

**Issue by lorenz-py** [nicotine-plus/nicotine-plus#2181] opened 2022-09-12 19:59 UTC
Nicotine+ has encountered a critical error and needs to exit. Please copy the following message and include it in a bug report:

Nicotine+ Version: 3.2.3
GTK Version: 3.24.34
Python Version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]

Type: <class 'ValueError'>
Value: list.remove(x): x not in list
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/dialogs/preferences.py", line 629, in cell_toggle_callback
    self.set_shared_dir_buddy_only(iterator, buddy_only)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/dialogs/preferences.py", line 616, in set_shared_dir_buddy_only
    self.shareddirs.remove(share)

### Describe the bug
like I said in the title

### Steps to reproduce the bug
Choose  a new share directory and select 'buddy-only'

**Comment by mathiascode** [comment] 2022-09-12 23:12
Duplicate of #2142

This issue was fixed in Nicotine+ 3.2.4.

**Closed by mathiascode** 2022-09-12 23:13 UTC
Labels: bug
