### ISSUE TITLE
remove - hyphen

### ISSUE THREAD

**Issue by 82d** [nicotine-plus/nicotine-plus#1592] opened 2021-10-04 09:55 UTC
FreeBSD 12.2-RELEASE-p6
Nicotine+ 3.1
it was damn convenient when the string water in the search composition Nicotine filtered from and to removing any characters except alphabetic letters. since version 3.1, you have made it so that the hyphen sign remains. I assure you that this is a huge mistake in practice during the search. because in 99.9% of search cases with copy/paste, this symbol interferes with the search, it constantly has to be deleted manually. this fact makes me think about the motivation for developers to make such a decision. as for me, this is an absolute harm to the comfortable search process in the application and an indication that the creators themselves are not focused on the search process music.

**Comment by 82d** [comment] 2021-10-04 10:00
I want Nicotine+ to become more convenient and efficient and not only more attractive in its external design. I will hope that in the next 3.2.0.dev1 those amenities will return.

**Comment by slook** [comment] 2021-10-04 10:43
Interesting that Nicotine+ is misbeahving on your system @82d... The "-" hyphen is still supposed to be removed from the query. It would be ideal to find out what causes this so that it can be fixed. Thank you for raising the issue.

@mathiascode please can you escalate this Enhancement to a Bug, because the OP's installation is not behaving as expected so this requires investigation.

@82d Please can you provide details about your system locale, country and OS keyboard layout settings.

**Comment by 82d** [comment] 2021-10-04 11:28
yes, this is found on the final 3.1 and subsequent versions up to the last 3.2.0.dev1. I enter Latin characters into the search. like:
D-Ren 1 Feat. Billie Godfrey – Inside
copied from the site discogs.com . I get the output result in the form:
D Ren 1 Feat Billie Godfrey – Inside
one diphis remains and prevents the search results from being displayed. that's why you have to delete it manually. in previous versions, there was no such result. I will filter out everything practical. when searching, only filtered dots were hindered by spaces, which would be logical to blind the letters in this way. D.M.X. DMX and not D M X.

**Comment by 82d** [comment] 2021-10-04 11:42
perhaps it would be a good idea to make it possible to choose in the filter settings which sims to delete when entering and which ones to replace them with. what is there now is not always something that would give such functionality . to be honest, I was looking for such an option from the very beginning. but by default there were enough default filters that broke with the update.

**Comment by slook** [comment] 2021-10-04 12:04
` D-Ren 1 Feat. Billie Godfrey – Inside` <-- _stupid filename_

The hyphen in this query is not a standard one, it is a double-length, extra long one. Indeed it is not filtered by Nicotine+

keysyms - keysyms recognized by Tk: **`ucircumflex**                        251     0x00fb`**



Character: **`û`**
ALT Code: **`ALT 150`**
Character Name: **`Latin small letter u with circumflex`**
Unicode Code Point: **`U+00FB`**

Character: **`–`**
ALT Code: **`ALT 0150`**
Character Name: **`En dash`**
Unicode Code Point: `U+2013`

I don't know if filtering "En dash" **`–`** might also exclude **`û`** from search queries.

**Comment by 82d** [comment] 2021-10-04 12:46
> Which update, 3.1.1 or 3.2.0.dev1 ?
2.9 or 3.1
by the way, could you tell me where to get the previous versions of nicotine up to version 3.1?

**Comment by slook** [comment] 2021-10-04 13:09
> 2.9 or 3.1

These are not N+ version numbers, please specify full version string(s) in "**MAJOR . MINOR . REVISION . devbuild**" format.
.

> where to get the previous versions of nicotine

https://github.com/nicotine-plus/nicotine-plus/releases

**Comment by 82d** [comment] 2021-10-04 13:15
I remembered that I used 3.0.1 and then upgraded to 3.1.1

**Comment by 82d** [comment] 2021-10-04 13:22
I confirm that in 3..0.1 there is no such problem as before.

**Comment by 82d** [comment] 2021-10-04 13:23
> > 2.9 or 3.1
> 
> Previous versions are not updated, nor supported. If you need features that are now missing, downgrading isn't the answer because you will face platform compatibility issues. .
> 
> > where to get the previous versions of nicotine
> 
> https://github.com/nicotine-plus/nicotine-plus/releases

I confirm that in 3..0.1 there is no such problem as before.

**Comment by mathiascode** [comment] 2021-10-04 13:25
> this fact makes me think about the motivation for developers to make such a decision. as for me, this is an absolute harm to the comfortable search process in the application and an indication that the creators themselves are not focused on the search process music.

Previously, some crucial special characters were removed from Japanese search terms, rendering them useless. This was fixed, but unfortunately, hyphens not being removed anymore is a side effect I didn't know about.

I am open to feedback/bug reports, but there's no need for long rants to have them implemented.

**Comment by 82d** [comment] 2021-10-04 13:34
> I am open to feedback/bug reports, but there's no need for long rants to have them implemented.

I apologize, at first I thought that N+ had stopped deleting the standard hyphen, so I expressed a sharp opinion towards the developers.only in the process we found out that it was not a simple diphis but a special symbol, I agree that they can not always be taken into account.

**Comment by mathiascode** [comment] 2021-10-04 14:17
> indication that the creators themselves are not focused on the search process music.

We have to take care of everything ourselves, from low-level protocol/networking code to all the numerous features Soulseek has, such as chat, search, interests, transfers + every additional feature and setting Nicotine+ has, even if it's not necessarily something I prefer to work on. Sometimes things fall through the cracks, which is why it's important that users report such problems. :)

I will check if something can be done about the dash character situation.

**Comment by redactedscribe** [comment] 2021-10-04 16:15
The typical dashes used are the standard dash-minus `-`, en dash, `–`, em dash `—`, and the typographical hyphen `‐`.

There's also the normal apostrophe `'` and the typographical one `’`, and then the typographical opening and closing double quotes, `“` and `”`.

These are the common ones I can think of. Maybe the ellipsis `…` too.

**Comment by mathiascode** [comment] 2021-10-04 16:58
Added in https://github.com/nicotine-plus/nicotine-plus/commit/5079a5620d5b62f3932517c30364ad0cc7e9a072

**Comment by mathiascode** [comment] 2021-10-04 17:06
> D.M.X. DMX and not D M X.

These kind of situations are problematic. DMX will not return results for file names containing D.M.X., while D M X will.

**Comment by slook** [comment] 2021-10-04 19:32
_For reference, this is the updated list of characters Nicotine+ 3.2.0.dev currently filters from searches:_
https://github.com/nicotine-plus/nicotine-plus/blob/5079a5620d5b62f3932517c30364ad0cc7e9a072/pynicotine/utils.py#L38-L39
This is confirmed as effective at resolving the OP's original concern in [this issue](https://github.com/nicotine-plus/nicotine-plus/issues/1592).

This update is included in the [latest 'Unstable' branch builds of Nicotine+](https://github.com/nicotine-plus/nicotine-plus#gnulinux-bsd-solaris) (currently 3.2.0.dev1)

**Comment by redactedscribe** [comment] 2021-10-04 19:37
I don't know how any of this is handled, but I wanted to suggest an idea: If filenames were matched upon after they were parsed for any punctuation contained, the search could match against two variations: the filename with the bad symbols replaced by spaces, and the filename with these symbols removed. Maybe that would do a lot to improve the results. Probably not an efficient way of doing it, but hopefully the idea is illustrated.

**Comment by slook** [comment] 2021-10-04 22:05
It's a valid idea @redactedscribe but I fear that is starting to get into the realms of a "smart" search, where algorithms start to decide things on the users behalf and things start getting unpredictable, it also would also create additional network traffic and surely take twice as long? I am not slating the essence your idea, perhaps some intelligent (and efficient) handling of the D.M.X type scenarios would indeed be beneficial to everybody.

Personally I quite like the exact match database lookup nature of the search interface we currently have. And with your prior suggestions about the Result Filters and @mathiascode hard work, the Search Files interface is very powerful.

For these sorts of discussions, myself and @mathiascode started https://github.com/nicotine-plus/nicotine-plus/discussions you're most welcome to have a browse and post in there for non-urgent development related matters, this helps to keep the issue tracker free for user support.

@mathiascode please close this Issue as I believe the scope of [this Enhancement](https://github.com/nicotine-plus/nicotine-plus/issues/1592) was well resolved by yourself with https://github.com/nicotine-plus/nicotine-plus/commit/5079a5620d5b62f3932517c30364ad0cc7e9a072 which seems to work nicely with the special hyphens.

**Closed** 2021-10-04 22:44 UTC
Labels: enhancement
