### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Kpalsm** [nicotine-plus/nicotine-plus#2982] opened 2024-04-17 13:24 UTC
Nicotine+ version:  3.3.2
Operating System/Distribution:
Edition	Windows 10 Pro
Version	22H2
Installed on	‎2023-‎11-‎23
OS build	19045.4291
Experience	Windows Feature Experience Pack 1000.19056.1000.0
Processor	Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz   3.40 GHz
Display adapter	NVIDIA GeForce RTX 3080
Installed RAM	16.0 GB (15.9 GB usable)

### Describe the bug
Random crash. 

### Expected behavior
Nicotine prolly shouldn't crash I suppose

### Steps to reproduce the bug
All I was doing was watching YouTube, I had just updated my graphics drivers about an hour ago (without restarting). It's been a couple of days since I last restarted this machine (uptime 51h40m) and I leave Nicotine+ running 24/7

### Additional context
Screenshots, logs, stacktraces or relevant information.

Honestly couldn't tell you why it crashed, all I was doing at the time was watching a (fullscreen) YouTube video. I've pasted the log below; strangely the directory listed doesn't exist on the machine. Nicotine is installed to C drive in the default location, and it's a fairly fresh Windows install due to a failed Windows update back in November so shouldn't be anything weird going on with jumbled up paths or messed up registry or anything like that

Nicotine+ Version: 3.3.2
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)

Type: <class 'TypeError'>
Value: '>' not supported between instances of 'int' and 'NoneType'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 961, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 290, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/uploads.py", line 893, in _transfer_request
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/uploads.py", line 953, in _transfer_request_uploads
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/uploads.py", line 361, in _update_transfer
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 376, in update_model
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 748, in update_specific
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/transfers.py", line 462, in get_percent

**Comment by slook** [comment] 2024-04-17 18:43
Duplicate of resolved issue https://github.com/nicotine-plus/nicotine-plus/issues/2953

Fixed in 3.3.3 https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Closed by slook** 2024-04-17 18:43 UTC
Labels: bug, duplicate
