### ISSUE TITLE
Rescan not picking up new files in existing folders

### ISSUE THREAD

**Issue by thepmaar** [nicotine-plus/nicotine-plus#2232] opened 2022-10-25 15:45 UTC
Nicotine+ version:  3.2.6
Operating System/Distribution: Windows 10

### Describe the bug
I noticed this issue just before updating to 3.2.6 and it was not resolved with the update, but I'm not sure how long the issue's been happening before I noticed.

When I add one or more files to an existing folder without creating any new subdirectories, after I do a rescan the new files don't show up in my shares when I browse myself. The same issue happens when I rename a file without moving it and rescan - the old name still shows up after browsing my files, even after restarting nicotine and my system. At the same time, if I add a new folder with new files, in the same rescan those will show up when I browse myself. The only way I can get the new files or renamed files to show up is if I unshare the folder completely and re-add it. However each time I do this, nicotine freezes for a long time, which I don't believe it used to do until recently. I've not been seeing any errors in the logs throughout all this, and I can say I've tested this on my mac and the issue doesn't happen there.

**Comment by slook** [comment] 2022-10-25 22:01
We rely on a KeyError happening to avoid setting the value of the `folder_unchanged` variable. Perhaps on the affected system the comparative operation doesn't fail as expected, and then the code is reached when it shouldn't be.

https://github.com/nicotine-plus/nicotine-plus/blob/4fef0eccf26cc3a2475ddd0d88603b2ed94c9dfc/pynicotine/shares.py#L327-L333

Either that or the date modified attribute of the containing folder is not set according to the latest file time.

@thepmaar What is the filesystem type of the affected share location (NTFS, exFAT, etc)?

**Comment by slook** [comment] 2022-10-30 15:35
It's probable that Microsoft support for this Apple filesystem partition is incomplete or not very good, since in older versions of Windows in some cases those volumes were read-only. This might lead to the unintended behaviour of the folder modification date not being updated correctly.

Can you observe whether or not the folder modified date displayed in File Explorer updates when you move or rename a file?

Does it make any difference if you create a new file in the folder, such as an empty text file?

**Comment by thepmaar** [comment] 2022-10-30 16:58
Ah, so I see that when I rename a file in a folder on the drive, the folder's modified date in File Explorer doesn't change. Same when I add a new file to a folder. It updates fine on NTFS disks.

I suppose I can just reformat to a Windows filesystem, if it's an issue with Windows more than Nicotine+.

**Comment by slook** [comment] 2022-10-30 22:01
Speed optimization of the quick rescan functionality relies entirely on the modification date of the subfolders. The only workaround to this problem of incorrect datestamps is to interogote all the files, which would be just as time consuming as doing a full rebuild, so really there is not any obvious fix for this issue.

> if I unshare the folder completely and re-add it... nicotine freezes for a long time, which I don't believe it used to do until recently

The application interface shouldn't freeze during any rescan operation, since the scanner runs in it's own thread. However, some network functions are unavailable during a rescan, such as starting uploads or responding to browse requests. Unless maybe something else is choking up elsewhere in the system due to your strange filesystem mount perhaps.

Please describe in more detail what exactly occurs when this freezing happens?

**Comment by thepmaar** [comment] 2022-10-31 17:22
Well I'm running it on a very slow PC, which could be a reason. I have been unsharing and re-sharing folders on the drive while disconnected, as well. I'll go offline and remove one of the folders from my list of shared folders, and hit apply and OK, which starts a rescan. The rescan doesn't take too long, but 5-10 seconds after it's done, the entire application hangs, which lasts a minute to 5 minutes, then it comes back. But right away after it starts responding again, it loads a bunch of uploads in the upload pane that I had in my queue before going offline - all showing "User logged off", since I'm offline.

**Comment by slook** [comment] 2022-10-31 17:34
> a bunch of uploads in the upload pane that I had in my queue

https://github.com/nicotine-plus/nicotine-plus/blob/389f2c755f2cb75e5238ee01964b489f3310ac42/pynicotine/shares.py#L874-L876

**Comment by mathiascode** [comment] 2022-10-31 18:29
> > the entire application hangs ... a bunch of uploads in the upload pane that I had in my queue
> 
> Right, that is a useful observtion. I'd imagine the hang happens here:
> 
> https://github.com/nicotine-plus/nicotine-plus/blob/389f2c755f2cb75e5238ee01964b489f3310ac42/pynicotine/shares.py#L874-L876
> 
> 
> Maybe this should be done somewhere else instead.

There can't be any pending network messages if we aren't connected to the server.

**Comment by slook** [comment] 2022-11-02 15:27
Perhaps then there is a large amount of already queued uploads being processed upon reconnection that leads to interface freezing, such as if @thepmaar has not configured a maximum "Limit number of upload slots" in Preferences > Uploads > Queue Behaviour?

**Comment by mathiascode** [comment] 2022-11-06 15:36
> The rescan doesn't take too long, but 5-10 seconds after it's done, the entire application hangs

To clarify, this happens after the scan progress bar has disappeared and the "Rescan complete" message has appeared?

> it loads a bunch of uploads in the upload pane that I had in my queue before going offline - all showing "User logged off", since I'm offline.

What do you mean by "loads"? If everything works correctly, these uploads should've been marked as "User logged off" when you disconnected from the server, and remained unchanged after the rescan completed.

> I'll go offline

Using Menu -> Disconnect?

**Comment by thepmaar** [comment] 2022-11-06 16:02
> To clarify, this happens after the scan progress bar has disappeared and the "Rescan complete" message has appeared?
Yes, correct

> What do you mean by "loads"? If everything works correctly, these uploads should've been marked as "User logged off" when you disconnected from the server, and remained unchanged after the rescan completed.
Well once I go offline (Using Menu > Disconnect) it removes all the active or queued transfers from my upload list, and only leaves the "Finished" uploads. So after scanning completes and after it comes back from freezing, the transfers which had been active or queued before disconnecting show up again as "User logged off".

> such as if @thepmaar has not configured a maximum "Limit number of upload slots" in Preferences > Uploads > Queue Behaviour?
Throughout all this, I've had a limit of 10 upload slots set.

**Comment by mathiascode** [comment] 2022-11-06 18:11
> Well once I go offline (Using Menu > Disconnect) it removes all the active or queued transfers from my upload list, and only leaves the "Finished" uploads. So after scanning completes and after it comes back from freezing, the transfers which had been active or queued before disconnecting show up again as "User logged off".

This is now fixed in 3.2.7.dev1. Can you check if the freeze issue still happens?
https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#windows

**Comment by slook** [comment] 2022-11-06 18:12
Thank you for your ongoing help in debugging this issue @thepmaar please can you test the [latest development build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md#windows) 3.2.7.dev1 and report back here as to if the recent changes make any difference to the freezing problem or not?

**Comment by thepmaar** [comment] 2022-11-06 19:50
> This is now fixed in 3.2.7.dev1. Can you check if the freeze issue still happens?
Yes, this build fixed the freezing issue. Also, when offline, the old transfers don't re-appear now after rescanning.

**Comment by mathiascode** [comment] 2022-11-07 11:44
Thanks for confirming.

As for the original issue, there isn't much we can do in Nicotine+. Are you using some third-party software/drivers to access the HFS drive? If so, what is it?

**Comment by thepmaar** [comment] 2022-11-07 12:49
Yes, that's no problem. I'm using the software HFS+ to read the macOS drives.

**Comment by slook** [comment] 2022-11-07 12:53
If you go to Control Panel > Device Manager > Disk drives > [drive] > Properties > "Driver Details" button, please post that information here.

**Comment by thepmaar** [comment] 2022-11-07 13:18
![drivers](https://user-images.githubusercontent.com/57067336/200319623-a831d080-97d1-4910-8c8c-da6cd75acc58.jpg)

**Comment by slook** [comment] 2022-11-08 10:18
I suspected it might be the Paragon driver, since the official Apple HFS+ driver for Windows is limited to provide read-only access.

The date shown in your screenshot above might indicate that this driver is not really the correct one for your OS version. The vendors' website suggests that up to Windows 11 is supported, see link "[HFS+ For Windows 11 – Troubleshooting Guide](https://kb.paragon-software.com/article/1337)"

If it is an OEM driver supplied by the drive manufacturer, then you might be able to get the updated version from them (if you're lucky). I beleive the current version of this proprietary driver is something more like 11.4.298.

The software vendor also suggests that the Windows 10 Fast Startup feature is not compatible with their HFS+ driver and should be disabled "to avoid file system corruption" (although it is not stated exactly what such corruption looks like - that could well involve datestamps perhaps), see link "PARAGON HFS+ for Windows User Manual": http://ftp.paragon.eu.com/support/Manual/ENG/HFS4Win_eng070218m.pdf

The above document does also specify in the "Known Issues" section on page 3, that the resource fork component of HFS partitions is not supported. My understanding is that this "resource fork" is an integral part of the filesystem journeling, in which case it is no surprise that datestamps won't work properly.

> I suppose I can just reformat to a Windows filesystem, if it's an issue with Windows more than Nicotine+.

Frankly, unless you have a compelling reason to stick with HFS+ for this drive, your best option is to reformat to something like NTFS or FAT32.

**Comment by thepmaar** [comment] 2022-11-09 00:20
Yes, I'll just reformat, no problem. I'll have to wait until I can get a large enough new drive to transfer everything to first, but in the meantime I've updated HFS+ and turned off fast startup. Thanks for the help!

**Comment by mathiascode** [comment] 2022-11-12 17:13
I'll close this issue, since there isn't anything to do in Nicotine+.

**Closed by mathiascode** 2022-11-12 17:13 UTC
Labels: bug

**Comment by slook** [comment] 2022-12-02 02:44
Another Windows user has recently reported a problem like this one where the folder timestamps on an NTFS drive are not updated in Windows, so perhaps the issue isn't exclusive to HFS filesystems after all.
