### ISSUE TITLE
Some 3.3.0.dev6 issues

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2714] opened 2023-10-28 14:06 UTC
Nicotine+ version:  3.3.0.dev6   •   Python 3.10.12   •   GTK 3.24.33
Operating System/Distribution: Ubuntu 22.04

### Describe the bug

Since upgrading recently to latest dev release 3.3.0.dev6, i've noticed what i think are some issues introduced:

1) Error showing this message in a dialig window:
So far it's been triggered while i am not actively using the UI. (Still active u/d transfers, user browsing my files, etc, are happening in the background)
```
Nicotine+ Version: 3.3.0.dev6
GTK Version: 3.24.33
Python Version: 3.10.12 (linux)

Type: <class 'KeyError'>
Value: 'JacobR01F'
Traceback:   File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/application.py", line 702, in on_process_thread_events
    return events.process_thread_events()
  File "/usr/lib/python3/dist-packages/pynicotine/events.py", line 287, in process_thread_events
    self.emit(event_name, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynicotine/events.py", line 246, in emit
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynicotine/core.py", line 363, in _thread_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pynicotine/slskproto.py", line 521, in _check_indirect_connection_timeouts
    self._username_init_msgs.pop(username + conn_type)
```

2) Some times, the program freezes, and looks unresponsive, irrecoverable.
It always happened while i am searching and adding files to download.
CPU usage is at minimun, so it does not seem to be locked in a busy UI loop or doing anything. Also unresponsive to background activity (transfers, browse request, etc).
I dont know a specific way of reproducing this...

3) After starting this new version, it started a full rescan. Maybe its required, but if not... it should be avoided. For a big collection, can take a long time...

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment] 2023-10-28 15:29
1. Crash was only just fixed in https://github.com/nicotine-plus/nicotine-plus/commit/70ba979aa0e7ab987491c2a3b88d3f7186adf43e

2. Either fixed or caused by https://github.com/nicotine-plus/nicotine-plus/commit/2fb1ec06a752c5ea4ad3cf3bae2f6ed1e85b6a9a

3. It is a new shares database format, unfortunately a full rescan has to be forced on firstrun.

Please update to the latest master build and verify if the issues you report still exist or not.

**Comment by cproensa** [comment] 2023-10-28 18:49
Thanks!
I will try in a couple of days after the packages and images get rebuilt

**Comment by slook** [comment] 2023-10-28 19:09
packages are built after every commit to the master branch.

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Closed by slook** 2023-10-28 19:09 UTC
Labels: bug

**Comment by mathiascode** [comment] 2023-10-29 10:37
> packages are built after every commit to the master branch.
> 
> https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

The PPA packages are only rebuilt daily though.
