### ISSUE TITLE
#312 continued, cannot connect

### ISSUE THREAD

**Issue by hboetes** [Nicotine-Plus/nicotine-plus#336] opened 2020-06-29 17:23 UTC
Although #312 is mostly fixed there are still a few bits left.

I still get `getting address` → `cannot connect` issues. Now all I have to `retry` and it's working again. But the `auto-retry failed` does not try it.

And this is whilst downloading a folder, where downloading all the other files from the same user works.

**Comment by mathiascode** [comment] 2020-06-29 19:08
The connection issues are probably flukes that aren't caused by Nicotine+, but I'll check why auto-retry isn't working.

**Comment by mathiascode** [comment] 2020-06-29 20:13
From what I can tell, there's code for the auto-retry feature, but it's never called...

**Comment by mathiascode** [comment] 2020-06-29 20:21
Removed in https://github.com/Nicotine-Plus/nicotine-plus/commit/e243758495dfeed7869623851a59d4ba1b72f756#diff-8c733c2cfa58a3e896747678fd3362c0, I'll see if I can reintroduce them.

**Comment by hboetes** [comment] 2020-06-30 02:53
I did notice another situation today where the connection with a user was very flaky and the failed and retries took about 1 second. Per file about 100 log entries. I'd guess. A shame I didn't save the log output.

**Comment by hboetes** [comment] 2020-06-30 17:33
@kiplingw 
I just found the bug was still present. Could you please wait a bit more before closing bugs?
Thanks

**Comment by kiplingw** [comment] 2020-06-30 17:36
Sorry about that @hboetes. The bug automatically closed when the PR was merged. Did you try running from Git? If you were trying the daily package from the PPA, it's probably not built yet. I will trigger a manual build now for you.

**Comment by hboetes** [comment] 2020-06-30 18:03
@kiplingw 
Thanks, I'm running straight from git via my own package manager: https://github.com/hboetes/cruxports_linux/blob/master/opt/nicotine/Pkgfile
and I updated about an hour after the commit. I just didn't run into the problem again. Now I did.

It only gets stuck after running into the `cannot connect` situation.

**Comment by hboetes** [comment] 2020-06-30 18:05
Hmmm I just noticed there was another update and I now really have the new version. Sorry for the confusion. Please give me a few hours to test drive the new version. Thanks.

**Comment by hboetes** [comment] 2020-06-30 18:20
Nope, still not recovering. :-\

```
20:08:30 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEff3e69ce703f780ac2a751eb8545de7001 - Let It Come Down.flac
20:10:17 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETE479a55e1437f3a9a5d2a99c036b630f5Oxygen.cue
20:10:18 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETEa9ab1759b1823d9318dde2a0194dc4d801. Oxygen.flac
20:10:35 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETEcbfea18285c94235b431c7311a0b269102. Oxygen (Edit).flac
20:10:46 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETE17db58e08fcadd1da570d4158367062c03. Oxygen (Live At Primavera).flac
20:11:01 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETEd6e639a4d5f10a5c69cf32c10c9b6deb04. Oxygen (Acoustic Version).flac
20:11:12 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETEae29e979c6f04fd9c6541dec4bc71f0e05. Oxygen (Early Version).flac
20:11:23 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETEba31e2eed420df32696ee3d183596bcd06. She Loves Us! (Live).flac
20:11:35 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\01 - Let It Come Down.flac
20:11:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:11:45 Download started: user techxvnode, file /mp3/incoming/tmp/INCOMPLETE02c29a3e9941534570214e8179f9e566Cover.jpg
20:12:07 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:12:12 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEff3e69ce703f780ac2a751eb8545de7001 - Let It Come Down.flac
20:12:29 Download started: user Breadwinner, file /mp3/incoming/tmp/INCOMPLETE15a3e0a1ad7dd7d1e26d5ea26ada975f01 - Pattern Recognition.flac
20:12:35 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\01 - Let It Come Down.flac
20:12:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:13:05 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:13:05 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEff3e69ce703f780ac2a751eb8545de7001 - Let It Come Down.flac
20:13:35 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\01 - Let It Come Down.flac
20:13:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:14:05 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:14:05 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEff3e69ce703f780ac2a751eb8545de7001 - Let It Come Down.flac
20:14:17 Download started: user Breadwinner, file /mp3/incoming/tmp/INCOMPLETEf47fb90d2da4a937458d88b87e9642f4Sonic Nurse.cue
20:14:18 Download started: user Breadwinner, file /mp3/incoming/tmp/INCOMPLETE280e5f97a37cd4149e430f90b451d85e10 - Peace Attack.flac
20:14:34 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\01 - Let It Come Down.flac
20:14:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:15:05 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:15:05 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEff3e69ce703f780ac2a751eb8545de7001 - Let It Come Down.flac
20:15:35 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\01 - Let It Come Down.flac
20:15:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:15:35 Download started: user Breadwinner, file /mp3/incoming/tmp/INCOMPLETEa9d178856109c7efa45ec85dc1b6d53407 - New Hampshire.flac
20:16:05 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:16:05 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEe85db42d0cb0f56972a2661394feac5a03 - Untitled Excerpt.flac
20:16:37 Download started: user Breadwinner, file /mp3/incoming/tmp/INCOMPLETEa8dd57598d7c6106a686bd11647c9bf409 - I Love You Golden Blue.flac
20:17:04 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\03 - Untitled Excerpt.flac
20:17:05 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE996ae1e6d7c30c3f2490c6f591eb18a202 - Blood On Your Hands.flac
20:17:34 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\02 - Blood On Your Hands.flac
20:17:35 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEe85db42d0cb0f56972a2661394feac5a03 - Untitled Excerpt.flac
```

https://i.imgur.com/kHaG9Qx.png

**Comment by hboetes** [comment] 2020-06-30 18:33
This one is in cannot connect mode:
```
20:24:04 Retrying failed download: user STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\04 - Will We Survive.flac
20:25:16 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\04 - Will We Survive.flac
```

After a few minutes it's starts retrying a few 100% files files.

```
20:32:11 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:12 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:12 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:13 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:13 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:14 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:14 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:14 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:15 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:15 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:16 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:17 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:17 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:18 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:19 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:19 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:20 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:21 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:21 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:21 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:21 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:22 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:22 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:23 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:24 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:25 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:25 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\05 - See No More.flac
20:32:25 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:26 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:27 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETEc05d822550fb11256f5a7947e610680605 - See No More.flac
20:32:31 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE5b6b592248cefb17fab0bb69ad959a7506 - Still A Child.flac
20:32:31 Retrying failed download: STG44, file d:\music\drone industrial noise martial dark folk\swans\1990 - anonymous bodies in an empty room\06 - Still A Child.flac
20:32:32 Download started: user STG44, file /mp3/incoming/tmp/INCOMPLETE7c1427ae0aba0b489c7636035fc8674607 - (She's A) Universal Emptiness.flac
```

https://i.imgur.com/YLQce2J.png

**Comment by mathiascode** [comment] 2020-06-30 18:40
Oh no, this looks wrong on so many levels... :]

**Comment by hboetes** [comment] 2020-06-30 18:41
Yeah, this need fixing. :-D

**Comment by hboetes** [comment] 2020-06-30 19:50
Sorry for all the drama. I made a thinko. Yes now it works. Yay! Thanks for giving me the opportunity to test this  thoroughly.

**Comment by mathiascode** [comment] 2020-06-30 19:59
There are still some small improvements that can be made to the transfer system. I ran into a problematic user that keeps closing the connection, which causes the retry spam seen above. I'll probably just remove that kind of auto-retry in favor of the timed one.

**Comment by mathiascode** [comment] 2020-06-30 20:16
I wonder if Nicotine+ somehow gets confused about which downloads are finished or not. One download has downloaded fully, but is still in the temporary downloads folder, which is probably why the user keeps closing the connection.

**Comment by hboetes** [comment] 2020-06-30 21:02
> I wonder if Nicotine+ somehow gets confused about which downloads are finished or not. One download has downloaded fully, but is still in the temporary downloads folder, which is probably why the user keeps closing the connection.

The funny thing is that this problem does resolve itself eventually. Category unpredictable behaviour.

**Comment by mathiascode** [comment] 2020-06-30 21:32
Can you test this branch? It should solve the issues with finished downloads getting stuck in the incomplete downloads folder. (just make sure you actually pull the branch changes)

`git clone -b transferimprovements https://github.com/mathiascode/nicotine-plus`

**Comment by mathiascode** [comment] 2020-06-30 22:10
I made some small changes in that branch, pull the latest ones if you're already using the branch.

**Comment by mathiascode** [comment] 2020-06-30 23:46
Pushed a few more fixes into the branch.

**Comment by hboetes** [comment] 2020-07-01 07:24
Yes, much better! Thanks! I just downloaded a shipload of files, and they all arrived nicely, without the need of constant checking and retrying.

**Closed** 2020-07-01 16:43 UTC
Labels: bug
