### ISSUE TITLE
PORT Issue!

### ISSUE THREAD

**Issue by DeathStalker77** [nicotine-plus/nicotine-plus#2694] opened 2023-10-19 19:12 UTC
Nicotine+ version:   3.3.0.dev5   Python 3.11.6   GTK 4.12.3 (Build from OCT-09-2023
Operating System/Distribution:  Win10x Ent 22H2 19045.3570  Windows Feature Experience Pack 1000.19052.1000.0

### Describe the bug
Unable to open port in any way - default is 1024 - With OR without firewall it makes no difference - no matter WHAT port I set it to, it is CLOSED.  When I set it to the Port that my Port Forwarding uses, it says - Cannot listen on port ####. Ensure no other application uses it, or choose a different port. Error: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

However, the LOG does NOT show this - it indicates NO issue with the default port -
2023-10-19 15:13:30 Listening on port: 1024
2023-10-19 15:13:30 Connecting to server.slsknet.org:2416
2023-10-19 15:13:30 Connected to server server.slsknet.org:2416, logging in…
2023-10-19 15:13:30 1886 privileged users

Any yes, I AM bound to the correct adapter - when I change that, it will not even connect to the server!

I even renamed the config file and started from scratch - it is STILL showing the default 1024 as CLOSED

***Also your INSTALLER remains active - it never completes and shuts down (msiexec.exe)

At this point, I feel my ENTIRE N+ install & config is 100% jakked and I see no way of fixing or restoring it.

### Expected behavior
ANY port select that is open - whether it is Application-Specific in the Firewall (such as Comodo), or Router, should work - as should a RANGE of ports

### Steps to reproduce the bug
Simply set the port for ANY port - whether it is the Port Forwarded Port or not (oddly, in the orig SLSK, I have to set my Port to 1 port LOWER than what is set for Port Forwarding and open in my firewall).  I tried that with N+ as well, but it didn't work

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment] 2023-10-19 20:39
> default is 1024

You are not allowed to use that port, unless you are Administrator. Your OS vendor blocks normal users from having it. Choose another one.

**Comment by slook** [comment] 2023-10-19 21:19
> [WinError 10013]
> However, the LOG does NOT show this - it indicates NO issue with the default port -
> 2023-10-19 15:13:30 Listening on port: 1024

Bug label re-added, the log should reflect the OS error.

**Comment by DeathStalker77** [comment] 2023-10-19 22:37
Ok, I will change the port - I think you also need to either identify that it CANNOT use the same Port as any other application, or simply make it work so that it does - as it is, it is not clear.  I will update to the latest build, change the port, and re-try.

**Comment by DeathStalker77** [comment] 2023-10-19 22:46
No, I still get the PORT CLOSED message no matter WHAT port I choose - even if I put a RANGE of open ports in my firewall (Comodo).

**Comment by slook** [comment] 2023-10-20 01:02
Until recently, it was possible to specify a range, but N+ doesn't really need it so it was only used for fallback.

Hence, the config value is a list of values (start, end) for the purposes of legacy compatibility, otherwise older versions would crash if you had run 3.3.0+ and then rolled back.

**Comment by DeathStalker77** [comment] 2023-10-20 01:04
Ok, but that still doesn't help address the problem I have of it not recognizing ANY port as being open, no matter what the settings are.

**Comment by slook** [comment] 2023-10-20 01:06
If everything is configured as it is supposed to be, then all you can do is keep rebooting and restarting stuff until it works. Some routers can be sticky.

**Comment by DeathStalker77** [comment] 2023-10-20 01:08
It is NOT my router - EVERYTHING else works 100% perfect.  ONLY N+ has an issue - even orig SLSK works fine. 

I will try rolling back to 3.29.

**Comment by DeathStalker77** [comment] 2023-10-20 01:19
Ok, rolling back to a CLEAN install of 3.29 now allows me to set the CORRECT port (that is forwarded) as OPEN.  It would seem there is an issue with your other versions allowing any other program to use the same port - thus the error message above.

Please regression test that scenario and let me know.  Thanks!

**Comment by slook** [comment] 2023-10-20 02:13
What happens when you roll forward to 3.3.0.dev6 again?

**Comment by DeathStalker77** [comment] 2023-10-20 02:14
Tried that - CLOSED again.

**Comment by slook** [comment] 2023-10-20 02:15
Okay now there seems to be a bug confirmed @mathiascode will need to decide what debug logging is needed to find the cause.

**Comment by DeathStalker77** [comment] 2023-10-20 02:19
Happy to be able to help!  As I say, I can test functionality & usability (+design/UX), and I "understand" coding (& logic) - and can read most - but I cannot write code.

**Comment by DeathStalker77** [comment] 2023-10-20 13:52
I will check!  I DO believe that the msiexec.exe issue was resolved with dev6 - it was present from 3.29 through the last dev5 builds.  I am 99.9% certain that I had N+ CLOSED before I ran the dev6 installation.

**Comment by mathiascode** [comment] 2023-10-20 13:57
Thanks! Please check the task manager, in case there's a Nicotine+.exe process where the window closed, but the process didn't exit for some reason.

If that's not the case, and you still have issues with ports, we can continue debugging.

**Comment by DeathStalker77** [comment] 2023-10-20 14:01
I will do so.  I _think_ I have all my setting effectively backed up from the 1st upgrade to dev5, so even though they are "technically" working now (though I cannot use it until the JSON issue is resolved), I can do an upgrade to dev6 without issue and let you know. :-)

**Comment by DeathStalker77** [comment] 2023-10-20 14:13
NEGATIVE!!!  I can confirm 100% that the **msiexec.exe ** remains running after the upgrade to dev6!

**Comment by DeathStalker77** [comment] 2023-10-20 17:15
I'm using a VPN with port forwarding, and Comodo as my firewall - with the appropriate port opened.

**Comment by slook** [comment] 2023-10-29 08:08
Any progress on this?

**Comment by hboetes** [comment] 2023-11-07 00:35
Have you configured the network interface to be used? Select the VPN interface.

**Comment by DeathStalker77** [comment] 2023-11-07 01:48
I have provided @mathiascode with additional info on Port Sharing in another post.  I _have_ to have 2 programs that use Port Forwarding running at the same time and my VPN only supports 1 open port.  YES, it IS possible to have 2 programs access the same port.  (And NO, I will NOT simply not use a VPN, so don't even bother to mention that!)

**Comment by mathiascode** [comment] 2023-11-07 12:56
> YES, it IS possible to have 2 programs access the same port.

I already told you why this is a bad idea.

**Comment by DeathStalker77** [comment] 2023-11-07 14:53
> > YES, it IS possible to have 2 programs access the same port.
> 
> I already told you why this is a bad idea.

You responded, but it was not clear to me WHY you feel it is a "bad" idea.

**Comment by slook** [comment] 2023-12-18 19:31
Are the issues around zombie background processess resolved now?

Sharing a port with other programs is not required functionality.

If an open port can be established that is not used by another program, then this bug can be closed?

**Comment by DeathStalker77** [comment] 2023-12-18 21:39
Not to me they are not.  It is technically feasible for more than one program to use the same port - since MOST people who do P2P use a VPN and MOST VPNs allow only ONE port open for Port Forwarding, this IS an issue for anyone wanting to run N+ with any other P2P program.

Just because you haven't gotten caught "speeding" yet, does not mean you never will - or, just because you've survived a few rounds of "Russian Roulette" does not mean you _always_ will.

**Comment by slook** [comment] 2023-12-18 22:15
Alright, regardless of if sharing a port between programs would be desirable for future implementation or not, the fact is that is not intended functionality.

As it stands, the program is only expected to work on a port that is not used by another program.

Is it working as expected?

**Comment by DeathStalker77** [comment] 2023-12-18 22:20
Point taken!  Yes, it is working as expected, so we could add this as an ENHANCEMENT issue :-)

**Comment by slook** [comment] 2023-12-18 22:25
Alright then, I'll close this Bug issue as resolved for now.

**Closed by slook** 2023-12-18 22:25 UTC
Labels: bug
