### ISSUE TITLE
Choosing "Download containing folder(s)" from search results does nothing

### ISSUE THREAD

**Issue by winchendonsprings** [Nicotine-Plus/nicotine-plus#84] opened 2018-12-06 22:00 UTC

**Comment by winchendonsprings** [comment] 2018-12-06 22:03
When my search results appear and I see a file and I want to download the entire folder that file is with in I right click, choose "Download containing folder(s)." It does work about 20% of the time. The other 80% of the time nothing happens. Nothing in the log window and nothing appears in Downloads tab.

**Comment by tinglycraniumplacidly** [comment] 2019-04-03 04:09
For the 20%/80%, is that for the same search result? Meaning, you try it once and it fails, and then you can keep trying on the same result and eventually it will succeed?

Have you taken a look at your Debug output? Can you post?

I'm asking because when I initially put "I Cn **

**Comment by holytrousers** [comment] 2019-08-30 19:11
have you checked whether your port is open ?
http://tools.slsknet.org/porttest.php?port=2234

**Comment by mathiascode** [comment] 2020-05-20 04:31
I can only reproduce if enable the "I can receive direct connections"-option, but that's because I can't open ports in my network. Could you test the master branch, and ensure that the "I can receive direct connections"-option is only checked if your port is actually open?

**Comment by mathiascode** [comment] 2020-06-16 10:08
I'm going to close this for now, see above.

**Closed by mathiascode** 2020-06-16 10:08 UTC
