### ISSUE TITLE
Leech Detector is bugging people who have folders shared already.

### ISSUE THREAD

**Issue by Tenome** [nicotine-plus/nicotine-plus#1565] opened 2021-09-15 11:00 UTC
Nicotine+ version:  
Operating System/Distribution:
3.1.1  •  GTK 3.24.30

### Describe the bug
Leech detector PMs people who are already sharing a folder (not sure how common it is, only one person has complained so far). Maybe the plugin is impatient and doesn't wait long enough if the user has a large share folder that doesn't immediately load?

**Comment by mathiascode** [comment] 2021-09-15 11:28
The leech detector plugin currently checks the number of shared files and folders sent from the server (visible in room user lists and user info), but this is unreliable due to bugs in SoulseekQt clients where they don't send the correct info to the server. We'll probably have to read the values from the user browse responses instead.

**Comment by slook** [comment] 2021-09-15 11:35
> not sure how common it is

This is fairly common. I believe it is possible that this happens when the plugin user has specified one or both of the "Least number of shared folders / files" parameters to a non-default value (more than 1). It would be useful if the plugin included/appended those parameters within the default message, but it doesn't.

> We'll probably have to read the values from the user browse responses instead.

I'm not sure that downloading users would want to receive notifications that "x user is browsing your shared files" from this plugin, because that would making it difficult to determine/log if it was a human browsing or not.

**Comment by mathiascode** [comment] 2021-09-15 11:50
> I'm not sure that downloading users would want to receive notifications that "x user is browsing your shared files" from this plugin, because that would making it difficult to determine/log if it was a human browsing or not.

It's too late for that. SoulseekQt also has a leech detector feature that has been using this method for years now.

**Comment by slook** [comment] 2021-09-15 11:58
Perhaps it is acceptable only in the error condition where a value of 0 is returned, by implementing the method as a fallback procedure.

> the number of shared files and folders sent from the server ... is unreliable due to bugs in SoulseekQt clients

Perhaps the Leech Detector plugin could be made able to workaround the known server bug, by giving the requesting requesting client the benefit of the doubt (and only send the message after verifying the 0 value with User Browse fallback method).

**Comment by Tenome** [comment] 2021-09-15 17:40
> I'm not sure that downloading users would want to receive notifications that "x user is browsing your shared files" from this plugin, because that would making it difficult to determine/log if it was a human browsing or not.

Is that not what the N+ script does already? I get those notifications in the bottom activity log fairly often when I'm browsing. I was assuming that I was triggering their leech detector plugin as well (I've never gotten a leech PM myself by accident either).

**Comment by mathiascode** [comment] 2021-09-15 19:57
> Is that not what the N+ script does already?

SoulseekQt does this.

**Comment by Tenome** [comment] 2021-09-16 09:59
Huh, the more you know. I didn't know SoulseekQT had a leech detector.

**Comment by slook** [comment] 2021-09-22 03:16
> Maybe the plugin is impatient

Upon investigation @Tenome I think that the most obnoxious thing about it, is way the private message is received as soon as any download is attempted. If this turns about to be an error then it is most infuriating. I had never ran this plugin myself before, only been on the receiving end of it. This is what made me keen to see what I could do about it.

-  **It would be highly preferable if this wasn't bugging new users so much. The pop-up notifications that immediately appear on click make the client and network appear spammy, especially on first run of a new user account.**

> a large share folder that doesn't immediately load?

During my testing I found that slsk accounts that are newly created seem to be the worst affected by the rouge messages from the Leech Detector, even when public shares have been configured. Perhaps it takes a while for the server to gather the statistics, I think there are multiple factors involved here, it seems to settle down significantly after a few days after using freshly installed client and username, once the other users clients have already dealt with me.

In my forked version on https://github.com/slook/nicotine-plus/blob/master/pynicotine/plugins/leech_detector/__init__.py I have calmed it's behaviour down by waiting to send the complaint message until after several successful transfers. This seems to be much more polite, as it is less likely to appear whilst the user is in the middle of operating the interface.

Additionally, I have added a feature to tolerate a configurable number of downloads before considering a user to be a leecher, which is made possible by new hooks that @mathiascode recently added into the plugin system. My preference is 20, as I don't mind if someone wants to gather enough to fill up Compact Disc (a vintage technology) that seems reasonable to me. The private message is only sent after the 20th download is completed (or any number between 1 and 999 set in Plugin Properties).

Following your bug report I have also added an option to skip clients reporting as zero files and zero folders. In addition to the buggy Qt clients, the most common reason for this I have found is users who have set all their shares to Buddy only. In this scenario, I would say it's unlikely that immediately sending them an automated message will do anything to change their mind about that, however after the 20th download this has resulted in a couple of opportunities for rather more polite conversations, where I was granted access without contest, on account of having justified reason for asking.

Whilst this isn't a proper fix for the bug, this different strategy greatly mitigates the issue, but would require widespread adoption for it to be effective. To this end, I am aiming to merge into master for Nicotine+ 3.2.0.dev1

Due to the nature of this plugin, testing is very difficult, so I would appreciate some feedback if anyone has the time to review it. It's in my personal repo or you can copy it from https://pastebin.com/47tGLu8c

**Comment by mathiascode** [comment] 2021-10-17 12:35
Note to self: if a Nicotine+ user shares a lot of files, and rescan on startup is enabled, there may be a small window where their shares are empty after logging in. This could trigger leech detectors that check the contents of the share.

Verify what slskQt does in this scenario.

**Comment by mathiascode** [comment] 2021-11-03 19:55
> Note to self: if a Nicotine+ user shares a lot of files, and rescan on startup is enabled, there may be a small window where their shares are empty after logging in. This could trigger leech detectors that check the contents of the share.
> 
> Verify what slskQt does in this scenario.

Should be improved in https://github.com/nicotine-plus/nicotine-plus/commit/40d87746d05190d5a522277e6efa4f6d53fc0266

**Comment by slook** [comment] 2021-11-05 20:46
This is interesting that the statistics are cached by the scanner, certainly if this improves accuracy of the file count being sent out that can only be a positive step in the right direction.

Do you think it will be necessary for the plugin to trigger a browse shares request to verify zero stats? If so then do you have a plan for interrogating remote machines in the background, ie without creating a visible Browse Shares tab?

I am looking at the mechanism in `make_new_model()` and `create_folder_tree()` in [userbrowse.py](pynicotine/gtkgui/userbrowse.py) but these GUI procedures are not designed for running in the background. It makes me wonder if some of this code should be moved into the core.

**Comment by mathiascode** [comment] 2021-11-05 21:09
> Do you think it will be necessary for the plugin to trigger a browse shares request to verify zero stats? If so then do you have a plan for interrogating remote machines in the background, ie without creating a visible Browse Shares tab?

I had a plan for this, but now I realize that we have a problem. You only need to read the first few bytes of the shares message to determine the number of shared folders, but would have to parse the whole message in order to sum up the number of shared files, which can take a very long time and waste bandwidth. SoulseekQt avoids this issue, since it only checks the number of shared folders.

At this point, I'm not sure if it's worth implementing the shares request.

**Comment by slook** [comment] 2021-11-05 23:04
> the first few bytes of the shares message to determine the number of shared folders

Interesting, how would this be done?

> SoulseekQt avoids this issue, since it only checks the number of shared folders.

I feel we should do the same, and then disregard the plugin's minimum required number of files in the particular case of a zero count according to the server, then it can be assumed the file count is likely to be wrong as well. Whilst this wouldn't be entirely accurate to the user's plugin settings, it would help for this scenario.

> You... would have to parse the whole [shares] message in order to sum up the number of shared files

I see, indeed whilst this is inexpensive to do if the client is already building a TreeView for browsing, iterating all the folders just to do a count is heavy and can take a long time as you rightly say, I have observed this to the point where transferring a file might be completed first, so this would need handling and adds a lot of complexity. A closed port might prevent getting the count using this method, so that would need handling too.

> I'm not sure if it's worth implementing the shares request. It wouldn't help much 

I disagree, I think it would help if we were able to get an up-to-date folder count in an efficient manor, or at least reliably establish if a failure to retrieve the folder stats might be due to a local fault.

I think there are other ways that could indeed help more, you should try the version of the plugin on my fork which tolerates a certain threshold number of files before complaining (20 by default), I think that is an idea worth implementing.

Also it was suggested to me that it would be a very good idea to persistently store known leechers in a JSON file, because that would stop users being repeatedly plagued by spam complaints each time the plugin is restarted, which I think could be the more major issue that causes the bugging.

**Comment by mathiascode** [comment] 2021-11-05 23:29
> > the first few bytes of the shares message to determine the number of shared folders
> 
> Interesting, how would this be done?

Parse the number of folders, discard the rest of the message. https://github.com/nicotine-plus/nicotine-plus/blob/377a2b2faf851b838a78b59af2c55ca23072e6c4/pynicotine/slskmessages.py#L2197

> I disagree, I think it would help if we were able to get an up-to-date folder count in an efficient manor, or at least reliably establish if a failure to retrieve the folder stats might be due to a local fault.

Well, have fun with that. I have a feeling this is one of those issues where people will be dissatisfied no matter what is done.

**Comment by slook** [comment] 2021-12-08 14:37
It's probable that some Qt users buggy client's send only the folder count, as indicated by 0 files in 1 folders of a user who responded to my debug message stating that was incorrect because there were files in his shared folder. Perhaps this could be the edge case for the chk_zero_num condition in is_leecher()

**Comment by mathiascode** [comment] 2021-12-08 15:41
> It's probable that some Qt users buggy client's send only the folder count, as indicated by 0 files in 1 folders of a user

I don't quite remember the specifics, but I think it was something related to network shares and SoulseekQt not scanning folders in time for the folder/file count sent to the server.

**Comment by slook** [comment] 2021-12-08 18:39
I seem to remember that Qt doesn't even bother counting the files, it only uses the folder count for it's leech detection. 0 files in >=1 folders would seem to be a strong indicator of such clients, although it is far from guaranteed.

I have also observed 0 files in many folders such as >100, it seems highly unlikely that all those folders would be empty.

**Comment by rcz01** [comment] 2021-12-20 07:55
I can confirm that there is a bug in QT and it lists folders/files in UserInfo as 0, especially for people who share a lot of files. It is especially visible in Buddy List - tons of people who have 0/0 but have upload speed listed - those are bugged ones.

About checking file shares - it is possible and actually fairly simple. But it comes with its own issues - sometimes files shares take forever to load, which is not a problem. You can just let user download until processing finishes.
But there is a bigger one - sometimes they start loading but never finish (network issues, I suppose). The only way to make them finish it to "nudge" them, by sending another browse shares request. But to do this, you need to implement a timer to check if shares loaded and periodically and if they haven't after certain period, retry.

How do I know this? My plugin does this. But the main problem is the timer - I use a hack that requests User Stats to implement a very crude timing loop, but that is rubbish and needlessly introduces a lot of pointless traffic. It seems Threading.Timer could work, but I'm not Python dev - this plugin was first thing (and only so far) I ever wrote in Python, so I don't know how to fix it. It is in "if refreshing:" block (line 85).

Code is below, feel free to do whatever you want with it. I think it should fairly easy to follow but give me a shout if you have any issues. You will find a lot of old commented code - it's the stuff that used to work in previous Nicotine releases - but doesn't any more. You're changing Nicotine too much! :P

https://pastebin.com/VRWrR0ET

**Comment by slook** [comment] 2021-12-20 23:48
Thank you for your insight @rcz01 that is an interesting approach to workaround the bug in the Qt client.

I can see that you have had issues with dependency on the N+ GUI, since this is a constantly evolving thing we would need a solution that is closer to the core that reads directly from the server message containing the browse shares response data.

However, I think we have decided not to implement any workaround for the file stats bug for the time being. As highlighted by your code there are significant drawbacks and complexity that becomes involved when making a browse shares request, and this only aims to solve a problem that shouldn't exist in the first place (if the UserStats sent by the Qt client were not wrong), so all this extra grunt work would seem to be introducing new bugs and require yet more hacks that are not suitable for the built-in plugin.

> a bug in QT and it lists folders/files in UserInfo as 0, especially for people who share a lot of files

That is interesting that you have observed the problem seems to be more prevalent for Qt users with a large number of files, perhaps that information would be useful to help fix the bug at it's source.

**Comment by rcz01** [comment] 2021-12-21 07:52
Yes, dependency on GUI has forced me to re-write parts of the plugin few times in the last 2 years. Last time 3 days ago :) Long time ago there used to be a variable in userbrowse.py (I think) called total_shares. Then it got orphaned (was still there for some time, but empty). Then you started moving things around to optimise N+ even more :) 
It would be nice to have a bunch of standard abstracted methods you could call from plugins to perform standard tasks, e.g. browse shares, message, download, ban/add, without the need to call actual methods in modules. That coupled with standard data structures, e.g. shares, stats, buddy/ban list, would decouple plugins from underlying code changes.

This bug in Slsk has been around since always - was also present in original Slsk 20 years ago. I'm not sure how it is now, but Slsk used to rescan shares on startup. If that wasn't done fast enough it used to report 0 to server. So any shares on remote shared folders were slowing rescans and were resulting in 0. I had this issue when I used Slsk ages ago. One of the workarounds was to log off from server before closing, then start up, let it rescan and then connect to server afterwards.

**Comment by mathiascode** [comment] 2021-12-21 15:14
> Yes, dependency on GUI has forced me to re-write parts of the plugin few times in the last 2 years. Last time 3 days ago :) Long time ago there used to be a variable in userbrowse.py (I think) called total_shares. Then it got orphaned (was still there for some time, but empty). Then you started moving things around to optimise N+ even more :)

There has been an ongoing effort to decouple the GUI from the core, hence the large rewrites (a long process due to the mountain of spaghetti code that Nicotine+ was). The core should be mostly stable at this point, but the GUI code will likely change somewhat as final cruft is cleaned up. The plan is to de-emphasize access to `self.frame` for anything non-GUI related, since plugins don't work in headless mode otherwise. `self.frame.np` can be replaced with `self.core` in plugins.

> It would be nice to have a bunch of standard abstracted methods you could call from plugins to perform standard tasks, e.g. browse shares, message, download, ban/add, without the need to call actual methods in modules. That coupled with standard data structures, e.g. shares, stats, buddy/ban list, would decouple plugins from underlying code changes.

I want to do this eventually, but I need to know exactly what plugin devs want to access. Concrete code suggestions are welcome.

**Comment by rcz01** [comment] 2021-12-21 19:36
Makes sense. 
Regarding plugins - I wonder if we could make a poll on reddit, slsk chat or wherever people discuss slsk/N+ to check what type of plugins would like to see, even if they don't exist right now. It would also give idea to plugin writers what is in demand.

**Comment by slook** [comment] 2021-12-21 22:22
Plugins discussion thread: https://github.com/nicotine-plus/nicotine-plus/discussions/1540

**Comment by rcz01** [comment] 2021-12-21 22:58
I was thinking about approaching it from other side: users. If we know there is demand for certain type of plugins, there is a chance somebody will try to make them. If there are easy methods to call and clear data structures to access it will make plugin creation easier, thus allowing more people to try. It all kind of works in a circle

**Comment by slook** [comment] 2022-02-21 18:36
> If there are easy methods to call and clear data structures to access it will make plugin creation easier

Tidying up the data structures in the pynicotine core is an ongoing effort, and unfortunately it has been inevitable that compatibility with some plugins have broken along the way, because it is impossible to know what methods plugin devs have needed to hack around in order to get their plugins to work due to some core modules being neglected for many years.

> It would be nice to have a bunch of standard abstracted methods ... decouple plugins from underlying code changes

I agree, some tasks are more difficult than they should be, I encourage you to look at the core to see if anything can be simplified to make plugin development more accessible.

> Standard data structures, e.g. shares, stats, buddy/ban list

This is difficult to do in a memory efficient way, because some of the lists can be very large and complex to manage without consuming too much system resources and adding complexity into the core. Hopefully this will improve over time (ideally in a backwards compatible manor).

> If we know there is demand for certain type of plugins, there is a chance somebody will try to make them.

That is up to the community to decide if there is a need/desire for particular functionality, and if it turns out that limitations in the Nicotine+ core prevent or hinder plugin development, then concrete code contributions are always welcome.

**Closed** 2023-11-11 12:45 UTC
Labels: bug
