### ISSUE TITLE
Can't share a virtual file system

### ISSUE THREAD

**Issue by JediMaster25** [nicotine-plus/nicotine-plus#2146] opened 2022-08-09 15:19 UTC
Nicotine+ version:  3.2.3-1
Operating System/Distribution: Manjaro Cinnamon

I create a VFS with supertag. It contains many folders and symlinks to files. It contains many symlinks to the same files in different folders. Then I add it to shares, the bar that indicates it's analyzing the shares appears and then stops, and when I open the shares the folder has disappeared. I have tried to add it a few times, I've clicked apply and ok after adding it but it never stays.

**Comment by mathiascode** [comment] 2022-08-09 15:46
Upgrade to Nicotine+ 3.2.4: https://nicotine-plus.org/NEWS.html#version-324-august-7-2022

**Comment by slook** [comment] 2022-08-09 17:00
Closing as duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2142

**Closed by slook** 2022-08-09 17:00 UTC
Labels: bug, duplicate
