### ISSUE TITLE
The Columns Is A Bug Not An Enhancement

### ISSUE THREAD

**Issue by 0pLuS0** [Nicotine-Plus/nicotine-plus#79] opened 2018-05-13 00:55 UTC
@Mutnick hello,

I first want to say that I am not trying to be disrespectful here, but just trying to get your attention, because in all honesty, when I made the last post over the development being dead, I truly thought it was.

I made a reply 3 months ago for the Columns with no word back, but I deleted those replies since then;

https://github.com/Nicotine-Plus/nicotine-plus/issues/8

So this is one reason I am trying to reach out to you, so please understand, again this is no disrespect, I understand it's Open Source, no one gets paid and you have a life, etc...

But when the post was originally made, gfarmerfr labeled it as an ```Enhancement``` and I never really paid attention to that.

I realized now this is a mistake and this is a ```Bug``` with the UI that needs to be fixed...

I understand there may be other areas of importance, that maybe your even working on, but I hope that getting a UI to function correctly would have some priority.

I hope you are not upset I made this post to get your attention, and thank you for your time and help and consideration, I just think nicotine is such a great piece of software and I too have been waiting years for this to get fixed by someone and then gfarmerfr comes along and then has to leave...

THANKS

**Comment by 0pLuS0** [comment] 2018-07-05 01:02
@Mutnick any word on future development, is the project still alive?

Thanks

**Comment by 0pLuS0** [comment] 2018-09-20 00:40
@Mutnick hi, are you still working on nicotine-plus?

If so, any chance of getting this issue fixed any time soon?

Thank you

**Comment by 0pLuS0** [comment] 2018-10-26 01:07
@kiplingw are you also working on this project, that you might be able to fix this?

Thanks

**Comment by kiplingw** [comment] 2018-10-26 01:54
Hey @0pLuS0. @Mutnick is actually the primary project lead. I haven't heard from him in a while either. You can try reaching him at gfarmerfr at free dot fr. We also have a \#nicotine channel on Freenode you're welcome to idle in - though I haven't seen @Mutnick in it in quite some time.

**Comment by 0pLuS0** [comment] 2018-10-27 00:28
@kiplingw

You gave me gfarmerfr's email address and I reached out to him last year, he's tied up.

 Mutnick seems to be MIA too... :(

You can't code on this too, and fix it?

This is so sad that it has UI issues that have gone on for years... :(

Maybe if you can't code/fix this, you can find some other Coding Buddies that can, or round some up?

I personally don't get why someone would let this Project/App die, when you consider SoulSeek, there is nothing that stands up to it's level...

Hmm

**Comment by kiplingw** [comment] 2018-10-27 01:54
I actually don't do a lot of Python, but if you happen to submit a patch I'd be happy to review it for you. And yes, I agree Nicotine+ is a great project which gives access to a great network.

**Comment by 0pLuS0** [comment] 2018-10-28 23:49
I'm not a coder, so I have no ideas here...

I've been Geeking it many years in the area of P2P and for music nothing can tough this, and it's just so sad seeing the project dead! 

@ kiplingw, maye you can round up some Geek Coder Buddies? Or figure out some way to do this?I know there's the bounty site, but I mean, whatever circles you hang in, maybe spread the word around...

I'm trying to think where I can spread it around too...

I'm mean seriously this is a joke, like people don't like music and don't use Linux who like Music...

Last time I checked Music was a pretty big thing in the world, hmm I guess not so much for P2P and Linux on SoulSeek then...

Ahhhhhhh :(

**Comment by 0pLuS0** [comment] 2018-10-28 23:51
I'm not a coder, so I have no ideas here...

I've been Geeking it many years in the area of P2P and for music nothing can touch this, and it's just so sad seeing the project dead! 

@kiplingw, maybe you can round up some Geek Coder Buddies? Or figure out some way to do this?I know there's the bounty site, but I mean, whatever circles you hang in, maybe spread the word around...

I'm trying to think where I can spread it around too...

I'm mean seriously this is a joke, like people don't like music and don't use Linux who like Music...

Last time I checked Music was a pretty big thing in the world, hmm I guess not so much for P2P and Linux on SoulSeek then...

Ahhhhhhh :(

**Comment by kiplingw** [comment] 2018-10-28 23:54
@0pLuS0, when you manage to round up some "Geek Coder Buddies" and your patch is ready for submission, the volunteers here will be happy to review it.

**Comment by 0pLuS0** [comment] 2018-10-29 01:28
@kiplingw, volunteers?

Who, where is this group of volunteers you are mentioning?

I'm only seeing you alive around here for now...

Hmm

**Comment by 0pLuS0** [comment] 2019-02-12 05:48
Anyone know anything going on with this project?

There's been no development in 2 years, and I'm still holding my breath, so sad, such an awesome application, and like no one uses it?

Hmm

**Comment by isAAAc** [comment] 2019-02-12 11:39
i use the app sometimes, but i don't know anything if someone is still maintaining it :/

**Comment by 0pLuS0** [comment] 2019-02-12 22:12
@isAAAc No one is maintaining it, I asked if anyone knew what is going on is all.

Sad to see this die, the truth is, which no one seems to realize is for a P2P music app like this, there is no equal, and that in and of itself is why it's so odd, that this would die off too... hmm

**Comment by kiplingw** [comment] 2019-02-12 23:45
Hey guys. Nicotine+ is not dead. Our project lead has been away with other responsibilities but never gave any indication his absence was permanent. Further, it hasn't been two years of inactivity, but only one if you examine the git log.

**Comment by 0pLuS0** [comment] 2019-02-13 00:30
@kiplingw that was a Version Bump, I hardly see that as qualifying as "Development", don't mean that as rude, but it's not development...

Anyhow, sad to see this die, it's sorely needed...

So any really actual software development has been 2 years...

**Comment by kiplingw** [comment] 2019-02-13 01:03
I've just emailed gfarmer. I tried a few months ago but was having mail server issues. I'll let you know if I hear back from him. Admittedly even a year is too long.

**Comment by 0pLuS0** [comment] 2019-02-13 03:24
I was in contact with him the past, needed to move on in life...

Truth is, we need someone else to take over...

**Comment by kiplingw** [comment] 2019-02-13 04:26
I agree we need to continue development. But it seems odd gfarmer would leave without any comment. I just assumed he was dealing with other things.

**Comment by 0pLuS0** [comment] 2019-02-13 05:39
Hey people have a life, they move on...

gfarmer is gone, that's over, I contacted him years back and he said he can't work on this.

We just need to get someone else is all.

**Comment by 0pLuS0** [comment] 2019-09-26 02:09
@vsedach or @Mutnick Hi

Do either of you have the coding skills to fix this columns issue?

Thanks

**Comment by kiplingw** [comment] 2019-09-26 02:12
@0pLuS0, see https://github.com/Nicotine-Plus/nicotine-plus/issues/79#issuecomment-433754349.

**Comment by 0pLuS0** [comment] 2019-09-26 23:45
I don't have Geek Coder buddies, or know someone, I thought maybe I mentioned that before. 

Also I was hoping to hear from either @vsedach or @Mutnick, so are you speaking on their behalf too, that neither of them, or anyone that is helping on this project has the coding skills?

THANKS

**Comment by vsedach** [comment] 2019-09-26 23:52
0pLuS0 <notifications@github.com> writes:

> Do either of you have the coding skills to fix this columns issue?

What issue are you talking about?

--
Vladimir Sedach
Software engineering services in Los Angeles https://oneofus.la

**Comment by 0pLuS0** [comment] 2019-09-27 23:00
@vsedach Hi,

I listed the issue in the beginning #8

Thanks

**Comment by vsedach** [comment] 2019-09-28 02:14
0pLuS0 <notifications@github.com> writes:

> @vsedach Hi,
>
> I listed the issue in the beginning #8
>
> Thanks

That looks fairly straightforward.

Here are a couple of freely available books you can use to learn
Python and fix the issue:
https://automatetheboringstuff.com/
http://greenteapress.com/thinkpython/html/index.html

Check out the #python IRC channel on irc.freenode.net if you have questions.

--
Vladimir Sedach
Software engineering services in Los Angeles https://oneofus.la

**Comment by 0pLuS0** [comment] 2019-09-28 23:01
I'm not in any position at present, or in the future to get into coding.

I'm only reporting the issue and hoping someone can fix it.

It is a bug in the application, that needs fixing.

THANKS

**Comment by kiplingw** [comment] 2019-09-28 23:30
@0pLuS0, we're all volunteers here and most of us don't have time to supply patches. We appreciate your enthusiasm, but if you cannot provide a patch after repeated inquiries here on the status of the reported issue, then please consider offering a [bounty](https://en.wikipedia.org/wiki/Bounty_(reward)#Open-source_software).

**Comment by 0pLuS0** [comment] 2019-09-30 23:45
@kiplingw

I'm a Geek, I know how Open Source works. I've been asking because I noticed other people I didn't recall seeing before like vsedach. So if you look back on this ```Issue Report``` you will see that I've never mentioned vsedach until now. I've only asked about Mutnick in the past, and as the ```Project Lead``` you mentioned, I was hoping to finally hear a word by now in all this time.

You don't have to keep mentioning about ```volunteers``` etc., I'm just asking people is all that I didn't before, and hopefully someone might float along here and catch eye to this and jump on board who knows...

Anyhow I just hope in here every once and awhile to see what's going on is all, hopefully the project will pick back up...

THANKS

**Comment by kiplingw** [comment] 2019-10-01 00:43
> Bountys, yes, I know them of course, no need to point me to a Wiki like a Noob. and it's also not about enthusiasm, but I see activity and then no one is following up on the Issue Reports like Geeks should be doing to show people what's happening with the Project, afterall there are commits happening...

I'm going to make a suggestion to you that you stop referring to people you've never met as "geeks". For a lot of people it's a pejorative. If you want to refer to yourself as that, by all means do so.

> `P.S. I'm not a coder, don't like coding, coding isn't my thing, so I can't provide a patch, otherwise if I was into coding then I would, and it's been 7 months since I last checked the status of this issue...`

Then as I said already, offer a bounty and you just might see your issue prioritized.

**Comment by 0pLuS0** [comment] 2019-10-02 22:54
A Geek is actually an expert or enthusiast in their chosen passion. The pejorative you speak of, is the ignorant that still continue to think and look at it in the same manner, as when the word was first coined, and that was a long time ago, and the pejorative is dead, Geeks are Experts...

Anyhow, enough said, I'll just keep my eyes on the project, and hopefully in time it will get picked back up...

PEACE

**Comment by mathiascode** [comment] 2020-05-19 01:03
This issue seems to be fixed in the master branch.

**Comment by mathiascode** [comment] 2020-05-19 01:10
Actually, the directory column keeps reappearing, but https://github.com/Nicotine-Plus/nicotine-plus/issues/8 can be used to track that issue instead. I'll check what the issue is.

**Closed** 2020-05-19 02:54 UTC
