### ISSUE TITLE
Port to python3

### ISSUE THREAD

**Issue by dvzrv** [Nicotine-Plus/nicotine-plus#99] opened 2019-11-19 12:00 UTC
Will nicotine+ be ported to python3?

I see very little activity in the repository in the past months and would just like to highlight, that [python2 is soon EOL](https://pythonclock.org/).
This means, that many Linux distributions will drop all python2 based software shortly thereafter from their repositories.

If no port is attempted: Are there alternatives?

**Comment by zniavre** [comment] 2019-11-19 12:38
re-install python2 and make it running as usual ....

**Comment by dvzrv** [comment] 2019-11-19 19:06
> re-install python2 and make it running as usual ....

How very... helpful.

**Comment by bernd-wechner** [comment] 2019-11-19 19:54
> re-install python2 and make it running as usual ....

An option. But many of us are glad to see Python 2 go ...  and the question was if there are any alternatives. But yes the SoulseekQT client still works methinks.

http://www.soulseekqt.net/news/node/1

It's no Open Source, but it works.

The port to Python3 is a job indeed, but not a huge one (process is simple enough especially if there's a test suite that has good coverage already built, but test the existing code base, then [automate](https://docs.python.org/2/library/2to3.html) a translation, then the big job - mop up the rest, fix the bits that don't work no more no more). 

Alas I can't make time for it as I'm not using Nicotine anyhow precisely because it's seemed unmaintained and without a community supporting it for some years now ...  Living software doesn't use python 2, and won't in future. The EOL for python 2 simply catalyses EOL for a lot of unmaintained python 2 code - that is seen by some, as a sort of benefit).

**Comment by thismachinechills** [comment] 2020-01-09 19:18
I've been using this software for like 15 years and am willing to port the pynicotine portion of Nicotine+ over to Python 3. If anyone would like to participate, ping me on my personal site

**Comment by lene** [comment] 2020-02-10 09:33
I've done some work at https://github.com/lene/nicotine-plus/tree/python3. As soon as I can get the client to do something useful, e.g. connect to the server, I'll open a PR here.

**Comment by dvzrv** [comment] 2020-02-10 16:38
@lene that's great news. Thanks for your work on this!

**Comment by kiplingw** [comment] 2020-04-28 00:58
Just letting everyone know that I hope to have @lene's porting work merged as soon as possible. After that I'd like to ask everyone to please test as much as possible from the unstable PPA. If everything works properly we will release it as stable 2.0.0.

**Comment by bitchkat** [comment] 2020-05-11 00:27
I just tested the latest git master on fedora 32 today and everything appears to be working -- at least I can search files, download. upload.  It is spewing a lot of messages to output regarding 'Connection closed by peer'  also 'Found meta data that couldn't be encoded, possible corrupt file'  on some flac files.  No other program -- picard, kid3, clementine is having problems reading the tags.

**Comment by Seegras** [comment] 2020-05-14 08:20
Same here, it works! But I've got "Found meta data that couldn't be encoded, possible corrupt file: 'somefile.mp3' has a bitrate of 320 kbs, a length of 252 seconds and a VBR of 0" for all the MP3s I tried to share.

**Comment by zniavre** [comment] 2020-05-17 08:06
good morning testing day2
flags randomly displayed or not for some users , instead of "world-flag"

my case "><((((*>" i need to check my own ip via right clic option to get my flag  for others users where flags missings also i hav to check their ip first to see their flags

screenshot > https://imgur.com/a/k6oylTt <

**Comment by kiplingw** [comment] 2020-05-17 22:17
@zniavre, I just updated the runtime dependencies to add `python3-geoip`. After the unstable PPA builds it, can you please see if you're still having the same problem?

**Comment by zniavre** [comment] 2020-05-18 11:37
same behavior... do i hav to precise im using the ppa tar.gz ? not the complete installation via .deb, python3-geoip is installed.

**Comment by emilazy** [comment] 2020-05-18 15:27
@kiplingw Now that things have settled down a bit around the port and Debian-derivative users are encouraged to test via the PPA, would you be happy to see it in the unstable NixOS channel for testing?

It seems the remaining major issues are to do with the Debian-specific packaging, and I managed to get the integration tests running in the Nix CI environment with the move to Robot Framework. This way there'd hopefully be real-world testing by users of more than one distro family before a stable release is made, and users who have opted-in to run the unstable rolling release channel and test updated packages out would benefit from the [several years of other bugfixes](https://github.com/Nicotine-Plus/nicotine-plus/compare/1.4.1...ad6e55af3e2acf845ee81171f1947ef1c21dae44) that haven't made it into a stable release. Of course, I'd update the package again in a timely manner when a stable release comes out, and can mark the version as unstable.

Some things I noticed when updating the Nix package:

* I'm a little confused by the addition of `python3-notify2` to the Debian package dependencies; it's not listed in `requirements.txt` and as far as I can tell the code never imports it. Is it meant to be a dependency of the package? I suggested moving to `notify2` in https://github.com/Nicotine-Plus/nicotine-plus/pull/106#issuecomment-620323974 but I don't think the work has actually been done for that yet ^^;

* Commit 666100f49107c8779f96d5c56ef44a2d99afaf90 broke functionality; the manual was meant to be installed with the package and now the "Help → Offline Nicotine+ Guide" menu entry is broken. Not sure what the intention is, but if it the manual isn't intended to be restored then the menu entry and `OnNicotineGuide` in `pynicotine/gtkgui/frame.py` can be removed.

(I can open issues for these if you'd prefer.)

**Comment by mathiascode** [comment] 2020-05-18 17:53
I haven't done any extensive testing, but basic functionality (downloading, searching, browsing user files) has worked just fine for me. Transfer lists and databases created in 1.4.1 will not be recognized in newer versions though, due to different file names (https://github.com/Nicotine-Plus/nicotine-plus/commit/5f847aead65516c0b75e46e379aaef6f02dc59ab) and Python3 changes in the pickle module used for the transfer list.

**Comment by kiplingw** [comment] 2020-05-18 17:54
> same behavior... do i hav to precise im using the ppa tar.gz ? not the complete installation via .deb, python3-geoip is installed.

Yes, please always use the Debian package. Installing from source is something you should only do if you are a developer. Otherwise it is dangerous to install outside of the FHS and the system package manager's oversight. The package should also ensure you have the correct dependencies installed (hopefully).

**Comment by kiplingw** [comment] 2020-05-18 17:54
> I haven't done any extensive testing, but basic functionality (downloading, searching, browsing user files) has worked just fine for me. Transfer lists and databases created in 1.4.1 will not be recognized in newer versions though, due to different file names ([5f847ae](https://github.com/Nicotine-Plus/nicotine-plus/commit/5f847aead65516c0b75e46e379aaef6f02dc59ab)) and Python3 changes in the pickle module used for the transfer list.

Yes, although hopefully that isn't that huge of an inconvenience for people. The shares database fortunately is easy to regenerate.

**Comment by kiplingw** [comment] 2020-05-18 18:03
> @kiplingw Now that things have settled down a bit around the port and Debian-derivative users are encouraged to test via the PPA, would you be happy to see it in the unstable NixOS channel for testing?

Hey @emilazy. You're certainly welcome add it to an unstable channel for NixOS. Honestly I know very little about it.

> It seems the remaining major issues are to do with the Debian-specific packaging, 

There may be some remaining, but most of the issues are going to be with the port itself. There have been a number of issues that are popping up, likely do to changes in the Gtk API and Python 3 which were difficult for @lene to foresee all of.

> and I managed to get the integration tests running in the Nix CI environment with the move to Robot Framework. 

I'm not sure how CI is performed on NixOS, but the standard we use which is suppose to be distro agnostic is DEP-8. On Debian this is implemented as `autopkgtest`. However it is that you are running the CI tests you need to ensure that they are running in a hermetically sealed container to ensure that there is nothing on your system that influenced the way the tests were performed. The best way to do this is by following the testing instructions I am about to add to the README.md shortly.

>This way there'd hopefully be real-world testing by users of more than one distro family before a stable release is made, and users who have opted-in to run the unstable rolling release channel and test updated packages out would benefit from the [several years of other bugfixes](https://github.com/Nicotine-Plus/nicotine-plus/compare/1.4.1...ad6e55af3e2acf845ee81171f1947ef1c21dae44) that haven't made it into a stable release. Of course, I'd update the package again in a timely manner when a stable release comes out, and can mark the version as unstable.

Yup. I'm totally fine with that. I'd also suggest submitting a PR for the README.md for instructions on how users can obtain NixOS packages for unstable and stable, like what we've done with Ubuntu.

> Some things I noticed when updating the Nix package:
> 
>     * I'm a little confused by the addition of `python3-notify2` to the Debian package dependencies; it's not listed in `requirements.txt` and as far as I can tell the code never imports it. Is it meant to be a dependency of the package? I suggested moving to `notify2` in [#106 (comment)](https://github.com/Nicotine-Plus/nicotine-plus/pull/106#issuecomment-620323974) but I don't think the work has actually been done for that yet ^^;

@lene, do we actually need that package? If not I'll remove it from the Depends stanza.

>     * Commit [666100f](https://github.com/Nicotine-Plus/nicotine-plus/commit/666100f49107c8779f96d5c56ef44a2d99afaf90) broke functionality; the manual was meant to be installed with the package and now the "Help → Offline Nicotine+ Guide" menu entry is broken. Not sure what the intention is, but if it the manual isn't intended to be restored then the menu entry and `OnNicotineGuide` in `pynicotine/gtkgui/frame.py` can be removed.

I've just removed that from the UI. That manual appeared unfortunately to be really old and no longer maintained. If someone decides to take it up again, it can be restored from Git.

**Comment by mathiascode** [comment] 2020-05-18 18:07
Probably better to just start anew instead of attempting to migrate the dbs into something Python 3 recognizes.

**Comment by bitchkat** [comment] 2020-05-18 18:11
> Yes, please always use the Debian package. Installing from source is something you should only do if you are a developer. Otherwise it is dangerous to install outside of the FHS and the system package manager's oversight. The package should also ensure you have the correct dependencies installed (hopefully).

So I run on fedora and have been using "python setup.py bdist_rpm" and then installing the rpm.  

I do have to make this change

`diff --git a/setup.cfg b/setup.cfg
index ed0f9aa9..4b5e40f2 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,3 +1,3 @@
 [bdist_rpm]
 install_script = tools/install-rpm.sh
-requires = python3 >= 3.6 python-gobject-2 python3-mutagen
+requires = python3 >= 3.6 python3-gobject python3-mutagen`

Since python-gpbject-2 package doesn't exist in fedora32 but python3-gobject does.

**Comment by kiplingw** [comment] 2020-05-18 18:12
Agreed. The shares databases are regenerated on my system in under a minute. The main thing is that the user `config` doesn't get corrupted. But it's a plain text file and not a pickle.

**Comment by kiplingw** [comment] 2020-05-18 18:13
> So I run on fedora and have been using "python setup.py bdist_rpm" and then installing the rpm.
> 
> I do have to make this change
> 
> `diff --git a/setup.cfg b/setup.cfg
> 
> index ed0f9aa9..4b5e40f2 100644
> 
> --- a/setup.cfg
> 
> +++ b/setup.cfg
> 
> @@ -1,3 +1,3 @@
> 
> [bdist_rpm]
> 
> install_script = tools/install-rpm.sh
> 
> -requires = python3 >= 3.6 python-gobject-2 python3-mutagen
> 
> +requires = python3 >= 3.6 python3-gobject python3-mutagen`
> 
> Since python-gpbject-2 package doesn't exist in fedora32 but python3-gobject does.

Thanks @bitchkat. Could you please test and submit a separate PR for Fedora?

**Comment by emilazy** [comment] 2020-05-18 18:57
> Hey @emilazy. You're certainly welcome add it to an unstable channel for NixOS. Honestly I know very little about it.

Thanks, I've reopened https://github.com/NixOS/nixpkgs/pull/86683 targetting the unstable NixOS branch ^^

> I'm not sure how CI is performed on NixOS, but the standard we use which is suppose to be distro agnostic is DEP-8. On Debian this is implemented as `autopkgtest`. However it is that you are running the CI tests you need to ensure that they are running in a hermetically sealed container to ensure that there is nothing on your system that influenced the way the tests were performed. The best way to do this is by following the testing instructions I am about to add to the README.md shortly.

All Nix builds run in a hermetic sandbox with an environment specifying only the dependencies they requested, so the guarantees here are very strong. Honestly, though, I've never seen a non-Debian-derived distribution that implements DEP-8 (or even heard of it before Nicotine+, despite many years of dealing with Linux packaging on non-Debian distros), and I don't think any non-Debian-derived distro (Fedora, openSUSE, NixOS, ...) will be able to reuse the DEP-8 testing infrastructure as-is.

The [specification for DEP-8](https://dep-team.pages.debian.net/deps/dep8/) is currently non-existent and points people to [the documentation for `autopkgtest`](https://salsa.debian.org/ci-team/autopkgtest/raw/master/doc/README.package-tests.rst), which seems pretty Debian-specific; the tests are described in `debian/tests/control`, specify dependencies on dpkg packages, and so on. I could see it being the basis of a distro-agnostic testing specification one day, but in its current state it's both rather Debian-centric and too underspecified for another distro to be able to reasonably implement it from the documentation and reuse tests in practice. I understand that the native packaging is Debian-based and I don't at all object to the Nicotine+ upstream using DEP-8, but I think wording in the README like this is just going to confuse packagers:

> There are [different ways](https://wiki.debian.org/qa.debian.org#Other_distributions) of performing CI on different distros. The most common one is via the international [DEP-8](https://dep-team.pages.debian.net/deps/dep8/) standard as used by hundreds of different operating systems.

I'm really not sure what kind of international standard Debian Enhancement Proposals are, and I assume those hundreds of operating systems must all be Debian derivatives... :)

I investigated a bit to see whether it would be practical to use the DEP-8 testing infrastructure in the Nix package, and my conclusion that in practice, I expect only dpkg-based distributions will be able to do so. Searching around hasn't turned up any truly stand-alone implementation; there is `sadt(1)`, which ignores the dpkg dependencies and could therefore theoretically be used on another distribution, but it appears to originate from the Debian `devscripts` package which is heavily Debian-specific, pulls in heavy dependencies like `dpkg`, and might not even be packaged on all distributions.

Even with a working DEP-8 implementation, it would be impossible to use the current `debian/tests/control` in the Nix sandbox, as it attempts to run `pip3 install` which would fail due to the lack of external network access. So the package's current tests just [duplicate the tests from `debian/test/control`](https://github.com/NixOS/nixpkgs/blob/6bdf21564e74691a5e679f668f63f31f46375c58/pkgs/applications/networking/soulseek/nicotine-plus/default.nix#L56-L83), which is not ideal, but not too bad, as the bulk of the complexity is in getting the integration tests to work in the Nix sandbox to start with, and future integration tests will hopefully be integrated via the existing Robot Framework functionality.

> Yup. I'm totally fine with that. I'd also suggest submitting a PR for the README.md for instructions on how users can obtain NixOS packages for unstable and stable, like what we've done with Ubuntu.

I'll try to remember to do so once the package has received proper upstream review. I might also take a look at moving notifications over to notify2 or the native GObject libnotify bindings (as [notify2's documentation](https://notify2.readthedocs.io/en/latest/) suggests might be preferable for GTK+ apps).

**Comment by kiplingw** [comment] 2020-05-18 20:13
> All Nix builds run in a hermetic sandbox with an environment specifying only the dependencies they requested, so the guarantees here are very strong. Honestly, though, I've never seen a non-Debian-derived distribution that implements DEP-8 (or even heard of it before Nicotine+, despite many years of dealing with Linux packaging on non-Debian distros), and I don't think any non-Debian-derived distro (Fedora, openSUSE, NixOS, ...) will be able to reuse the DEP-8 testing infrastructure as-is.

I'm not sure that's entirely correct. Although DEP-8 probably has limited implementation on other distros, that's probably not due to rejection of the standard but due to lack of available resources to implement elsewhere. Keep in mind that recognition among some other distros, like Fedora are already [mindful](https://fedoraproject.org/wiki/Changes/InvokingTestsPackaged#Comparison_with_Debian.27s_autopkgtest) of its value.

> I could see it being the basis of a distro-agnostic testing specification one day, but in its current state it's both rather Debian-centric and too underspecified for another distro to be able to reasonably implement it from the documentation and reuse tests in practice. 

I don't agree with you on that. There's nothing about the standard that's Debian specific. The `autopkgtest` implementation, what you linked to, is of course Debian specific. But it's up to other distros to either re-invent their own `autopkgtest` or to simply use it.

> I understand that the native packaging is Debian-based and I don't at all object to the Nicotine+ upstream using DEP-8, but I think wording in the README like this is just going to confuse packagers:

Unfortunately we can't take a lot of responsibility for developers on non-Debian based distros. As a user, people should use whatever distro they are comfortable with. But as a developer, for the better or the worse, the development toolchain and package manager is bar none.

> I'm really not sure what kind of international standard Debian Enhancement Proposals are, and I assume those hundreds of operating systems must all be Debian derivatives... :)

Probably almost all of them are. This is probably because Debian based distros are very popular for developers. But that's not a problem for us since primary development is performed and tested on that in the case of this project.

> I investigated a bit to see whether it would be practical to use the DEP-8 testing infrastructure in the Nix package, and my conclusion that in practice, I expect only dpkg-based distributions will be able to do so.

Sorry @emilazy. There's not really much I can do for you there. The distro that you are using is adopted by a small minority of users which also uses a not very widely supported package manager. APT has been around for over twenty years with no alternatives that come near it's capabilities. In all the years that I've been working with this project, I think you are probably the only NixOS user we've ever encountered.

Having said that, we want to support as many distros as possible. But while supporting as many users is a good idea, supporting all possible development environments is not. It is fair to say that some development environments are more capable than others and I don't believe NixOS comes anywhere near the field testing and tools that a Debian based environment has.

> I'll try to remember to do so once the package has received proper upstream review. I might also take a look at moving notifications over to notify2 or the native GObject libnotify bindings (as [notify2's documentation](https://notify2.readthedocs.io/en/latest/) suggests might be preferable for GTK+ apps).

Yes thank you.

I'd also suggest for future discussions related to NixOS packaging that you create a separate issue / PR. Let's try to keep this thread concerned with @lene's code migration.

**Comment by mathiascode** [comment] 2020-05-18 21:26
Notifications are now handled by PyGObject's notify.

**Comment by mathiascode** [comment] 2020-05-20 03:25
Most issues related to the Python3/GTK3 port should be resolved now. Any Windows users here who have managed to install and test?

**Comment by zniavre** [comment] 2020-05-20 05:57
good morning, when alt+r to get room list > 

(nicotine:16934): Gtk-WARNING **: 07:53:47.807: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(nicotine:16934): Gtk-CRITICAL **: 07:53:47.807: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

then there is no scrollbar anymore in the userlist ...

(with this morning update nic+)

**Comment by zniavre** [comment] 2020-05-20 07:02
did you ever tried to keep nic+ python3 open long time ? 

in fact i believe after 45mn/1hour it deconect / reconect too often too fast so ban from server several minutes 
need to be confirmed > i see this behavior without understanding since few days

**Comment by mathiascode** [comment] 2020-05-20 22:59
Things left to investigate (that I currently know of):
- User pictures don't load
- User description encoding is incorrect
- Broken icon in the plugin list
- Alt+R userlist issue as described earlier

**Comment by zniavre** [comment] 2020-05-22 11:01
@mathiascode im not able to reproduce the alt-r issue 
maybe fixed or a bug between chair and keyboard

**Comment by mathiascode** [comment] 2020-05-30 08:22
Windows installer for testing: https://github.com/mathiascode/nicotine-plus/blob/exe/files/windows/Nicotine+-1.4.3.exe?raw=true (GeoIP missing for now, until I figure out how to install it)

**Comment by mathiascode** [comment] 2020-06-06 14:27
I'd say we're at a stage where a 2.0 release is looking pretty good. I'm probably going to wind down on patches that introduce new functionality for some time, and fix any remaining 1.4.3 regressions if found.

**Comment by kiplingw** [comment] 2020-06-06 16:32
I agree. Let's try and get #238 resolved because that will allow for more comprehensive testing in the interim between now and stable release.

**Comment by mathiascode** [comment] 2020-06-06 16:50
I'll try to get it resolved by tomorrow.

**Comment by mathiascode** [comment] 2020-06-09 21:59
New Nicotine+ 1.4.3 unstable build for Windows:
https://github.com/mathiascode/nicotine-plus/blob/bf17c7fb384e04fbf4bf2670352b238a826e3eb7/files/windows/Nicotine+-1.4.3-x86_64.exe?raw=true

**Closed** 2020-06-12 23:19 UTC
