### ISSUE TITLE
Log windows scroll back to begin after any new entry.

### ISSUE THREAD

**Issue by mtem** [Nicotine-Plus/nicotine-plus#926] opened 2021-01-03 10:09 UTC
Nicotine+ version:  2.3.0-dev1
Operating System/Distribution: Windows 10

### Expected behavior
Stay at the current position.

**Comment by mathiascode** [comment] 2021-01-08 09:51
I can't reproduce this issue. If I'm positioned at the bottom of the log window, it scrolls to the bottom when new entries are added. If I've scrolled up, the log window stays at the current position when updated.

Perhaps I've misunderstood something?

**Comment by mtem** [comment] 2021-01-09 12:42
on every new entry i see this error:
Gtk-CRITICAL **: 13:38:00.554: gtk_adjustment_get_page_size: assertion 'GTK_IS_ADJUSTMENT (adjustment)' failed

**Comment by mtem** [comment] 2021-01-09 14:27
Solved: latest mingw64 glib2 version 2.66.4 is the culprit

**Comment by mathiascode** [comment] 2021-01-09 19:36
Closing as there's nothing to do on our side.

**Closed by mathiascode** 2021-01-09 19:36 UTC
Labels: bug
