### ISSUE TITLE
(Bug) 3.2.0 dev Arch Linux Error loading plugin libhunspell and libaspell

### ISSUE THREAD

**Issue by francisuk1989** [nicotine-plus/nicotine-plus#1548] opened 2021-09-06 05:56 UTC
Nicotine+ version:  3.2.0 dev GTK 3.24.30
Operating System/Distribution: Arch Linux 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

### Describe the bug
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.578: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.581: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.582: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.591: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.607: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.698: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.698: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.699: Error loading plugin: libhunspell-1.7.so.0: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.699: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory
** (org.nicotine_plus.Nicotine:1388): WARNING **: 01:36:22.699: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

``
### Steps to reproduce the bug
git clone https://github.com/nicotine-plus/nicotine-plus
cd nicotine-plus
./nicotine

### Additional context
I have not enabled Spell checker
I have also ticked and unticked also

**Comment by mathiascode** [comment] 2021-09-06 21:57
Does this happen on every run? I know this happens on Arch whenever the GSpell dependency is loaded, but this shouldn't happen anymore after spell check has been disabled and Nicotine+ has restarted.

**Comment by francisuk1989** [comment] 2021-09-07 00:16
> Does this happen on every run? I know this happens on Arch whenever the GSpell dependency is loaded (harmless warning), but this shouldn't happen anymore after spell check has been disabled and Nicotine+ has restarted.

> Does this happen on every run?
Yes but only once.

> shouldn't happen anymore after spell check has been disabled and Nicotine+ has restarted
Only when im running /.nicotine in terminal, Dosnt affect 3.1.1

**Comment by mathiascode** [comment] 2021-09-08 18:52
Closing, since this is not caused by Nicotine+.

**Closed by mathiascode** 2021-09-08 18:52 UTC
Labels: bug
