### ISSUE TITLE
Network share issue

### ISSUE THREAD

**Issue by h0ek** [Nicotine-Plus/nicotine-plus#559] opened 2020-08-16 08:57 UTC
Nicotine+ version: 2.0.1
Operating System/Distribution: Windows 10

### Describe the bug
I have a music on my network drive mapped to PC. I added this folder but still shows nothing in app.
I removed it, added again and hit rebuild button.
Got message:  615 directories found after rescan/rebuild
But nothing is added.

### Expected behavior
Share some files from network drive like it was in version 1.4

**Comment by h0ek** [comment] 2020-08-16 11:05
Update!

Looks like blue bar at the bottom is progress bar for update for shared folder.

So everything work fine but in my opinion this is misleading. There should be info next to progress bar that files are being added  eg. 1987 of 6907 files added etc. or some comment in console that process started.
In old version there was such  a information.

Please change label bug to Feature request

**Comment by hboetes** [comment] 2020-08-17 08:47
@h0ek 
The scanning behaviour has improved a lot since 2.0.1.
The new 2.1.0 will be released one of these days,  please update it as soon as it's released and check if the problem is gone.

**Comment by h0ek** [comment] 2020-08-17 09:11
Awesome! Will do.

**Closed** 2020-08-19 16:02 UTC
Labels: bug
