### ISSUE TITLE
Automatically reconnect to a server after connection failure

### ISSUE THREAD

**Issue by Gojkira** [nicotine-plus/nicotine-plus#2168] opened 2022-09-01 13:42 UTC
As things currently work when the user disconnects from a server (eg. VPN disconnects), the user will need to manually reconnect by either clicking on the tray icon or loading up the GUI. It would be preferable if this reconnection process was automatic, similar to how qBittorrent functions.

**Comment by alekksander** [comment] 2022-09-16 13:37
in other words this is a request to auto–reconnect on connection refuse upon certain amount of time? if so vpn has nothing to do with it and You can rename Your Issue correspondingly.

**Comment by mathiascode** [comment] 2022-09-16 14:58
What OS are you using? This seems like a bug, since Nicotine+ should already try to auto-reconnect if the connection to the server breaks.

**Comment by slook** [comment] 2022-09-16 21:04
Currently if the local network is down then it appears to be handled in the same way as if the remote server went down, whereby the retry timeout grows exponentially up to as much as 10 minute intervals:

https://github.com/nicotine-plus/nicotine-plus/blob/02c1fcb8bbed8ac91e35bd210776f6c9fea424b7/pynicotine/slskproto.py#L416-L417

I suppose that long interval is done to avoid pestering the server, but this method is overly conservative if we are waiting for our local network interface to come up, whereupon it would be better for us to catch some sort of signal from the system so we can attempt instantaneous re-connection, rather than waiting for 10 minutes between each retry.

**Comment by mathiascode** [comment] 2022-12-15 12:33
On my system, Nicotine+ disconnects from the server if there are no attempts to send messages to the server between the time the network interface went down, and the server socket keepalive reaches the timeout limit. If there are any outgoing messages to the server in the queue, e.g. requesting the IP address of a user, Nicotine+ is stuck.

@slook This should also be reproducible without a VPN, if you simply disable your network connection. Could you verify if the issue happens on your system?

**Comment by mathiascode** [comment] 2022-12-15 12:58
Seems like it's indeed a thing: https://stackoverflow.com/questions/7768894/so-keepalive-does-not-work-during-a-call-to-write

**Comment by mathiascode** [comment] 2022-12-15 14:24
Current situation after https://github.com/nicotine-plus/nicotine-plus/commit/c492027027e57d1ec3b30e1c24e92b57ff2d9673 was committed:

**Linux**
- When waiting for read, server connection times out after 30 seconds
- When waiting for write, server connection times out after 30 seconds (since https://github.com/nicotine-plus/nicotine-plus/commit/a96e7eb88c5e686634c489ea7c3299476ed922cf)

**Windows**
- When waiting for read, server connection times out after 30 seconds
- When waiting for write, server connection times out after 21 seconds (some Windows default)

TODO: verify what macOS and the various BSDs currently do

**Comment by mathiascode** [comment] 2022-12-15 18:17
Based on the results above, this issue should be resolved.

@Gojkira Could you confirm if the issue is solved on your end? Development builds of Nicotine+ are available here: https://nicotine-plus.org/doc/TESTING.html

**Closed by mathiascode** 2022-12-15 18:17 UTC
Labels: bug

**Comment by slook** [comment] 2023-01-07 00:27
@Gojkira The bug fix is now included in Nicotine+ 3.2.8 released on January 6th 2023 https://nicotine-plus.org/doc/DOWNLOADS
