### ISSUE TITLE
Local file error (I/O error: cannot fit 'int' into an offset-sized integer)

### ISSUE THREAD

**Issue by architux** [nicotine-plus/nicotine-plus#1985] opened 2022-04-15 08:38 UTC
Nicotine+ version: 3.2.2 (GTK 3.24.5).
Operating System/Distribution: Raspbian GNU/Linux 10 (buster) (armv7l).

### Describe the bug

I've started to get strange error messages some time ago, maybe after the latest Nicotine+ upgrade to the aforementioned version.

Some files can not be uploaded with the "Local file error" message in "Status" column of "Uploads" tab. At the same time a couple of error items appear in the log history: "I/O error: cannot fit 'int' into an offset-sized integer". I guess those error messages seem to be related one with another.

As I click the "Retry" option from the context menu for the specific uploading file, it disappears from the uploading queue.

The only feature to narrow the scope of the issue that I may provide is the following. Those files that I've seen this issue about have a pretty large size (the latest file with this error has more than 3 Gb of file size).

### Expected behavior

I guess there should be no such errors, no matter the size of any certain file being uploaded.

### Steps to reproduce the bug

I'm not sure about the exact steps to reproduce such an issue, but it occurres from time to time with some particular files.

### Additional context

I'm not sure how to provide some additional technical data for further investigation, so I'd be glad to add some additional feedback, in case it's possible.

**Comment by mathiascode** [comment] 2022-04-15 09:35
Do you have usernames of some users that cause this issue? What seems to be happening is that some (presumably) old Soulseek client without proper support for large >2 GB files asks to resume a download, and sends an invalid file byte offset in the range 9223372036854775808 to 18446744073709551615 (possibly a negative integer originally that wraps around on our end).

**Comment by slook** [comment] 2022-04-15 09:35
Thank you for your bug report @architux this is already excellent information. As you have observed the Soulseek protocol is not optimized for large files and there is a known server limitation with files > 2GB not reporting the correct bytes done/remaining, for which a less than ideal workaround is currently in-place and was recently re-worked, this may or may not be related.

> some particular files ... how to provide some additional technical data

Please email @mathiascode (the address on his Github profile) with your Soulseek username and some slsk:// links (or link(s) to other cloud storage etc) to the problematic files in your shares that seem to reproduce this error, this would help with investigations.

We appreciate your willingness to help with this, since testing of large transfers is something that is becoming more relevant nowadays.

**Comment by slook** [comment] 2022-04-15 09:43
> usernames of some users

Please avoid publicly posting private user data on here, use @mathiascode email address instead @architux some slsk:// links to the problemaitc files in your shares would be very useful thanks :)

**Comment by architux** [comment] 2022-04-15 10:19
@mathiascode @slook OK, thank for for your replies and considerations.
I have sent the additional data to Mathias email address.

**Comment by mathiascode** [comment] 2022-04-15 13:06
The problematic client is Soulseek NS. If more than 2 GB of a file has been downloaded, and the download aborts/pauses and later continues, Soulseek NS fails to read the size of the incomplete file. It then sends an invalid file offset of `-1`.

There's nothing we can do on our end, except improve the error message. If we ignore the offset and start sending data from the beginning of the file, the user ends up with a corrupted file.

There are two options for Soulseek NS users that want to download >2 GB files:

- Download the whole file in one go, never pause the download or disconnect once it passes 2 GB
- Switch to a modern Soulseek client that properly supports large files (Soulseek Qt, Nicotine+, slskd, Seeker)

**Comment by architux** [comment] 2022-04-15 15:23
@mathiascode Thank you for that detailed info.

I will send a message to that user asking about the details, how one tried to obtain that big file from my share. Would you please clarify does this behavior depends on some versions of Soulseek NS, or is it a client-bound problem?

And, yes, the clearer error message would be useful too in this particular case. Anyway, I will add a kind of a disclaimer message both into my user info text block and also into the private chat message of "Leech Detector" plugin, to inform other users about the possible problems.

**Comment by architux** [comment] 2022-04-15 15:25
By the way, I'm not familiar with Soulseek protocol itself yet, but is there a chance for a local client uploading some data to get the downloading client's specification? 💡 So then a separate dedicated plugin may be written to send a PM in case some downloading user has such a problematic client on one's side. It may also cover another problems that you may be familiar with, to send a proper feedback to any downloader just in time.

**Comment by mathiascode** [comment] 2022-04-15 15:47
> Would you please clarify does this behavior depends on some versions of Soulseek NS, or is it a client-bound problem?

Affects any Soulseek NS version, the client was last updated in 2009 and generally can't handle values past the int32 limit. The few times it does is by chance.

> And another question is what the downloading user sees in such particular error within the Soulseek NS client, what kind of error message, is it the same as on the uploader's side?

They see a `Failed` message, and the total size displayed in the GUI is usually screwed up for these downloads.

![](https://user-images.githubusercontent.com/8754153/163591461-2889c1f2-25b8-49bb-8e50-0cc7e591347d.png)

> By the way, I'm not familiar with Soulseek protocol itself yet, but is there a chance for a local client uploading some data to get the downloading client's specification?

There's no reliable way to do so, unfortunately.

**Comment by architux** [comment] 2022-04-15 15:53
OK, so I'll just prepare those messages informing about a possible error for this particular outdated client.

Are there any other similar/related issues with older/incompatible clients that downloaders/uploaders may stumble upon? I've seen another error on my side, far more frequently, saying "Can not connect", and, again, I'm not sure what's the actual problem and on which side it happens. I was thinking about raising a separate request for this one.

**Comment by slook** [comment] 2022-04-15 16:03
Indeed there are various specific quirks that give clues that can help to discover what is the remote client, but unfortunately the protocol does not have a specific identification message. Writing a plugin to serve this purpose would involve highly complex and invasive data gathering along with all the strange logic to capture those quirks and specific error conditions, it's simply not practical to do so.

You can discover what version of Nicotine+ a remote user is running by sending the `/ctcpversion` command via private chat, but this function is exclusive to Nicotine+ only.

> clearer error message would be useful too

It might be useful to simply include the human readable `current_bytes` and `total_size` values appended to end of all transfer error messages? Maybe the token and/or filename might be useful too.

**Comment by mathiascode** [comment] 2022-04-15 16:25
> I've seen another error on my side, far more frequently, saying "Cannot connect", and, again, I'm not sure what's the actual problem and on which side it happens.

It happens when the connection (attempt) times out. A few of these cases were fixed in Nicotine+ 3.2.2, especially for larger files. If you still see these errors, could you enable debug logging (right-click the log pane -> log categories -> enable 'transfers', 'connections' and 'messages'), and send the logs to my email?

Keep in mind that debug logging is verbose and slow, so don't keep it enabled permanently.

**Comment by slook** [comment] 2022-04-15 17:19
> the "Local file error" message in "Status" column

Although the error is thrown locally, it could be worth catching this `-1` case because really this is a "Remote file error"

**Comment by architux** [comment] 2022-04-15 20:11
@mathiascode OK, I will set the debugging level for a brief period of time to get some logging data.

@slook Basically I think that the current error message itself is somehow confusing, in this particular case too. "Local file error" makes you (me, at least, in the first place) speculating about some local file errors literally, i.e. some hard drive problems, file inconsistency, etc. But, actually, it's not. So maybe this error message itself might be refactored to be more straight-to-the-point indication of the possible problem(s). But that's just a matter of terminology guidelines anyway. 🙂

**Comment by slook** [comment] 2022-04-16 08:57
The current `msg.error` message is a raw string that the Python interpreter spits out (afaik), it is normally useful since any sort of error may be thrown by the OS, it is usually something helpful like "out of disk space" or "file not found" etc:

https://github.com/nicotine-plus/nicotine-plus/blob/8a2496ebfef7dbdabc59b4eeec87e59b2ec2bc9a/pynicotine/transfers.py#L972-L974

In this case the official legacy client is non-compliant with the protocol, which makes us consider it to be a "Remote file error", but we are only supposed to set this if the remote client refused us the transfer due to a problem on that end, but of course this doesn't happen since the remote client is oblivious to the issue! There is no mechanism for us to report a remote issue, because the clients are supposed to fend for themselves.

There is a "Too many megabytes" status/reason, but this is usually for the purpose of the queue limiter, so if we send this reason to the peer then the remote user would assume that you disallowed transfers over the size set in your upload preferences, then it might keep retrying to check or do something else weird, because the legacy clients can be pretty dumb sometimes!

**Comment by architux** [comment] 2022-04-16 21:20
@slook OK, I see. So maybe there's no need/no room for some source code clarifications then.

I believe such typical error cases should be listed somewhere on the official Nicotine+ website, in case there's no such section there yet, for users to be able to browse it for some errors that they might face with working with the client for some period of time.

**Comment by slook** [comment] 2022-04-17 21:48
Most of the typical errors raised are self-explanatory, and do not require an external reference for the user to understand what is happening whilst using the application. When raw cryptic messages are shown when the error is not handled, then this indicates something unexpected is going on that requires attention, or as in this case, something which is beyond our control.

In this case, the message is unique enough to identify this edge case, and the explanation/solutions above (https://github.com/nicotine-plus/nicotine-plus/issues/1985#issuecomment-1100097476) can now be found thanks to the title of this issue.

**Comment by mathiascode** [comment] 2022-04-17 22:07
It would be a good idea to add common transfer status messages to the Soulseek protocol documentation.

**Comment by slook** [comment] 2022-05-30 09:30
> add common transfer status messages to the Soulseek protocol documentation.

Done. The table added in the protocol documentation might be expanded in the future.

> typical error cases should be listed somewhere on the official Nicotine+ website

We would like to avoid the need for external references wherever possible. Perhaps ToolTips within the interface could help to clarify the meanings of the different transfer statuses, which could be done in future based on the developer documentation.

For now there is no further action required given this error is not caused within Nicotine+ and the problem as already handled as best as possible (by allowing the transfer to continue unless it is paused by a user). The linked PR and this issue can be closed.

**Closed** 2022-05-31 19:51 UTC
Labels: bug
