### ISSUE TITLE
New User Cannot Load Up Shared Files list

### ISSUE THREAD

**Issue by MannyK2018** [nicotine-plus/nicotine-plus#2240] opened 2022-11-02 02:19 UTC
Nicotine+ version:  
Operating System/Distribution:

### Describe the bug

I recently downloaded Nicotine Plus because of issues I was having with Soulseek. However when I went to configure my shares it did not upload the details of the files I left it scanning for over an hour and yet still nothing. Just the report that the users filelist is empty In the interim I added some files to my share area and reloaded my share in  Soulseek and whilst a little slower than previously (presumambly because I am running Nicotine Plus too), it uploaded the revised share list in a matter of minutes.  I can only assume its not working

I am able to see other users shares

### Expected behavior

I would expect to upload my share list in a similar manner and timescale to SoulSeek

### Steps to reproduce the bug

Open Nicotine Plus Add filepath to shares in settings. Applied the share and pressed OK window closed and then waited. Then went to users entered my login name and requested to browse my shares (I have over 125,000 currently of SoulSeek). Nicotine plus reported I did not have any shares. Waited 10 minutes repeated request to view shares. reported no files shared and did so every time I tried.  the scanning shares graphic at the bottom of the screen was active and coloured blue

### Additional context
Screenshots, logs, stacktraces or relevant information.
Running Windows 10 64 bit. First time user. Still finding my way around but assume the share utility is functionally similar to that of SoulSeek.

**Comment by slook** [comment] 2022-11-02 07:13
> Nicotine+ version:

Please specify ^

Until we figure this out, try configuring a small test folder with a handful of files to verify that anything is working at all?

There might be some scanner error messages in "Debug Miscellaneous" log catagory in:

- View > Show Log History Pane > Right-click > Log Catagories > "[Debug] Miscellaneous"
- Then do "Rescan Shares" again and see if there are any errors or not, post here if anything shows up.

> assume the share utility is functionally similar to that of SoulSeek

Nicotine+'s share indexing system is simpler than SoulseekQt's, however many users do report that shares scanning in N+ is usually faster.

**Comment by mathiascode** [comment] 2022-11-16 16:50
Any update on this issue?

**Comment by slook** [comment] 2022-12-02 02:37
After a first run experience like that it is no surprise that the user gave up.

The issue is severe enough for this bug to remain open until the problem can be isolated, even though we don't have enough information to replicate it.

**Comment by slook** [comment] 2022-12-06 18:00
Agreed closing cannot replicate not enough information.

**Closed by slook** 2022-12-06 18:00 UTC
Labels: bug, invalid
