### ISSUE TITLE
Settings are reset to application defaults when a system crash occurs

### ISSUE THREAD

**Issue by derscott** [nicotine-plus/nicotine-plus#2147] opened 2022-08-09 17:58 UTC
Nicotine+ version:  3.2.4  •  GTK 3.24.20
Operating System/Distribution: Linux Mint 20.2

### Describe the bug
After performing a search, my computer freezes. My mouse cursor does not respond to mouse movement anymore as well as caps and num lock don't respond to being pressed. In that state, the only thing I can do is restart my computer.

### Expected behavior
A list of search results appears and the application and operating system continue to operate normally.

### Steps to reproduce the bug
1. I go to file search tab
2. I enter a search term and press enter
3. The search result list appears
4. Some moments later, my whole computer freezes. And the only thing I can do is restart my computer.

### Additional context
I even tried to reduce the search results from the default 1500 to 100, but it didn't help either. Also remarkable is the fact that after rebooting and starting Nicotine+ again, the onboarding dialog appears. Somehow Nicotine+ is not able to remember my login after that kind of crash. Settings also seem to be reset to application defaults every time such a crash occurs.

**Comment by slook** [comment] 2022-08-09 18:13
This sounds like a duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2128, what is your kernel version?

> Settings also seem to be reset to application defaults every time such a crash occurs

That is very unlucky, there has been another report of similar recently and also on Windows the config is lost after a force shutdown. Maybe there is something that could be done to prevent data loss from occurring, or at least to make it possible to recover. It is noteworthy that the config.old file is not useful because it is immediately overwritten after the application is started.

**Comment by mathiascode** [comment] 2022-08-09 18:38
> Somehow Nicotine+ is not able to remember my login after that kind of crash. Settings also seem to be reset to application defaults every time such a crash occurs.

Can you back up `~/.config/nicotine` before performing a search, and after the system has crashed? Are both the `config` and `config.old` blank after restarting?

**Comment by derscott** [comment] 2022-08-09 21:36
> This sounds like a duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2128#issuecomment-1198549508, what is your kernel version?

It's `5.4.0-122-generic`

> Can you back up ~/.config/nicotine before performing a search, and after the system has crashed? Are both the config and config.old files blank after restarting?

`~/.config` contains two files, `config` and `config.old`. I've backed them up before and after crash, and I have the current one while Nicotine is freshly started after the reboot. Comparing these files using Meld gave me these results:

* Before the crash both files are identical, human readable with UTF-8 encoding. File size is 6 KiB.
* After the crash both files are **not** identical, and the encoding seems to be broken. File size is also 6 KiB of both files.
* Currently (after restarting Nicotine) both files are identical again, they are human readable with UTF-8 encoding. File size has shrinked to 5.1 KiB.

**Comment by slook** [comment] 2022-08-09 22:33
> It's 5.4.0-122-generic

Apparently there is some bug in the tcp stack of the -122 kernel that is encountered by several applications including Nicotine+, there is no way for us to work around it.

It is confirmed you can avoid the crash by downgrading the kernel to -121 or using -123 from the Ubuntu proposed repo (which is due for release to the Ubuntu stable repo any day now).

> the encoding seems to be broken

What is it about the config file contents or attributes that has led you to this conclusion?

**Comment by derscott** [comment] 2022-08-10 21:18
> What is it about the config file contents or attributes that has led you to this conclusion?

There was nothing but glyphs to see in Meld when I compared the files backuped *after the crash*. Also, it gave a message that there were many differences between these files and asked if I would really like to go on analyzing them. According to Meld, both files have different encodings:
* `config`: *ISO-8859-15*
* `config.old`: UTF-8

**Comment by slook** [comment] 2022-08-11 01:01
The kernel containing a fix for the crashing issue should now be available https://github.com/nicotine-plus/nicotine-plus/issues/2128#issuecomment-1210694082 (perhaps it might take a while for Mint to get the update from upstream Ubuntu).

Since we still want to investigate the corrupted config file problem (and I have heard a report of losing config data after a power failure), it would seem to be a good idea to change this issue title to something like: "Settings are reset to application defaults when a system crash occurs".

**Comment by derscott** [comment] 2022-08-11 17:54
> The kernel containing a fix for the crashing issue should now be available

Installed it today and everything is working fine again. Thanks everybody :)

**Comment by mathiascode** [comment] 2022-08-11 18:38
Here's a corrupted config from my Windows test system, as a result of hard restarting the machine immediately after Nicotine+ wrote to the config.

Perhaps it's not flushing the file write fast enough?

[config.txt](https://github.com/nicotine-plus/nicotine-plus/files/9311233/config.txt)

**Comment by slook** [comment] 2022-08-11 18:44
Yes I suspect Windows's delayed write caching is getting in the way. Maybe there is some method to override the OS's default write caching features, since for a small file like config there probably isn't much performance benefit either way.

**Closed** 2022-08-11 19:47 UTC
Labels: bug

**Comment by mathiascode** [comment] 2022-08-11 19:51
Confirmed fixed on my Windows test machine.
