### ISSUE TITLE
all people don't see my private files

### ISSUE THREAD

**Issue by arbdlp** [nicotine-plus/nicotine-plus#1595] opened 2021-10-04 23:39 UTC
Hello.
When I want to block certain folders to several friends, I would like those blocked folders to be visible to everyone (in case someone wanted something), but by making them private they disappear from the search results.
Is that something normal?
Is it possible for everyone to see my free and private folders?
Thanks.

**Comment by slook** [comment] 2021-10-05 00:26
> Is that something normal?

Yes this is normal, only users in your Buddy List can download your private files.

> Is it possible for everyone to see my free and private folders?

Even if you mark a share as 'Buddy Only', then it is still possible for others to see the files listed, but they wont be able to download them, they are marked as [PRIVATE FILE] (there is an option in Preferences which enables the listing of them, which makes them appear in the results greyed-out).

The Soulseek network isn't intended to be a secure method of file transfer. If you share something, then this implies you want everybody else to have it, especially users in your Buddy List, who can get extra files from you if you have setup a Buddy Share(s).

- I would suggest the best solution for you is to run another instance of Nicotine+ on an extra machine with a separate Soulseek Username. You could use either another physical computer or a Virtual Machine (on some OS's that support multi user switching it is possible to run Nicotine+ under a different OS login, but this isn't recommended). Obviously you would then have a totally separate set of Public Shares and Buddy Shares, so this would give you the separation that you want.

If you are really concerned about privacy then you could run one of your machines internet connections through a VPN, proxy, mobile hotspot, etc. This way, your friends won't be able to discover your other account(s) because your IP address will be different.

Hopefully that answers your query?

**Comment by mathiascode** [comment] 2021-10-05 02:45
Privately shared/locked files from other SoulseekQt clients can be displayed (they have the [PRIVATE FILE] prefix), but showing your own private files to everyone isn't currently possible in Nicotine+. Due to widespread abuse of this feature, and several complaints across the internet, it's not high priority for me.

**Comment by arbdlp** [comment] 2021-10-05 19:18
well, the problem is that if I open the entire library, most users abuse a lot (I have a 4TB library of music)
I am in favor of everyone being able to download (as long as they also share), but downloading a 500GB folder directly and not even thanking you ... of course, since it damages the health of my hard drive and overloads the machine.

Normally my most important folders I block them, and the user who asks me for something I give him permissions, if there was some way to limit the abusers I would have the whole library open.

**Comment by 82d** [comment] 2021-10-31 14:47
I think it needs to be done. this is not enough, just as it was once not enough to see the hidden files of other users. I think that you need to do this, but add a parameter to hide them at will. this will be better for many users and even less reason to look in the direction of SoulseekQT. in fact, Nicotin+ has almost no disadvantages over SoulseekQT, but this is clearly not enough for me.

**Comment by slook** [comment] 2021-11-01 00:41
I often hear that something needs to be done, but unfortunately my understanding of the problem is lacking because I am not personally bothered by these sorts of issues.

Of the many ideas suggested on various forums, none seem like they would be truly satisfactory. In the long term I think it will require a range of features to be implemented, which will be difficult whilst avoiding excessive complexity.

**Comment by mathiascode** [comment] 2022-02-06 15:14
Closing in favor of #1870

**Closed by mathiascode** 2022-02-06 15:14 UTC
