### ISSUE TITLE
Adding files to download in pause

### ISSUE THREAD

**Issue by pastrank** [nicotine-plus/nicotine-plus#2122] opened 2022-07-10 08:57 UTC
### Adding many files
At least in my case, there are many times where I find an user that's got a complete discography of an artist and many files to download from him. For example, he can have 25 albums, 15 bootlegs and 30 eps, But I don't need to download all: I'm just interested in 4 or 5 discs and relative covers. 
Now, I can get the stuff directory by directory, but if he use a structure like _genre/artist/album/coverart_ it's a pain to retrieve the names at the end, expecially if not properly tagged. On the other hand, if I put all in download and then pause and delete unnecessary stuff, I fill his Soulseek or Nicotine with lots of file names.
The solution, in my opinion, could be to have the power to add downloads directly in pause.

**Comment by slook** [comment] 2022-07-10 09:45
Duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/1717. Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1659.

**Closed by slook** 2022-07-10 09:45 UTC
Labels: duplicate, enhancement
