### ISSUE TITLE
OS error: [Errno 13] Permission denied: '/Users/USER

### ISSUE THREAD

**Issue by dosch** [nicotine-plus/nicotine-plus#2001] opened 2022-04-26 08:03 UTC
Nicotine+ version:  3.3.0.dev1  •  GTK 4.6.2
Operating System/Distribution: MacOS Monterey - 12.3.1 (21E258)

### Describe the bug
Local files and folders can't be accessed. 
Log:  `OS error: [Errno 13] Permission denied: '/Users/USER`

### Expected behavior
Local files can be accessed

### Steps to reproduce the bug
Download Nicotine+ and use it.

### Additional context
probably linked to restricted file permissions required by the OS. 
I granted full disk access to Nicotine+ in the privacy and security preferences pane. 
This did not help...

**Comment by mathiascode** [comment] 2022-04-26 14:38
Is this issue exclusive to the unstable version of Nicotine+?

**Comment by dosch** [comment] 2022-04-27 05:54
no stable has the same issue

**Comment by dosch** [comment] 2022-05-16 13:26
setting a actually existing 'incomplete download' folder solved that issue.

Next issue: nicotine can't seem to move the files to the complete downloaded folder after downloading is complete...

**Comment by dosch** [comment] 2022-05-16 17:05
> Any error messages in the log?

19:03:12 Couldn't move '/Users/USER/Nicotine/Incomplete Downloads/INCOMPLETE0818866b33e47bf932d0f42ef896e5d414SONGNAME.mp3.bak' to '/Users/USER/Soulseek Downloads/complete/ALBUM/SONGNAME.mp3.bak': [Errno 13] Permission denied: '/Users/USER'

> The config file is located in `~/.config/nicotine/`, other data files such as the list of downloads and logs are located in `~/.local/share/nicotine/`.

Interesting that MacOS spotlight can't find these files. Even with 'show invisible files' and 'show system files' enabled...

**Comment by mathiascode** [comment] 2022-05-16 21:47
Could you check the permissions of the `Soulseek Downloads` folder and any subfolders, and perhaps try downloading an album to another folder somewhere else? `Soulseek Downloads/complete` looks like the folder structure SoulseekQt creates, perhaps it's something related to the way these folders were created by SoulseekQt, assuming you're using it? I don't think there's any issue in Nicotine+ here.

**Comment by slook** [comment] 2022-05-26 19:41
@dosch Did you resolve or work around your issue? If so how? Let us know if you need further help or not. Thanks.

**Comment by slook** [comment] 2022-05-30 09:34
Closing since nobody else seems to be experiencing any similar issue, it must have been something to do with @dosch's local environment, perhaps related to file permissions. Please re-open the issue if you still require assistance.

**Comment by dosch** [comment] 2022-05-30 09:36
> @dosch Did you resolve or work around your issue? If so how? Let us know if you need further help or not. Thanks.

sorry, did not have time for proper checking and re-checking. Will do so later and indeed, if anything is found, I will re-open the issue. Thnx for your patience.

**Comment by EgonHeuson** [comment] 2022-08-02 07:28
Same issue for me here. I gave a complete access to disk in the Preference System security panel, but it didn't help...

**Comment by slook** [comment] 2022-08-02 11:06
I don't know exactly what is needed to fix the problem as it was never properly investigated. It might be to do with the "Owner" of the offending folder object, maybe manually creating a different new folder for the Incomplete Downloads folder could help.

It would be great to identify what circumstances lead to this state in the first place, such that we can help other macOS users from encountering this same error in the future.

**Comment by EgonHeuson** [comment] 2022-08-02 11:15
In my case, it seems that it is the config folder that is not written. Therefore, when I restart the App, I have to reconfigure everything again. Annoying... By the way I have custom folders for downloads and music share.

**Comment by slook** [comment] 2022-08-02 11:26
Well it is more than annoying since it prevents you from running the application.

To work around around the issue you can use the `--config` and/or `--user-data` command line options to specify a custom location for the config file and program settings folder.

Please specify the path where the config folder is supposed to be, if you need to find out for us which location Nicotine+ wants to use by default, you can enable the "[Debug] Miscellaneous" in View > Log History Pane > Right Click > Log Categories, then open and OK the Preferences dialog you should see a log line such as "[Misc] Saved configuration: /home/user..." or perhaps an error that contains the inaccessible path name.

**Comment by EgonHeuson** [comment] 2022-08-02 11:51
Here are the logs that concern this issue):
`13:48:20 Impossible de créer le répertoire « /Users/egonheuson/.config/nicotine », l'erreur est  : [Errno 13] Permission denied: '/Users/egonheuson/.config/nicotine'
13:48:20 Un problème est survenu lors de la lecture du fichier /Users/egonheuson/.config/nicotine/config : [Errno 2] No such file or directory: '/Users/egonheuson/.config/nicotine/config'`
I use the GUI app for MacOS so i'm not sure I can use command lines to configure it.

Does this help?

**Comment by slook** [comment] 2022-08-02 11:59
Thanks yes that is helpful.

> I use the GUI app for MacOS so i'm not sure I can use command lines to configure it.

Instead of using the desktop launcher, you can open Terminal in macOS and the command for running the application is `nicotine` so for example you could enter a command to launch the program such as:

`nicotine --user-data /Users/egonheuson/Documents/nicotine --config /Users/egonheuson/Documents/nicotine/config`

**Comment by mathiascode** [comment] 2022-08-02 12:06
> If the path returned by the environment is not writable, then we should fall back to `legacy_dir` @mathiascode

No, the legacy dir should not be used anymore. The root cause should be fixed instead.

Before attempting to set a custom config dir, are you able to manually create files in /Users/egonheuson/.config/nicotine? Are you able to remove the folder?

**Comment by slook** [comment] 2022-08-18 17:34
@EgonHeuson Are you able to help us investigate the issue further? If so please test on your system:

- are you able to manually create files in /Users/egonheuson/.config/nicotine?
- Are you able to manually remove the folder without granting elevated permissions?

**Comment by tatiee** [comment] 2022-08-19 20:28
This just started happening to me as well running on elementary OS 5.1.7 Hera

Couldn't move '/home/tev/.nicotine/incompletefiles/INCOMPLETE393b1419c79336169ea1ee090a5835ea01 Introduzione.mp3' to '/media/tev/evo/Users/tevin/Music/01 Introduzione.mp3': [Errno 30] Read-only file system: b'/media/tev/evo/Users/tevin/Music/01 Introduzione.mp3'

Didn't have this problem before - and i can add files to the .config

**Comment by slook** [comment] 2022-08-19 21:37
@tatiee your error does not seem to be related to the issue being discussed here.

**Comment by mathiascode** [comment] 2022-08-19 21:49
> [Errno 30] Read-only file system

I suppose you're storing finished downloads on some removable drive? Maybe there's a temporary issue with it that requires unplugging or restarting. Are you able to create/move files on it outside of Nicotine+?

**Comment by EgonHeuson** [comment] 2022-08-19 22:39
Hey! Sorry! I had no time yet. I’ll have a look as soon as I can :-)

**Comment by tatiee** [comment] 2022-08-20 15:13
> 

Yeah this is a separate issue. Sorry guys - I'll look into why my SSD is suddenly "read-only"... frustrating.

**Comment by slook** [comment] 2022-08-20 15:49
> Preferences doesn't allow me to change the settings regarding incomplete/DL folders

That is a known issue in 3.2.3, make sure you are running Nicotine+ 3.2.4

**Comment by slook** [comment] 2022-09-04 22:01
@tatiee @EgonHeuson @dosch Please try the latest stable version of Nicotine+ 3.2.5 and report back as to if the configuration issue still exists on your machines. Thanks.

**Comment by EgonHeuson** [comment] 2022-09-05 06:52
I’ll do this today :-)

**Comment by EgonHeuson** [comment] 2022-09-05 21:57
The config is still reseted at each app reboot on the 3.2.5 😰 Sorry 😓

**Comment by slook** [comment] 2022-09-05 22:17
Thank you @EgonHeuson Are you able to help us investigate the issue further? If so please test on your system:

1. Is it allowed for you to manually create files in `/Users/egonheuson/.config/nicotine`?
2. Are you able to manually remove the folder without granting elevated permissions?
3. Does deleting the `.config/nicotine` folder resolve the problem, or is it still reset to default each time?

**Comment by EgonHeuson** [comment] 2022-09-05 22:28
@slook "Is it allowed for you to manually create files in /Users/egonheuson/.config/nicotine?" you mean like manually create a new file in this folder?
The /Users/egonheuson/.config/nicotine folder doesn't exist but if I create it and authenticate, no problem I can create folders and files
<img width="501" alt="2022-09-06_00-24-59" src="https://user-images.githubusercontent.com/32910291/188517336-7b75e80f-3231-4605-ae72-ccb49dd73ebc.png">

<img width="568" alt="2022-09-06_00-25-25" src="https://user-images.githubusercontent.com/32910291/188517344-c3c86e2d-5465-4d96-aaf9-f94363048777.png">

Once created (and being sudo I guess), I can remove folders from /Users/egonheuson/.config/nicotine without problem.
But I guess the main problem is that the folder doesn't get created by default.

**Comment by EgonHeuson** [comment] 2022-09-05 22:31
Here are the logs when opening the app (I can translate them fro you if needed): 
```
2022-09-06 00:28:38 Chargement de GTK 3.24.34
2022-09-06 00:28:38 Chargement de Python 3.9.13 (main, May 24 2022, 21:28:12) 
[Clang 12.0.0 (clang-1200.0.32.29)]
2022-09-06 00:28:38 Chargement de Nicotine+ 3.2.5
2022-09-06 00:28:38 Écoute du port : 2234
2022-09-06 00:28:38 Chargement du greffon système
2022-09-06 00:28:38 Vous devez spécifier un nom d'utilisateur et un mot de passe avant de vous connecter…
2022-09-06 00:28:45 UPnP : Le port externe 2234 a été redirigé avec succès vers l'adresse IP locale 192.168.0.xx du port 2234
2022-09-06 00:29:12 Réanalyse des partages…
2022-09-06 00:29:12 1590 répertoires trouvés avant réexamen, reconstruction…
2022-09-06 00:29:12 En cours de connexion à server.slsknet.org :2242
2022-09-06 00:29:12 Connecté au serveur server.slsknet.org :2242, ouverture de session en cours…
2022-09-06 00:29:13 1831 utilisateurs privilégiés
2022-09-06 00:29:13 Vous n'avez pas de privilèges. Les privilèges ne sont pas nécessaires, mais permettent à vos téléchargements d'être mis en file d'attente avant ceux des utilisateurs non privilégiés.
2022-09-06 00:29:13 Réanalyse terminée : 1590 dossiers trouvés
```

**Comment by EgonHeuson** [comment] 2022-09-05 22:33
Ok, after manually creating the folder /Users/egonheuson/.config/nicotine, the config files get created correctly and the app seems to work well now, keeping the config once closed. So I guess it's really the initial creation of the folder that creates en issue.

**Comment by slook** [comment] 2022-09-05 23:31
Similar to the above [failure to create downloads folder](https://github.com/nicotine-plus/nicotine-plus/issues/2001#issuecomment-1127130708) I suppose the problem with the config folder arises here:

https://github.com/nicotine-plus/nicotine-plus/blob/737d7a4aa7fae1f9ac7ad7b4c0a24aa6c89966b4/pynicotine/config.py#L127-L137

https://docs.python.org/3.10/library/os.html#mkdir-modebits

**Comment by slook** [comment] 2022-09-06 00:23
@EgonHeuson Please search for the folder `/Users/egonheuson/.local/share/nicotine/` and let us know if it exists or not?

If it doesn't exist, then you will need to create it manually for the program to work properly (download history, logs, etc).

**Comment by EgonHeuson** [comment] 2022-09-06 06:34
This one does exist :-). Only the /Users/egonheuson/.config/nicotine didn't exist. :-)

**Comment by EgonHeuson** [comment] 2022-09-06 06:37
> Similar to the above [failure to create downloads folder](https://github.com/nicotine-plus/nicotine-plus/issues/2001#issuecomment-1127130708) I suppose the problem with the config folder arises here:
> 
> https://github.com/nicotine-plus/nicotine-plus/blob/737d7a4aa7fae1f9ac7ad7b4c0a24aa6c89966b4/pynicotine/config.py#L127-L137
> 
> > ```
> > Impossible de créer le répertoire « /Users/USER/.config/nicotine », l'erreur est  : [Errno 13] Permission denied: '/Users/USER/.config/nicotine'
> > ```
> 
> https://docs.python.org/3.10/library/os.html#mkdir-modebits https://docs.python.org/3.6/library/pathlib.html#pathlib.Path.mkdir
> 
> > if I create it and **_authenticate_**, no problem I can create folders and files
> 
> For some reason the ownership of the user's `.config` folder prevents new folders from being created by the user of this system, but seems to allow the creation of files. Authentication would not normally be expected to create new folders in here.
> 
> Perhaps Apple now expects applications to create config folders during elevated installation. Maybe we need to ship a skeleton directory structure with the macOS installer @mathiascode ?

Agreed. After checking, the permission are 744 on the .config folder, which is in correlation with what you guessed:
<img width="275" alt="2022-09-06_08-35-12" src="https://user-images.githubusercontent.com/32910291/188563895-f15bff69-62be-4d8d-bab6-4c8a534b8f99.png">

**Comment by mathiascode** [comment] 2022-09-07 14:09
Which application does the oldest subfolder in the .config folder belong to? My guess is that you ran some application with admin privileges, which then created the .config folder with those permissions.

**Comment by slook** [comment] 2022-09-07 14:14
According to the user's screenshot "fish":

https://fishshell.com/
https://github.com/fish-shell/fish-shell/issues

**Comment by slook** [comment] 2022-09-18 16:46
Closing as the error message is correctly displayed to indicate the permissions problem in this edge-case scenario, which unfortunately it is not possible for us to mitigate.

**Closed by slook** 2022-09-18 16:46 UTC
