### ISSUE TITLE
Crash - Error flushing display: Broken pipe

### ISSUE THREAD

**Issue by ckx** [nicotine-plus/nicotine-plus#2839] opened 2024-01-25 22:06 UTC
Nicotine+ version: 3.2.9  •  GTK 3.24.40
Operating System/Distribution: Fedora 39, Plasma Wayland

I have `nicotine+-3.2.9-3.fc39.noarch` from the fedora repo, installed via dnf.

### Describe the bug
Intermittent crash, happens most often when I'm on the `Downloads` tab (with a few hundred downloads queued).

### Expected behavior
No crashes.

### Steps to reproduce the bug
It's hard to reproduce. I _feel_ like it happens most often when I've added new downloads to the queue and then I scroll the downloads list. I am unsure if it has ever happened to me on other parts of the UI, but if so it's rarer I think (granted I'm also just in other sections of the application less frequently too).

### Additional context
If I launch from CLI and wait for the crash, this is all the output I get:

```
Gdk-Message: 13:52:55.275: Error flushing display: Broken pipe
```

I'm pretty much always running it on a second monitor, 120Hz, 1920x1080. If there are additional logs somewhere I can grab let me know, I'm a pretty new user.

Basic gpu info (6950XT with standard amdgpu drivers):
```
10:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6950 XT] [1002:73a5] (rev c0)
        Subsystem: ASRock Incorporation Navi 21 [ASRock OC Forumla Radeon RX 6950XT] [1849:5230]
        Kernel driver in use: amdgpu
```

**Comment by slook** [comment] 2024-01-25 23:07
Does the crash happen to be triggered upon disconnected the external monitor (i.e. unplugging the cable from the port)?

**Comment by ckx** [comment] 2024-01-26 00:04
Nope, the display device never drops or gets disconnected. On that note it isn't a wake from sleep or hibernation issue either, it'll sometimes happen a few times in a single continuous session, sometimes back to back.

I did realize something though. Another (related?) crash happens when I first boot up Nictoine+ with some reliability. The client hangs for a solid few seconds on startup and then either recovers, or throws this:
```
Gdk-Message: 15:56:58.979: Lost connection to Wayland compositor.
```

I did a quick strace to try and understand what it's doing during the hang, but not sure it's very helpful, it spins its wheels spitting this out rapidly:

```
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=209899492}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=209982329}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a8, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=226805425}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=226894392}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=226973319}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7fed8a3f11a8, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7fed8a3f11a4, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=195774, tv_nsec=243775646}, FUTEX_BITSET_MATCH_ANY) = -1 EAGAIN (Resource temporarily unavailable)
```

This occurs right after it calls newfstatat on a bunch of paths in my downloads directory, I presume to see if a file already exists or something:

```
newfstatat(AT_FDCWD, "/hayate/media/incoming/#slsk/Foster The People/(2014) Supermodel/cover.jpg", 0x7ffee164def0, 0) = -1 ENOENT (No such file or directory)
write(7, "\1\0\0\0\0\0\0\0", 8)         
```

One additional note, though I dunno if it matters (just trying to dump info), is that my shares and download directories are all on a NAS, but the connection and mountpoint are stable throughout the process.

**Comment by ckx** [comment] 2024-01-26 01:04
Just had another Broken Pipe crash, guess I'll edit this comment each time it occurs so I can track exactly when it happens:

* Broken Pipe when I expanded a collapsed node in the "Downloads" tab, nothing much else going on.

**Comment by slook** [comment] 2024-01-26 12:59
Are these crashes also experienced in Nicotine+ 3.3.0rc3 ??
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by mathiascode** [comment] 2024-01-26 14:52
From personal experience, these kind of errors can happen when the GUI hangs/freezes long enough on Wayland.

**Comment by slook** [comment] 2024-02-01 23:28
@ckx [Nicotine+ 3.3.0](https://github.com/nicotine-plus/nicotine-plus/releases/tag/3.3.0) is released to stable. Please can you test it on your Wayland system.

**Comment by highon10kyears** [comment] 2024-02-13 07:26
I'm not OP but I am having the same issue on Nicotine+ 3.3.0, except that it is **not** intermittent (it happens **every** time I attempt to open my Uploads tab), and I am on sway 1.8.1 instead of Plasma Wayland.

**Comment by mathiascode** [comment] 2024-02-13 08:12
@highon10kyears
- When opening the Uploads tab, does Nicotine+ hang before crashing? If so, for how long?
- Are you using the GTK 4 version? Does it happen on GTK 3? (start Nicotine+ with `NICOTINE_GTK_VERSION=3 nicotine`)
- Could you send your uploads.json file (located in ~/.local/share/nicotine/) to my email address on my GitHub profile?

**Comment by highon10kyears** [comment] 2024-02-13 23:43
>     * When opening the Uploads tab, does Nicotine+ hang before crashing? If so, for how long?
> 
>     * Are you using the GTK 4 version? Does it happen on GTK 3? (start Nicotine+ with `NICOTINE_GTK_VERSION=3 nicotine`)
> 
>     * Could you send your uploads.json file (located in ~/.local/share/nicotine/) to my email address on my GitHub profile?

1. It does hang, for about 5-10 seconds, before crashing.
2. I am using the GTK 4 version: on GTK 3, the same behavior, including the hang and duration thereof, occurs, but the resulting error message is "Lost connection to Wayland compositor."
3. I sent it over.

**Comment by mathiascode** [comment] 2024-02-14 06:33
@highon10kyears I managed to bring down the loading time from 5 seconds to 4 seconds on my end. Could you try 3.3.1.dev1 and see if there's any improvement on your end? https://nicotine-plus.org/doc/TESTING.html

It would be helpful if you could run py-spy, to see if any performance improvements can be made. Do the following:

1. [Run Nicotine+ with py-spy](https://nicotine-plus.org/doc/DEVELOPING.html#profiling). Ensure the uploads tab is not activated on startup.
2. In py-spy, press L to enable line numbers. When Nicotine+ has started, press R to reset the output.
3. Activate the Uploads tab
4. Post the output here after the tab has loaded (or Nicotine+ is killed)

**Comment by slook** [comment] 2024-02-14 23:37
It doesn't seem like the crash will be solved with performance optimization alone. The problem is with the characteristic of the interface freezing while the main thread is busy loading the json, I guess Wayland times out and bails out.

**Comment by highon10kyears** [comment] 2024-02-14 23:48
![image](https://github.com/nicotine-plus/nicotine-plus/assets/33668568/06ef599c-7701-44ce-a348-f237b37462b2)

Oddly enough, the first time I booted 3.3.1dev1, it reproduced the "Broken pipe" crash when activating the Uploads tab, but I wasn't able to get the py-spy output (accidentally fat-fingered and closed my terminal); after that, it has successfully rendered the Uploads tab consistently.

**Comment by slook** [comment] 2024-02-15 00:03
I don't understand the cause of the crash, but the above py-spy shows a duplicated code that is redundant...

`add_row()`:
https://github.com/nicotine-plus/nicotine-plus/blob/d6dc507720922990733f667547d3587c7abfdc61/pynicotine/gtkgui/widgets/treeview.py#L496-L500

The most expensive code line during json load:
https://github.com/nicotine-plus/nicotine-plus/blob/d6dc507720922990733f667547d3587c7abfdc61/pynicotine/gtkgui/widgets/treeview.py#L505-L507

`insert_with_values()` from `add_row()` must end up calling `set_row_value()`:

https://github.com/nicotine-plus/nicotine-plus/blob/d6dc507720922990733f667547d3587c7abfdc61/pynicotine/gtkgui/widgets/treeview.py#L544-L548

The gvalue conversion code block is run twice.

**Comment by mathiascode** [comment] 2024-02-15 00:37
The problem seems to be that the main thread hangs long enough for certain Wayland compositors to kill the application. Some compositors seem to be much more eager to do this than others.

> insert_with_values() from add_row() must end up calling set_row_value()

insert_with_values() is first called when adding all rows, then set_row_value() is called to update parent rows.

Row insertions are very slow in GTK (O(n^2)), and there's little we can do about those while we still use Gtk.TreeView.

**Comment by slook** [comment] 2024-02-15 00:57
In that case, this processing needs to be somehow asynchronously offloaded.

No matter how much the transfers lists are optimized, there are always going to be cases where data iteration is going to take a long while.

Since its unrealistic to expect the model cannot be populated instantly, then it would be ideal if it was replaced with a spinner or progress bar widget until the list is ready.

**Comment by mathiascode** [comment] 2024-02-15 18:28
I pushed a few more optimizations, but I think we've run out of low-hanging fruit.

It might be possible to add rows without blocking the GUI, but quick testing showed that GTK heavily deprioritized the task (so instead of taking 4 seconds, it will take 30+ seconds). I really don't want to show a spinner for that long, so it will require further experimentation.

**Comment by slook** [comment] 2024-02-15 19:07
It looks like Wayland users will have to stick with 3.2.9 for the time being. This bug can't block 3.3.1 because we have a critical fix to push to stable release asap.

**Comment by mathiascode** [comment] 2024-03-18 20:36
Closing in favor of #2910. Same underlying issue, except some Wayland compositors kill the program when it freezes too long.

**Closed by mathiascode** 2024-03-18 20:36 UTC
Labels: bug
