### ISSUE TITLE
Add dates to statistics dialog

### ISSUE THREAD

**Issue by cproensa** [nicotine-plus/nicotine-plus#2316] opened 2023-01-11 11:06 UTC
Feature request: Add dates to the stats dialog, indicating the dates when the "current session" and the "total" recounting started

Currently the statistinc dialog only shows the quantities for each section: "current session", and "total"
It'd be helpful to have additional info regarding the timeframe of those values.
For example:
In each section add some text showing: "Since [date and hour]"

**Comment by slook** [comment] 2023-01-11 13:06
Closing as duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/1598 as completed in https://github.com/nicotine-plus/nicotine-plus/commit/50867c12c92cd8b402962cff987eb8e06858666a on Oct 30, 2022

The feature is in master 3.3.0+, but for old profiles it only starts to work if you reset stats.

**Closed by slook** 2023-01-11 13:06 UTC
Labels: duplicate, enhancement
