### ISSUE TITLE
function of return/enter key changes after clicking "Remove" button

### ISSUE THREAD

**Issue by blindingblacklight** [nicotine-plus/nicotine-plus#3073] opened 2024-08-07 18:03 UTC
Nicotine+ version:  3.3.4
Operating System/Distribution: macOS Sonoma 14.5 (23F79)

### Describe the bug

Function of the enter/return key changes if I click the "Remove" button.

### Expected behavior

I expect that when a user name is selected/highlighted and I hit return/enter, it will only toggle the expansion of the list of files, not remove them.

I expect that files and folders will be removed only when they are selected/highlighted and I then click the Remove button.

### Steps to reproduce the bug

1. Click the Downloads tab and see the list of users and their files that have downloaded or have yet to download.
2. Click on a user name from which the Nicotine user is downloading/has downloaded.
3. Hit return/enter on my keyboard.
4. The list of files downloaded/am downloading/have yet to download from the user who is sharing "collapses", as if the user who is downloading had clicked the triangle next to the user name. If I hit return/enter again, it toggles as if I were clicking the triangle.
5. I click on a file/folder, then click the "Remove" button (just to the right of the Pause button).
6. Click on a user name who is sharing.
7. Now when I hit return/enter on the keyboard, it will *Remove* that user (and all the files) from the download list.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by mathiascode** [comment] 2024-08-07 18:24
Widget focus is supposed to return to the tree view when clicking it. If you hold down the Alt key, is the Remove button still highlighted after clicking the username?

**Comment by mathiascode** [comment] 2024-08-19 14:35
I can't reproduce the issue on my end.

**Comment by mathiascode** [comment] 2024-08-29 23:45
Closing for reasons above. Please try 3.3.5rc1 and see if you still experience the issue: https://nicotine-plus.org/doc/TESTING.html#macos

**Closed by mathiascode** 2024-08-29 23:45 UTC
Labels: bug
