### ISSUE TITLE
Bitrate - Length - Speed

### ISSUE THREAD

**Issue by Geyup** [Nicotine-Plus/nicotine-plus#45] opened 2017-02-07 03:24 UTC
I noticed a few things with 1.4.0, not sure I understand what is going on, if this is just the way it is, depending on the user or something to do with soulseek?

I noticed when doing a search for a song, many of the songs don't even show a bitrate or length.

For me bitrate is really important to look for better quality...

Also under the Downloads section I noticed when I was done downloading the song under Speed it appeared like this;

Speed
0.1

By the way this is with 1.4.0 from your repo, is there suppose to be a speed indicated when done, like showing the average of what the download was? if so then ok it's showing something but ```0.1``` must be a bug since it's not showing the true average which was 20KB.

Also shouldn't a KB or MB be appearing after the numbers, when done as well as when a download is in progress? Also when downloading I will only see as example ```25.5``` 

Thanks

**Comment by gfarmerfr** [comment] 2017-02-07 21:58
For the search bitrate:

I noticed that too in 1.2.16 and 1.4.0. I've looked a little bit into it a few months ago but then I forget to come back to it. From what I remembered clients responding to the search request were sending these kind of informations (bitrate and length) in a non reliable manner. I mean, sometime the length was here but not the bitrate, sometime one of the two wasn't making any sense. I definitively need to take time to look into this.

For the speed:

It seems to not be indicated anywhere but it's in KB/s and it's an immediate speed. It seems to be calculated from the amount of data transferred between each GUI tick refresh (600ms) divide this interval of time. So when the transfer is completed at the beginning of one of these interval it xould be divide by the total amount of time 600ms and result in a very small number at the last refresh of the downloaded file.

**Comment by Geyup** [comment] 2017-02-08 06:44
Yeah the bitrate and length thing is really annoying, I hope you'll be able to resolve it.

Well with newer faster broadband speeds now in MB/s it would be nice when you get time if they can be showing either KB/s or MB/s.

THANKS

**Comment by gfarmerfr** [comment] 2017-02-08 19:18
Yeah I'll look at both issue probably this week-end.

**Comment by gfarmerfr** [comment] 2017-02-12 22:51
Hi @Geyup,

I've a working implementation of the speed units being displayed in my repo 'develop' branch.
I'll look at the other part (length & bitrate in the search tab) soon.

**Comment by gfarmerfr** [comment] 2017-02-13 21:02
Re @Geyup,

I've also added in the same branch a commit that try harder to find the bitrate and length of files in searches results.

Before this commit less than 10% of files had these infos, now it's more like 70%.
Some search results doesn't seems to give us any kind of infos other than the file size so I don't know how to have a better coverage for the time being. From what I've observed from the Qt client it seems to have the same behaviour: some clients don't report the extended attributes.

If you have time could you give a try to this branch and tell me if that seems good enough to you ?

**Comment by Geyup** [comment] 2017-02-17 02:59
Sounds good...

Well good enough for me, I don't think would be the issue, rather you being the developer, know the capability here better then me, of what to get, expect out of this...

I assumed every file you looked at would show this...

THANKS

**Comment by Geyup** [comment] 2017-02-17 03:41
Ok I gabbed from your repo and ran it...

I only saw around ```10%- 20%``` of files showing the bitrate and length....

The ```Number``` showed 418 songs, so this percentage ```10%- 20%``` I'd say is really low...

Hmm

**Comment by gfarmerfr** [comment] 2017-02-17 19:48
Hi @Geyup,

Just to be sure you used my develop branch on my repo right ? Because these number looks to me more like the code in the master branch.

**Comment by Geyup** [comment] 2017-02-18 03:08
I cloned from here ```https://github.com/gfarmerfr/nicotine-plus.git```

**Comment by gfarmerfr** [comment] 2017-02-18 12:13
Ok and then you did a `git checkout develop` to switch to the develop branch right ?

**Comment by Geyup** [comment] 2017-02-20 06:25
My bad I didn't do ```git checkout develop```...

After doing this now, and running nicotine, out of 500 files 100 didn't have info, so around 20% not showing...

**Comment by gfarmerfr** [comment] 2017-02-21 17:59
Yeah 80% coverage is more like it.
If you want to dig deeper you can compare with what SlskQt provide as answers but it seems to me that the problem is at the opposite end for some files. We just don't get all the needed metadata.
I'll push this branch in master and in the 1.4 branch for a future bugfix release.

**Closed** 2017-02-21 18:00 UTC
Labels: bug
