### ISSUE TITLE
Username Wrong Color in Chat

### ISSUE THREAD

**Issue by woollarding** [Nicotine-Plus/nicotine-plus#1013] opened 2021-03-02 13:18 UTC
Nicotine+ version:  3.0.2
Operating System/Distribution: LinuxMint 20

### Describe the bug
When chatting with a user their name shows up in the dark red color that is for showing user offline

### Expected behavior
not the offline color

note: having the option to have a different configurable color would be nice

### Steps to reproduce the bug
chat with a user

### Additional context
Screenshots, logs, stacktraces or relevant information.

note: having the option to have a different configurable color for users than my username would be nice

**Comment by woollarding** [comment] 2021-03-02 17:12
this may be corrected now, sorry

**Comment by Inso-m-niaC** [comment] 2021-03-02 18:55
i did notice previously when a user briefly went offline during a private message, and chatted again after coming back online the user colour tag didn't update.
i tested for this again moments ago and colours update just fine.

you can close this yourself if all is well @woollarding

**Comment by mathiascode** [comment] 2021-03-02 19:03
I think there's a minor regression where the color doesn't update if a user's status was previously fetched, and you open a new private chat tab for the user. Subsequent status updates for the user (away) trigger the color change.

**Closed** 2021-03-02 19:15 UTC
Labels: bug

**Comment by mathiascode** [comment] 2021-03-02 19:42
There was also an issue where the username color only changed in the last chat entry, caused by an unwanted change back when Nicotine+ was ported to GTK 3/Python 3.

**Comment by woollarding** [comment] 2021-03-03 15:32
it looks like its doing the red username thingy after i close the chat
window and then someone messages me again, i do have it set to away all the
time, not sure if that makes a difference

thanks for all your hard work, really appreciate it, wish i knew how to
help more but i don't code
