### ISSUE TITLE
Shared folder resets, Edit in shared folder causes error

### ISSUE THREAD

**Issue by jivemelon** [nicotine-plus/nicotine-plus#2153] opened 2022-08-12 05:24 UTC
Operating System/Distribution: Arch
Nicotine+ Version: 3.2.3
GTK Version: 3.24.34
Python Version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]

Type: <class 'ValueError'>
Value: list.remove(x): x not in list
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/widgets/dialogs.py", line 201, in on_response
    callback(self, response_id, callback_data)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/dialogs/preferences.py", line 689, in on_edit_shared_dir_response
    shared_dirs.remove(old_mapping)

### Describe the bug
Shared folder resets every time I close the preferences menu and clicking 'Edit' in the shared folder tab causes the program to freeze after showing an error, prompting me to have to force close from system resources.

**Comment by slook** [comment] 2022-08-12 07:16
Fixed in the [current stable version](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md) of Nicotine+ 3.2.4 

Duplicate of #2146 and #2142

**Closed by slook** 2022-08-12 07:16 UTC
Labels: bug, duplicate

**Comment by mathiascode** [comment] 2022-08-12 09:57
Looks like the maintainer of the Arch package has been away for a week. Might have to wait for some time, use Menu -> Help -> Setup Assistant in the meantime.

**Comment by jivemelon** [comment] 2022-08-12 10:17
I built and installed nicotine-plus-git from the AUR and everything is updated and working perfectly now. Thanks for the help and sorry for the duplicate.
