### ISSUE TITLE
OS error: [Errno 13] Permission denied on Windows 10

### ISSUE THREAD

**Issue by RaverSnowLep** [nicotine-plus/nicotine-plus#2179] opened 2022-09-11 14:27 UTC
Nicotine+ version:3.2.4rc1 GTK3.24.34  
Operating System/Distribution: Windows 10 latest update as of 9/11/22

### Describe the bug
My friend ran into this issue when downloading a 22GB file from me: OS error [Errno 13] Permission denied: b'\\\?\\D:\\Games\\"FILENAME"
This caused the download to throw this error then show 100% completion and fill his download folder with 50 or so DLL files.
I have the screenshots and they will be linked below.

### Expected behavior
The file would download fully.

### Steps to reproduce the bug
Simply download a file of the same size. Obviously this doesnt happen all the time and we arent sure what happened this time to cause it.

### Additional context
https://imgur.com/a/usF0nAD

**Comment by slook** [comment] 2022-09-11 19:37
This looks like the large file was perhaps an archive containing exectuables with associated DLL library files? If this is the case then perhaps another daemon program on the destination system has detected, quarantined, moved, expanded then locked maybe because some of the contents was detected as potential malware like a packaged keygen or third-party licensing tool, but this is only a guess.

There is not enough information in your bug report to indicate that this is a bug in Nicotine+, since is not obvious as to whether the error could have been caused by a third-party program, a built-in operating system feature or there could be some other explanation for what has occurred on the destination machine, given there are a lot of running tasks open in the screenshot you provided it is a busy system so it might be difficult to identify the exact cause.

In any case where another program continuously interrogates the contents of filesystem activity and is capable of intercepting a file socket during network transfers then it would be expected that a client such as Nicotine+ won't be able to operate very well in that environment (and furthermore operating any client on such a system may pose a privacy concern for the user). Unfortunately this type of invasive commercial software is common on machines running proprietary operating systems, and the behaviour of those system vendor approved scanning applications and core system processes are not well understood by anybody since they are usually closed source, which makes it difficult to isolate and ascertain what actions those processes might do at any given time or even what purpose they serve!

Please ask your friend to help you with further testing to find out if the error is persistent when downloading the same (and other) file(s) with the **'Prevent write access by other programs for files being download'** setting enabled (in Preferences > Downloads), and let us know if that resolves the error or not?

**Comment by slook** [comment] 2022-09-18 16:43
Closing this doesn't appear to be a bug in Nicotine+

**Closed by slook** 2022-09-18 16:43 UTC
