### ISSUE TITLE
Show transfers in Kbs instead of MB/s?

### ISSUE THREAD

**Issue by magnog0** [nicotine-plus/nicotine-plus#2119] opened 2022-07-05 00:47 UTC
Hello is it possible to show the trasnfers  in Kbs? insead of MB/s? i.e https://files.catbox.moe/08slu8.png thanks! maybe you can add it as a feature in the future so we can pick in the settings :)

**Comment by mathiascode** [comment] 2022-07-05 11:12
Apparently people have different opinions about this (see #1948), so I'll probably add a setting at some point.

**Comment by slook** [comment] 2022-07-05 11:49
On a slow connection, the transfer Speed is not usually high enough to warrant abbreviation to MiB/s, and having two different units constantly changing in the same column can make the data difficult to compare. Those with fast connections may feel differently, and if both peers have super-fast connections they probably still need an "Automatic" option such that is currently in place.

The Size would indeed be easier to read and compare if all the items had the same unit, and the preference as to which unit to choose depends on each use case, such that the same user may need to frequently alter the displayed unit in accordance with certain operations they need to do.

Therefore, such options would ideally be available from a context menu within the main interface, rather than being buried somewhere in the Preferences.

**Comment by magnog0** [comment] 2022-07-05 12:52
> Apparently people have different opinions about this (see #1948), so I'll probably add a setting at some point. Do you want the size in KB too?

I mean might as well add the option for that as well, the more customizable the better!  Thank you Mathia, can't wait for your to implement it, any chance you can make the speeds more consistent in the downloads upload section? I don't think it updates in real time like the original slsk.

**Comment by magnog0** [comment] 2022-07-05 14:02
I have 3.3 dev build I go between 3.3 and 3.2.2. thanks for the speedy replies btw it's nice. Nice to know you guys listen :)

**Comment by slook** [comment] 2022-07-05 17:53
You're welcome :) It's nice to know the users care about the project enough to give feedback and make suggestions which help to make things better for everybody.

When I recently helped with improving the responsiveness of the transfers UI it was very clear to me that the counting of the speed is actually quite resource intensive, especially when there are many items in the list, so compromises have to made as to the importance of accuracy vs performance.

In regard to the fluctuating speeds you are observing then we think this is probably an unrelated issue to do with other clients which try to push data faster than the network can handle it, but it's difficult to know how to approach the issue at the moment.

Hopefully perhaps while implementing the speed unit options then this may help some areas of improvement come to light.

**Comment by magnog0** [comment] 2022-07-05 23:07
> Hopefully perhaps while implementing the speed unit options then this may help some areas of improvement come to light.

good point, hopefully one adding this stuff fingers crossed next test build! maybe it'll be better, we can only see! keep up the great work, let's make this app perfect!

**Comment by magnog0** [comment] 2022-07-28 01:50
did you add completed transfer speeds? i've noticed that in the latest test build, it's a little buggy tho but glad you added it!

**Comment by mathiascode** [comment] 2022-07-28 09:14
Buggy in which way? There were some fixes about two weeks ago for transfer speeds not always showing up. Have you updated your testing build since?

**Comment by magnog0** [comment] 2022-07-28 09:53
> 

Sometimes it would show incorrect numbers for example yesterday I'm sharing a file that was 333mb and it says I uploaded at 333mb/s , it's like now and then it randomly pulls the number from the file size, you'll probably see it as well

**Comment by mathiascode** [comment] 2022-07-28 14:28
Can you try the latest unstable build to see if 6aa46d697ac47c39e953aaefc4c6b0a839e6ddb6 helps at all?

**Comment by magnog0** [comment] 2022-07-28 14:30
Hi bro let me know if you get this message

**Comment by mathiascode** [comment] 2022-07-28 15:04
I can see your message.

**Comment by magnog0** [comment] 2022-07-28 15:53
Ok, I'll try the build tonight, also any word on adding kbs as an option?
Instead of mbs?

**Comment by mathiascode** [comment] 2022-07-28 16:24
Thanks! I'll look into adding an option at some point after Nicotine+ 3.2.3 is released.

**Comment by mathiascode** [comment] 2022-07-29 01:15
I found the issue related to the upload speed. f3b779d4e4af241020ed254c60cb49e221a7f943 takes care of it.

**Comment by mathiascode** [comment] 2022-07-30 06:17
The build is ready, just download again.

**Comment by magnog0** [comment] 2022-07-30 12:30
Thanks when will the Linux build be ready? It's still the same there

**Comment by mathiascode** [comment] 2022-07-30 16:48
Which installation method and distro?

**Comment by magnog0** [comment] 2022-07-30 16:54
https://nicotine-plus.org/doc/TESTING.html .DEB package I use Ubuntu! I
don't think you've updated that one yet

**Comment by mathiascode** [comment] 2022-07-30 17:10
Looks like it wasn't updating due to the macOS build failing. Should be up to date now.

**Comment by magnog0** [comment] 2022-07-30 17:19
Thanks I love how active you are, you just be the only dev that listens to
the feedback of the users love that, keep it up! Will install when I get
home!

**Comment by magnog0** [comment] 2022-07-31 18:17
Hey ok so I think it's still doing it, I have a screenshot in case you want
to check it out

**Comment by mathiascode** [comment] 2022-07-31 21:39
Sure

**Comment by magnog0** [comment] 2022-07-31 22:26
![20220731_141616](https://user-images.githubusercontent.com/106936342/182047715-24a4f75d-e525-45e7-99ec-6d3a150793cb.jpg)
 
Let me know if you get the image

**Comment by slook** [comment] 2022-07-31 22:50
Yes can see it thanks for the screen photo. Do your transfers actually complete in exactly 1 second?

**Comment by magnog0** [comment] 2022-07-31 22:53
Usually if they are small files like these and they get a good speed yeah, and it doesn't show time for all of the times it seems to be random

**Comment by slook** [comment] 2022-07-31 22:54
Well if the transfers only take 1 second to complete then the speed calculation is as accurate as it can possibly be, since the speed calculation only occurs once every second.

**Comment by magnog0** [comment] 2022-07-31 23:03
Ah ok... Yeah I guess that makes sense also it could just be a Linux issue
I haven't tested it in my PC yet!

**Comment by slook** [comment] 2022-07-31 23:06
https://github.com/nicotine-plus/nicotine-plus/blob/c7cbab482141b4049783aa8313447788962d3fa8/pynicotine/gtkgui/transferlist.py#L353

Suggest change `>= 1` to `> 0`

**Comment by mathiascode** [comment] 2022-08-01 11:06
> Suggest change `>= 1` to `> 0`

Fixed in 339db1dfb3e133dc6b40b7e4d3c7eeaaefb07cf7

> Or add `transfer.time_elapsed += 1` in upload_finished() which might infact be more accurate since the current calculation doesn't take into account the processing time involved with queuing, initializing and finalizing the transfer.

Initializing a transfer can take a few seconds in some rare cases, so this wouldn't be accurate anyway.

**Comment by magnog0** [comment] 2022-08-05 21:24
Hey Matt nicotine isn't adding my folders, I add the folder and then it
rescans 0 folders, when I go back to configure shares the folder is not
there. This has been happening for a while now, I'm using 3.2.3rc4 Linux.

**Comment by mathiascode** [comment] 2022-08-05 21:55
Sigh, I can reproduce it in an older Ubuntu version, and I already tagged 3.2.3. Damn it...

**Comment by mathiascode** [comment] 2022-08-05 23:04
Can you verify that it's fixed in 3.2.4rc1? https://github.com/nicotine-plus/nicotine-plus/blob/3.2.x/doc/TESTING.md

**Comment by magnog0** [comment] 2022-08-05 23:08
I'll try, is this for Linux yeah?

**Comment by mathiascode** [comment] 2022-08-05 23:10
yes, same procedure as always

**Comment by magnog0** [comment] 2022-08-06 02:14
Hey sorry I'm home now gonna try now!

**Comment by magnog0** [comment] 2022-08-06 10:21
Seems to be working now

**Comment by mathiascode** [comment] 2022-08-06 17:02
Thanks for confirming, I'll release 3.2.4 today with the fix.

**Comment by magnog0** [comment] 2022-08-06 17:30
Np, happy to help I'll let you know if any bugs I come across! And idea when this will be fixed? 
![20220806_110140](https://user-images.githubusercontent.com/106936342/183259599-d88554fd-7ad5-468f-829f-f22890980106.jpg)
 That's from the latest Linux test build.

**Comment by mathiascode** [comment] 2022-08-06 19:02
I don't think there's an issue here. If the upload completes in a second or less, the upload speed will naturally be the same as the file size.

**Comment by slook** [comment] 2022-08-07 16:57
>> Maybe we should bump all the time elapsed values to start at 1 instead of 0 to allow for this

> Initializing a transfer can take a few seconds in some rare cases, so this wouldn't be accurate anyway.

True, but assuming it always takes at least 1 second might be better than 0:00 being displayed as this does not match the speed calculation.

**Comment by magnog0** [comment] 2022-08-07 19:35
Just do what soulseek does and display a 0 not 0.00

**Comment by slook** [comment] 2022-08-08 13:36
I don't see how that would help.

**Comment by mathiascode** [comment] 2022-11-29 15:30
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1948

**Closed by mathiascode** 2022-11-29 15:30 UTC
Labels: enhancement
