### ISSUE TITLE
python issue?

### ISSUE THREAD

**Issue by aka399** [nicotine-plus/nicotine-plus#2007] opened 2022-05-01 09:36 UTC
Nicotine+ Version: 3.2.2
GTK Version: 3.24.31
Python Version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]

Type: <class 'TypeError'>
Value: could not get a reference to type class
Traceback:   File "/usr/lib/python3.10/site-packages/pynicotine/pynicotine.py", line 464, in network_event
    self.events[i.__class__](i)
  File "/usr/lib/python3.10/site-packages/pynicotine/pynicotine.py", line 692, in join_room
    self.chatrooms.join_room(msg)
  File "/usr/lib/python3.10/site-packages/pynicotine/chatrooms.py", line 173, in join_room
    self.ui_callback.join_room(msg)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/chatrooms.py", line 170, in join_room
    self.pages[msg.room] = tab = ChatRoom(self, msg.room, msg.users)
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/chatrooms.py", line 385, in __init__
    ChatEntry(self.frame, self.ChatEntry, chatrooms.completion, room, slskmessages.SayChatroom,
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/widgets/textentry.py", line 65, in __init__
    self.frame.init_spell_checker()
  File "/usr/lib/python3.10/site-packages/pynicotine/gtkgui/frame.py", line 345, in init_spell_checker
    self.spell_checker = Gspell.Checker()

fresh install of Nicotine+ vi a pacman on Arch (recently updated)

**Comment by mathiascode** [comment] 2022-05-01 11:37
Duplicate of #2006

**Closed by mathiascode** 2022-05-01 11:37 UTC
Labels: bug
