### ISSUE TITLE
bug or feature ?

### ISSUE THREAD

**Issue by zniavre** [Nicotine-Plus/nicotine-plus#47] opened 2017-02-07 16:08 UTC
Hello, just noticed some diif between 1.2.17 and 1.4.0 upnp seems to does not work, the way to change icons also does not work 'as before'

(~/Téléchargements/nicotine-plus-master$ ./nicotine 
mar. 16:53 UPnP exception: Échec de redirection du port WAN externe: Invalid Args
mar. 16:53 Échec de création de la règle de redirection de port UPnP.)

and the way to modify languages: now im in french and i still to keep it in english

thank you.

im ><((((*> in nicotine room if you need/want helps

**Comment by zniavre** [comment] 2017-02-08 07:39
hello again, after looking inside i hav found the new icon naming for trayicon, i deleted the fr.po ...

just upnp thingy who still does not work , i got new error messages in english so it's better for you i guess:

zniavre@zniavre:~/Téléchargements/nicotine-plus-master$ ./nicotine 
mer. 07:30 UPnP exception: Failed to map the external WAN port: Invalid Args
mer. 07:30 Failed to automate the creation of UPnP Port Mapping rule.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387f8bd0>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387f8c10>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3441c1fd0>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535050>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535c50>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387f8d90>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387d0290>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387d0890>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535050>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535a10>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535090>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb338535310>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387d0e90>.
WARNING: Could not find transfer <pynicotine.transfers.Transfer object at 0x7fb3387d0d50>.
/home/zniavre/Téléchargements/nicotine-plus-master/pynicotine/gtkgui/frame.py:1306: Warning: Source ID 19685 was not found when attempting to remove it
  gobject.source_remove(self.awaytimer)



it works regulary with 1.2.17svn

it looks also like upload are not working quite well they stay 'cannot connect' states

hope it s helpfull ...  thank you

**Comment by gfarmerfr** [comment] 2017-02-08 20:11
Hi @zniavre ,

Yes I remove the way to switch from the UI to other locales because most applications aren't doing this but the major reason was because of unreliable Windows support. For the last few years each version of Windows has come with a different naming scheme for locales. Locales definition also depends on what VisualStudio version python was compiled with. To be short: a nightmare to be able to determine what the locale name should be... At least with Win10 they seems to have come to their senses and it's now similar to what linux does. I think this function might be reintroduced when we managed to switch to python3 since it's compiled with VS2015 if my memory serves well.

There's at least two ways to have the english version:
- In the command line with `LC_ALL=en_US.UTF-8 nicotine`
- Like you did removing the fr.mo does the trick too.
- I think you can all modify a local .desktop file (not tested) as describe [here](https://wiki.archlinux.org/index.php/Desktop_entries#Modify_environment_variables)

For UPnP:
Do you have the python bindings for miniupnpc (python-miniupnpc package) installed or do you use the binary (miniupnpc package) ? Can you also provide the version you're using ?
I suppose you fall back to using static port redirection with your router ? If not it would explain the uploads having problems.

Trayicon: You were trying to change the trayicon right ? Yes sorry I changed the icons names to be more clear about their functions because lots of them were reused everywhere without indication and I had to scan the source code to find out what icon was used for what purpose.

**Comment by eLvErDe** [comment] 2017-02-08 21:02
Hey,

I came across this link for proper language detection in Windows a few days ago:

http://stackoverflow.com/a/25691701

On February 8, 2017 9:11:23 PM GMT+01:00, Michael Labouebe <notifications@github.com> wrote:
>Hi @zniavre ,
>
>Yes I remove the way to switch from the UI to other locales because
>most applications aren't doing this but the major reason was because of
>unreliable Windows support. For the last few years each version of
>Windows has come with a different naming scheme for locales. Locales
>definition also depends on what VisualStudio version python was
>compiled with. To be short: a nightmare to be able to determine what
>the locale name should be... At least with Win10 they seems to have
>come to their senses and it's now similar to what linux does. I think
>this function might be reintroduced when we managed to switch to
>python3 since it's compiled with VS2015 if my memory serves well.
>
>There's at least two ways to have the english version:
>- In the command line with `LC_ALL=en_US.UTF-8 nicotine`
>- Like you did removing the fr.mo does the trick too.
>- I think you can all modify a local .desktop file (not tested) as
>describe
>[here](https://wiki.archlinux.org/index.php/Desktop_entries#Modify_environment_variables)
>
>For UPnP:
>Do you have the python bindings for miniupnpc (python-miniupnpc
>package) installed or do you use the binary (miniupnpc package) ? Can
>you also provide the version you're using ?
>I suppose you fall back to using static port redirection with your
>router ? If not it would explain the uploads having problems.
>
>Trayicon: You were trying to change the trayicon right ? Yes sorry I
>changed the icons names to be more clear about their functions because
>lots of them were reused everywhere without indication and I had to
>scan the source code to find out what icon was used for what purpose.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nicotine-Plus/nicotine-plus/issues/47#issuecomment-278447200

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by zniavre** [comment] 2017-02-09 14:35
hello thank you answering

1/ im using ubuntu 16.10 
2/ i got python-miniupnpc 1.9.2014010-2ubuntu2   (from repos)
    miniupnpc 1.9.20140610-ubuntu2 (from repos)
    libminiupnpc10 1.9.2014610-ubuntu2 (from repos)
3/ any chance to port nic+ to python3 and gtk+3 ?

thank you again
 salut à vous ! 
  ><((((*>

**Comment by gfarmerfr** [comment] 2017-02-12 23:22
@eLvErDe :
The problem is not to detect a locale but to set one :)
Python 2.7 is compiled with VS2008, so to switch to another locale you must now the target ["language string"](https://msdn.microsoft.com/en-us/library/39cwe7zf(v=vs.90).aspx) under windows. Until VS2012 it was quite a nightmare and require some ugly hack with hardcoded mapping arrays like this: https://gist.github.com/schlamar/4130239
Python 3.5 and onwards is compiled with VS2015 so the locales names are identical to what Unixes does.

For a full deep dive explanation see [this comment](https://stackoverflow.com/questions/32037573/load-gtk-glade-translations-in-windows-using-python-pygobject/32061833#32061833).

@zniavre :
1 + 2 ) ok I'll look into this this week.
3) I've seen your comment on IRC. Yes it's on the roadmap.

**Comment by gfarmerfr** [comment] 2017-02-27 23:21
Hi @zniavre 

I find out what the bug is with UPnP.
The problem was in the code that was trying to find the local IP address of the box.
I'll send a patch tomorrow once I've tested it on all platforms.

**Comment by gfarmerfr** [comment] 2017-03-01 22:06
@zniavre: I've just pushed the fix for UPnP on master.

Could you check if it's working for you ?

**Comment by zniavre** [comment] 2017-03-02 06:51
it looks like it works as before

slsktest:
 IP: 82.250.70.139 Port: 15000/tcp open. Your router and Soulseek client is configured correctly.

pastebien debug log from nic+:
http://pastebin.com/DLqyersW

thank you

**Comment by gfarmerfr** [comment] 2017-03-02 18:01
Great. That's also what I'm seeing on all OSes I've tested (fedora 25, ubuntu 16.04 + 16.10, debian stable, arch, win7, win10). Closing this issue.

**Closed by gfarmerfr** 2017-03-02 18:01 UTC
Labels: bug
