### ISSUE TITLE
Nicotine+ 3.3.1 crash on tuple index out of range

### ISSUE THREAD

**Issue by 501NotImplemented** [nicotine-plus/nicotine-plus#2907] opened 2024-02-29 18:03 UTC
Nicotine+ Version: 3.3.1
Operating System/Distribution:
Nicotine+ Version: 3.3.1
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)
OS: Windows 11 Pro
Version	23H2
OS build	22631.3155
Experience	Windows Feature Experience Pack 1000.22684.1000.0

### Describe the bug
Nicotine+ crashes randomly

### Expected behavior
The app should not crash and continue execution.

### Steps to reproduce the bug
No particular, the app crashes at some point.
From the log, it might be related to file rescan issues (see screenshot).

Type: <class 'IndexError'>
Value: tuple index out of range
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 961, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 290, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 435, in _file_search_request_distributed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 688, in _process_search_request
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 474, in _create_file_info_list

![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/b5c4b1c9-791f-44ad-b629-681b5ed4b199)

**Comment by slook** [comment] 2024-02-29 19:08
Regression since 67d84e5f

**Comment by mathiascode** [comment] 2024-02-29 19:36
https://github.com/nicotine-plus/nicotine-plus/commit/e8b8a910582b1fd3b99e514b3c4e561c399e7bb1 makes scanning actually fail.

@501NotImplemented Can you try the latest unstable build? It should provide a more detailed error message.
https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by 501NotImplemented** [comment] 2024-02-29 20:17
@mathiascode I've upgraded to 3.3.2 for now, the issue did not reproduce for now.
I'll also share the problematic files with you via email.

**Comment by 501NotImplemented** [comment] 2024-02-29 21:25
Okay, I've caught it on 3.3.2 after enabling rescan shares on the startup option. Will try the latest testing build as well.

Nicotine+ Version: 3.3.2
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)

`Type: <class 'IndexError'>
Value: tuple index out of range
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 961, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 290, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 435, in _file_search_request_distributed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 688, in _process_search_request
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 474, in _create_file_info_list`

Here's also the content of debug log file:

> 29.02.2024 23:24:13 Loading Python 3.11.8
29.02.2024 23:24:13 Loading Nicotine+ 3.3.2
29.02.2024 23:24:13 Faulthandler module could not be enabled. Error: sys.stderr is None
29.02.2024 23:24:13 Loading GTK 4.12.5
29.02.2024 23:24:13 Loading plugin system
29.02.2024 23:24:13 Loaded plugin Nicotine+ Commands
29.02.2024 23:24:13 Leech Detector: Require users have a minimum of 1 files in 1 shared public folders.
29.02.2024 23:24:13 Loaded plugin Leech Detector
29.02.2024 23:24:13 Loaded plugin Auto-Browse Shares
29.02.2024 23:24:13 Listening on port: 2234
29.02.2024 23:24:13 Connecting to server.slsknet.org:2242
29.02.2024 23:24:13 Connected to server server.slsknet.org:2242, logging in…
29.02.2024 23:24:14 UPnP: Failed to forward external port 2234: HTTP Error 500: Internal Server Error
29.02.2024 23:24:15 1983 privileged users
29.02.2024 23:24:15 You have no Soulseek privileges. While privileges are active, your downloads will be queued ahead of those of non-privileged users.

**Comment by slook** [comment] 2024-03-01 13:08
You can enable the "Search" and "Miscellaneous" [debug logging catagories](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#debug-logging) for more detailed information.

What we know so far is that the crash is triggered at the moment the client prepares to serve an incoming search request using faulty shares data arising from an invalid Flac header.

**Comment by mathiascode** [comment] 2024-03-01 15:17
The files you sent are corrupted. None of them play, and one is full of null bytes.

> What we know so far is that the crash is triggered at the moment the client prepares to serve an incoming search request using faulty shares data arising from an invalid Flac header.

This isn't completely right. The screenshot says there was an issue saving the database at the end of the rescan process. Due to an additional try except, the scanner didn't catch this, assumed the scan finished successfully, and enabled search request processing with invalid/previous data.

The invalid files shouldn't be causing this issue, the scanner will just skip setting metadata for them.

@501NotImplemented Can you try a rescan in the testing build, and see if it fails again and shows more details about the issue?

**Comment by 501NotImplemented** [comment] 2024-03-01 17:21
@mathiascode I've sent you debug logs from the client Nicotine+ 3.3.3.dev1. Please check your mail.
The client crashed several times silently when I've just opened the Uploads tab. If I can provide any other logs or useful info - please let me know.

One log line that brought to my attention:
`01.03.2024 19:15:32 Failed to fetch the shared folder To listen\France\Kromozom 4 - 2019 Hardcore Fun - À Boire Et À Manger (Et D'Autres Vieux Trucs Dedans): argument of type 'NoneType' is not iterable`

**Comment by slook** [comment] 2024-03-01 18:09
The `None` value should be an empty `set()`.

**Comment by mathiascode** [comment] 2024-03-01 18:52
> @mathiascode I've sent you debug logs from the client Nicotine+ 3.3.3.dev1. Please check your mail. The client crashed several times silently when I've just opened the Uploads tab. If I can provide any other logs or useful info - please let me know.

Unfortunately, it looks like rescanning succeeded this time, so I have no idea what caused it to fail before.

Is the Uploads tab issue unrelated to this one? By silent crash, do you mean the window just closes when opening the Uploads tab?

> One log line that brought to my attention: `01.03.2024 19:15:32 Failed to fetch the shared folder To listen\France\Kromozom 4 - 2019 Hardcore Fun - À Boire Et À Manger (Et D'Autres Vieux Trucs Dedans): argument of type 'NoneType' is not iterable`

Was this before the most recent rescan?

**Comment by mathiascode** [comment] 2024-03-01 18:53
> > the scanner will just skip setting metadata for them
> 
> The `None` value should be an empty `set()`.

What are you talking about? What part of the code?

**Comment by 501NotImplemented** [comment] 2024-03-01 19:02
@mathiascode yes, that particular message was before the most recent rescan.

For now - I've deleted the corrupted files from the drive.
Delete the folder, where those corrupted files were located from shared list
Deleted the .dbn files from the AppData\Roaming\nicotine
Forced the rescan, it successfully completed from the logs.

`01.03.2024 20:30:21 Rebuilding shares…
01.03.2024 20:30:50 Rescan complete: 23328 folders found`

As of this moment - I am able to browse my files again, and the Nicotine+ does not crash. But it shows 0 files and 0 folders shared for me. In User Profile and Buddy list. Does it take some time to show the correct value?

I've shared the folder again and forced a rescan from private chat as @slook suggested.
`01.03.2024 20:58:46 Rebuilding shares…
01.03.2024 20:59:26 Rescan complete: 30553 folders found`

Still 0 files shared on UI, but i see new Uploads are starting and running and I still can browse myself.

**Comment by slook** [comment] 2024-03-01 19:35
> Still 0 files shared is shown on UI in User Profile

That is the value reported by the server, which takes a while to update.

>>    The None value should be an empty set().

> What are you talking about? What part of the code?

https://github.com/nicotine-plus/nicotine-plus/blob/8842b470641e8313cb30a95d41878b19e207158e/pynicotine/slskmessages.py#L424

**Comment by slook** [comment] 2024-03-03 13:21
@501NotImplemented what is the status of this bug? Is it fixed now or are we not able to establish the exact cause?

**Comment by 501NotImplemented** [comment] 2024-03-03 14:29
@slook 
![image](https://github.com/nicotine-plus/nicotine-plus/assets/32591300/489d510c-8af9-45af-b3e6-a87e11563d59)

Yes, I've tried as you've suggested. See screenshot. Nicotine+ 3.3.3.dev1

**Steps to reproduce:**
1. Disable the network connection
2. Start Nicotine+, so it attempts to connect and fails
3. Enable the network
4. Manually connect the Nicotine+ (Righ click on tray icon > Connect)

**Actual result:**
Nicotine+ is connected, the transfers start from the online user, but it still shows User is logged off status on Downloads tab for Queued uploads. If the status is manually updated - right click on the root username on the Downloads pane and select Resume - the status is correctly updated to Queued.

**Expected result:**
The status should be updated to Queued uploads on the Nicotine+ connection.

`03.03.2024 16:20:37 Loading plugin system
03.03.2024 16:20:37 Loaded plugin Nicotine+ Commands
03.03.2024 16:20:37 [Misc] Enabled plugin(s): core_commands, leech_detector, auto_user_browse
03.03.2024 16:20:37 Leech Detector: Require users have a minimum of 1 files in 1 shared public folders.
03.03.2024 16:20:37 Loaded plugin Leech Detector
03.03.2024 16:20:37 Loaded plugin Auto-Browse Shares
03.03.2024 16:20:37 Reconnecting to server in 12 seconds
03.03.2024 16:20:37 Cannot listen on port 2234. Ensure no other application uses it, or choose a different port. Error: [WinError 10051] A socket operation was attempted to an unreachable network
03.03.2024 16:20:37 [Misc] CLI input prompt is no longer available: input(): lost sys.stdin
03.03.2024 16:20:39 Rescanning shares…
03.03.2024 16:20:49 Reconnecting to server in 24 seconds
03.03.2024 16:20:49 Cannot listen on port 2234. Ensure no other application uses it, or choose a different port. Error: [WinError 10051] A socket operation was attempted to an unreachable network
03.03.2024 16:21:13 Reconnecting to server in 48 seconds
03.03.2024 16:21:13 Cannot listen on port 2234. Ensure no other application uses it, or choose a different port. Error: [WinError 10051] A socket operation was attempted to an unreachable network
03.03.2024 16:21:40 [Misc] Local IP address: 192.168.88.231
03.03.2024 16:21:40 [Misc] Maximum number of concurrent connections (sockets): 512
03.03.2024 16:21:40 Listening on port: 2234
03.03.2024 16:21:40 Connecting to server.slsknet.org:2242
03.03.2024 16:21:40 Connected to server server.slsknet.org:2242, logging in…
03.03.2024 16:21:41 [Misc] Creating Port Mapping rule...
03.03.2024 16:21:41 [Misc] NAT-PMP: Portmap request attempt 1 of 2: b'\x00\x02\x00\x00\x08\xba\x08\xba\x00\x00\xa8\xc0'
03.03.2024 16:21:41 [Misc] NAT-PMP not available, falling back to UPnP: [WinError 10054] An existing connection was forcibly closed by the remote host
03.03.2024 16:21:41 [Misc] UPnP: Discovering... delay=1 seconds
03.03.2024 16:21:41 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Sent M-SEARCH IP request 1
03.03.2024 16:21:41 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANPPPConnection:1\r\nMAN: "ssdp:discover"\r\nMX: 1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Sent M-SEARCH PPP request 1
03.03.2024 16:21:41 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nMAN: "ssdp:discover"\r\nMX: 1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Sent M-SEARCH IGD request 1
03.03.2024 16:21:41 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:service:WANIPConnection:2\r\nMAN: "ssdp:discover"\r\nMX: 1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Sent M-SEARCH IP request 2
03.03.2024 16:21:41 [Misc] UPnP: SSDP request: b'M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:2\r\nMAN: "ssdp:discover"\r\nMX: 1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Sent M-SEARCH IGD request 2
03.03.2024 16:21:41 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=3600\r\nEXT: \r\nLOCATION: http://192.168.88.1:2828/gateway.xml\r\nSERVER: RouterOS/6.49.8UPnP/1.0 MikroTik UPnP/1.0\r\nST: urn:schemas-upnp-org:service:WANIPConnection:1\r\nUSN: uuid:UUID-MIKROTIK-WAN-CONNECTION-DEVICE-8SBP-3M48-3::urn:schemas-upnp-org:service:WANIPConnection:1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Device description response from http://192.168.88.1:2828/gateway.xml: b'<?xml version="1.0"?>\r\n<root xmlns="urn:schemas-upnp-org:device-1-0">\r\n  <specVersion>\r\n    <major>1</major>\r\n    <minor>0</minor>\r\n  </specVersion>\r\n  <device>\r\n    <deviceType>urn:schemas-upnp-org:device:InternetGatewayDevice:1</deviceType>\r\n    <friendlyName>MikroTik Router</friendlyName>\r\n    <manufacturer>MikroTik</manufacturer>\r\n    <manufacturerURL>http://www.mikrotik.com/</manufacturerURL>\r\n    <modelName>Router OS</modelName>\r\n    <UDN>uuid:UUID-MIKROTIK-INTERNET-GATEWAY-DEVICE-8SBP-3M48</UDN>\r\n    <iconList>\r\n      <icon>\r\n        <mimetype>image/gif</mimetype>\r\n        <width>16</width>\r\n        <height>16</height>\r\n        <depth>8</depth>\r\n        <url>/logo16.gif</url>\r\n      </icon>\r\n      <icon>\r\n        <mimetype>image/gif</mimetype>\r\n        <width>32</width>\r\n        <height>32</height>\r\n        <depth>8</depth>\r\n        <url>/logo32.gif</url>\r\n      </icon>\r\n      <icon>\r\n        <mimetype>image/gif</mimetype>\r\n        <width>48</width>\r\n        <height>48</height>\r\n        <depth>8</depth>\r\n        <url>/logo48.gif</url>\r\n      </icon>\r\n    </iconList>\r\n    <serviceList>\r\n      <service>\r\n        <serviceType>urn:schemas-microsoft-com:service:OSInfo:1</serviceType>\r\n        <serviceId>urn:microsoft-com:serviceId:OSInfo1</serviceId>\r\n        <SCPDURL>/osinfo.xml</SCPDURL>\r\n        <controlURL>/upnp/control/ihikbymfdr/osinfo</controlURL>\r\n        <eventSubURL>/upnp/event/szowfkpdjr/osinfo</eventSubURL>\r\n      </service>\r\n    </serviceList>\r\n    <deviceList>\r\n      <device>\r\n        <deviceType>urn:schemas-upnp-org:device:WANDevice:1</deviceType>\r\n        <friendlyName>WAN Device</friendlyName>\r\n        <manufacturer>MikroTik</manufacturer>\r\n        <manufacturerURL>http://www.mikrotik.com/</manufacturerURL>\r\n        <modelName>Router OS</modelName>\r\n        <UDN>uuid:UUID-MIKROTIK-WAN-DEVICE-8SBP-3M48-3</UDN>\r\n        <serviceList>\r\n          <service>\r\n            <serviceType>urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1</serviceType>\r\n            <serviceId>urn:upnp-org:serviceId:WANCommonIFC1</serviceId>\r\n            <SCPDURL>/wancommonifc-3.xml</SCPDURL>\r\n            <controlURL>/upnp/control/djubzloglr/wancommonifc-3</controlURL>\r\n            <eventSubURL>/upnp/event/ttaegecslh/wancommonifc-3</eventSubURL>\r\n          </service>\r\n        </serviceList>\r\n        <deviceList>\r\n          <device>\r\n            <deviceType>urn:schemas-upnp-org:device:WANConnectionDevice:1</deviceType>\r\n            <friendlyName>WAN Connection Device</friendlyName>\r\n            <manufacturer>MikroTik</manufacturer>\r\n            <manufacturerURL>http://www.mikrotik.com/</manufacturerURL>\r\n            <modelName>Router OS</modelName>\r\n            <UDN>uuid:UUID-MIKROTIK-WAN-CONNECTION-DEVICE-8SBP-3M48-3</UDN>\r\n            <serviceList>\r\n              <service>\r\n                <serviceType>urn:schemas-upnp-org:service:WANIPConnection:1</serviceType>\r\n                <serviceId>urn:upnp-org:serviceId:WANIPConn1</serviceId>\r\n                <SCPDURL>/wanipconn-3.xml</SCPDURL>\r\n                <controlURL>/upnp/control/jdhzbmjqru/wanipconn-3</controlURL>\r\n                <eventSubURL>/upnp/event/hwedxfonnc/wanipconn-3</eventSubURL>\r\n              </service>\r\n            </serviceList>\r\n          </device>\r\n        </deviceList>\r\n      </device>\r\n    </deviceList>\r\n    <presentationURL>http://192.168.88.1/</presentationURL>\r\n  </device>\r\n  <URLBase>http://192.168.88.1:2828</URLBase>\r\n</root>\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Device details: service_type 'urn:schemas-upnp-org:service:WANIPConnection:1'; control_url 'http://192.168.88.1:2828/upnp/control/jdhzbmjqru/wanipconn-3'
03.03.2024 16:21:41 [Misc] UPnP: Added service to list
03.03.2024 16:21:41 [Misc] UPnP: Device search response: b'HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=3600\r\nEXT: \r\nLOCATION: http://192.168.88.1:2828/gateway.xml\r\nSERVER: RouterOS/6.49.8UPnP/1.0 MikroTik UPnP/1.0\r\nST: urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\nUSN: uuid:UUID-MIKROTIK-INTERNET-GATEWAY-DEVICE-8SBP-3M48::urn:schemas-upnp-org:device:InternetGatewayDevice:1\r\n\r\n'
03.03.2024 16:21:41 [Misc] UPnP: Device location was previously processed, ignoring
03.03.2024 16:21:42 [Misc] UPnP: 1 service(s) detected
03.03.2024 16:21:42 [Misc] UPnP: Trying to redirect external WAN port 2234 TCP => 192.168.88.231 port 2234 TCP
03.03.2024 16:21:42 [Misc] UPnP: Adding port mapping (192.168.88.231 2234, urn:schemas-upnp-org:service:WANIPConnection:1) at url 'http://192.168.88.1:2828/upnp/control/jdhzbmjqru/wanipconn-3'
03.03.2024 16:21:42 [Misc] UPnP: Add port mapping request headers: {'Host': '192.168.88.1:2828', 'Content-Type': 'text/xml; charset=utf-8', 'SOAPACTION': '"urn:schemas-upnp-org:service:WANIPConnection:1#AddPortMapping"'}
03.03.2024 16:21:42 [Misc] UPnP: Add port mapping request contents: b'<?xml version="1.0"?>\r\n<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:AddPortMapping xmlns:u="urn:schemas-upnp-org:service:WANIPConnection:1"><NewRemoteHost></NewRemoteHost><NewExternalPort>2234</NewExternalPort><NewProtocol>TCP</NewProtocol><NewInternalPort>2234</NewInternalPort><NewInternalClient>192.168.88.231</NewInternalClient><NewEnabled>1</NewEnabled><NewPortMappingDescription>NicotinePlus</NewPortMappingDescription><NewLeaseDuration>43200</NewLeaseDuration></u:AddPortMapping></s:Body></s:Envelope>\r\n'
03.03.2024 16:21:42 UPnP: Failed to forward external port 2234: HTTP Error 500: Internal Server Error
03.03.2024 16:21:42 [Misc] Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 562, in _add_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 168, in add_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 155, in _request_port_mapping
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 569, in _add_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 472, in add_port_mapping
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/portmapper.py", line 434, in _request_port_mapping
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 216, in urlopen
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 525, in open
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 634, in http_response
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 563, in error
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 496, in _call_chain
  File "C:/msys64/mingw64/lib/python3.11/urllib/request.py", line 643, in http_error_default
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
03.03.2024 16:21:42 1992 privileged users
03.03.2024 16:21:42 You have no Soulseek privileges. While privileges are active, your downloads will be queued ahead of those of non-privileged users.`

Note, that when I initially faced the bug, the network was on. For now, I can reproduce the issue only via the steps provided, it didn't occur just starting the app.

**Comment by 501NotImplemented** [comment] 2024-03-03 14:44
@slook I've put the corrupted files into a separate directory, added it to the shares and saved Nicorine configuration.
Share rescan started immediately.
03.03.2024 16:37:05 Rescanning shares…

I see scanning shares spinner in the app tray and it seems like the process is stuck. The Nicotine+ 3.3.3.dev1 is working for now.

Restarted the app.
03.03.2024 16:42:01 Rebuilding shares…
Same, scanning shares spinner spins, the process does not end. However, the app does not crash for now.

**Comment by slook** [comment] 2024-03-03 15:26
Alright, if and when it does finish please report the timestamp of the "Rebuild complete: X folders found" log message to establish the number of minutes that elapsed since the "03.03.2024 16:42:01 Rebuilding shares…" message, along with any other scanning errors printed into the log.

**Comment by 501NotImplemented** [comment] 2024-03-03 16:19
@slook the app crashed after some time of running in background.

After the restart:
03.03.2024 18:18:05 Rescanning shares…
03.03.2024 18:18:07 [Misc] Saved configuration: C:\Users\*****\AppData\Roaming\nicotine\config\config
03.03.2024 18:18:25 Rescan complete: 32243 folders found

**Comment by slook** [comment] 2024-03-03 16:21
> the app crashed

How did you realise this? Did it crash silently without error message?

**Comment by 501NotImplemented** [comment] 2024-03-03 16:23
@slook Yes, exactly. I've had it running in the background, went away from PC for some time after I returned - it wasn't running. Had to restart it manually.

**Comment by slook** [comment] 2024-03-03 16:33
Whilst the original "tuple index out of range IndexError" caused by the bug in 3.3.1 and 3.3.2 has been fixed in 3.3.3dev1, it appears that a further mitigation is ideally required, but there is a lack of any debug logging or other details to define this, and nobody else has reported a similar crash yet.

Please continue to report any further issues with the nightly unstable development builds , at link:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

Closing as resolved, at least the problem that leads to the original crash will be avoided.

**Comment by 501NotImplemented** [comment] 2024-03-07 10:35
@slook looks like this issue has to be reopened.

Nicotine+ Version: 3.3.3.dev2
GTK Version: 4.12.5
Python Version: 3.11.8 (win32)

Type: <class 'IndexError'>
Value: tuple index out of range
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 961, in on_process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 290, in process_thread_events
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 246, in emit
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 434, in _file_search_request_distributed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 687, in _process_search_request
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/search.py", line 473, in _create_file_info_list

That's the only log that is available, unfortunately.

**Comment by mathiascode** [comment] 2024-03-07 13:47
Could you send your .dbn files again?

I don't know what else to do at this point. None of the errors make any sense, and I haven't been able to reproduce any of them.

**Comment by 501NotImplemented** [comment] 2024-03-07 16:24
@mathiascode yes, please check your email.

**Comment by slook** [comment] 2024-04-01 16:02
Closing this as sadly there is nothing actionable we can do to identify what the quirk is on the affected machine which leads to the spurious errors thrown by the Python interpreter.

**Closed by slook** 2024-04-01 16:02 UTC

**Comment by slook** [comment] 2024-04-02 21:47
This issue isn't invalid because something useful did come out of this series of investigation since https://github.com/nicotine-plus/nicotine-plus/commit/e8b8a910582b1fd3b99e514b3c4e561c399e7bb1 avoids a potential for corruption of the shares database in the case of a fault.

**Comment by mathiascode** [comment] 2024-04-02 22:26
Fair enough.
