### ISSUE TITLE
critic error on 3.3.4

### ISSUE THREAD

**Issue by jps1990** [nicotine-plus/nicotine-plus#3080] opened 2024-08-12 02:25 UTC
Nicotine+ version:  
Operating System/Distribution:
win 11

### Describe the bug
critic error

### Additional context
Screenshots, logs, stacktraces or relevant information.

Nicotine+ Version: 3.3.4
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'MemoryError'>
Value: 
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2725, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2492, in _process_ready_sockets
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2433, in _process_ready_input_socket
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2606, in _read_data

**Comment by slook** [comment] 2024-08-12 08:58
Closing as duplicate of #3022 it is fixed in 3.3.5.dev3 please try it:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Closed by slook** 2024-08-12 08:58 UTC
Labels: bug, duplicate
