### ISSUE TITLE
Really varied upload speeds

### ISSUE THREAD

**Issue by Climbatiz** [nicotine-plus/nicotine-plus#2219] opened 2022-10-19 19:15 UTC
Nicotine+ version:  3.2.6rc3
Operating System/Distribution: Windows 10 Home

### Describe the bug
There is really varied upload speeds to users, it can jump from for example 50kb/s upto 10mb/s and it goes up and down all the time

### Expected behavior
i would expect speed to hold at a given rate instead of jumping up and down so much, at least not as much as it does

### Steps to reproduce the bug
...

### Additional context
as you can see here the speed is very varied, it is like this for all uploads
![Untitled](https://user-images.githubusercontent.com/39280509/196783007-81459e69-5044-4dbc-b664-0556312f35e0.png)

**Comment by slook** [comment] 2022-10-20 07:57
This is normal behaviour for the network. It is probable that many peers only dedicate a small portion of their total bandwidth to file transfers (in their Preferences > Downloads/Uploads > Speed Limits).

If you want a predicatable stable rate, then you can set your maximum upload speed. For example I have a slow 2 Mbps internet connection, so I have set my download and upload limits to "150 KiB/s", because at this setting it is still possible to navigate to a web page, even when somebody decides to get something from my machine at the same time.

If speed is wildly fluctuating during a given transfer, then this indicates that the peer is using their connection for something else, such as streaming video, updating their os or suchlike.

**Comment by Climbatiz** [comment] 2022-10-20 08:04
okie dokie, i would have expected speeds to hold at a certain speed as a norm (ftp or torrent uploads usually don't fluctuate this much), this happens to me with every person downloading from me, i have 1gbit upload so i don't really limit anything apart from number of upload slots in Nicotine

**Comment by slook** [comment] 2022-10-20 08:18
> torrent uploads usually don't fluctuate this much

The torrent protocol works by swarming multiple peers together and chunking data which has the effect of averaging out the speeds, whereas the slsk protocol only establishes a single file connection socket between two peers.

Nicotine+ is very old software, it was never designed with today's internet speeds in mind, and it uses simple methods for reading and writing data to/from disk in a lineear fashion, so it is not as performant as some FTP clients which make use of caching and buffering.

As files become larger, more numerous and connections get faster.it's possible that some improvements in this area might need to be made in the future.

**Comment by mathiascode** [comment] 2022-10-20 12:05
> Nicotine+ is very old software, it was never designed with today's internet speeds in mind, and it uses simple methods for reading and writing data to/from disk in a lineear fashion, so it is not as performant as some FTP clients which make use of caching and buffering.

I'm not quite sure what you mean by buffering in this case, but we do have a temporary buffer per connection for outgoing data.

It is expected that uploads complete slightly faster than the downloading peer receives all the data, but these kind of wildly fluctuating speeds seem abnormal. Ideally the speed should average out a few seconds into the upload.

> Some minor improvements and bug fixes in the transfers module have recently been made, please [test the latest build](https://nicotine-plus.org/doc/TESTING.html#windows) of Nicotine+ 3.2.6.rc4 to check everything is working as expected on your system. Please feel free to report any issues you encounter.

@Climbatiz When you test 3.2.6rc4, could you enable debug logs and send them to my email address (on my GitHub profile), so I can check if anything stands out?

To enable debug logs:
- Preferences -> Logging -> Log debug messages to file
- Menu -> View -> Show log history pane
- Right-click the log history pane -> Categories -> Enable "Connections", "Transfers", "Messages", "Miscellaneous"
- Once you've captured a few uploads in the log, right-click the log history pane -> Open log folder, to see the debug log file.

Remember to undo these steps once you're done, otherwise you will experience bad performance if there's a lot of logging going on.

**Comment by mathiascode** [comment] 2022-10-20 16:37
> asynchronous disk I/O, DMA or multi-core CPU model-specific optimizations.

Python doesn't support asynchronous disk I/O at least, so that's not something we can utilize at least. Anyway, this is unlikely to be relevant in this specific case, since we're only reading from disk.

What I suspect is happening is that the socket is marked as ready for receiving, accepts a larger amount of data at once, and becomes busy until the user has received everything on their end. It would be nice if we could avoid these bursts somehow, but I'm not sure how yet.

**Comment by mathiascode** [comment] 2022-10-20 17:20
I've set a socket buffer size limit in 46fa80f1577bf5293e80e705c89be763153025b3.

@Climbatiz A new test build will be available in about 20 minutes. Can you try it and see if the problem is fixed?
https://nicotine-plus.org/doc/TESTING.html#windows

**Comment by Climbatiz** [comment] 2022-10-20 18:39
yeah, it is still jumping all over the place, i also ran into troubles adding some multiple large discographies with odd naming and/or long dir/file path names and when rebuilding the shares would just hang forever, i wasn't sure which file or folder was giving the error so i just deleted it all

**Comment by mathiascode** [comment] 2022-10-20 18:59
> i also ran into troubles adding some multiple large discographies with odd naming and/or long dir/file path names and when rebuilding the shares would just hang forever, i wasn't sure which file or folder was giving the error so i just deleted it all

Can you create a separate issue for this?

**Comment by mathiascode** [comment] 2022-10-20 19:15
> yeah, it is still jumping all over the place

Is there any pattern? Does it go up for some time, drop, and start going up again?

**Comment by Climbatiz** [comment] 2022-10-20 19:39
it goes up to a point (possibly the users max dl) and drops down by 5-10x that speed and then up again and then down again, never really holding any specific or small variable of speeds

**Comment by slook** [comment] 2022-11-04 08:51
I can confirm this behaviour is observed with certain peers in my case. It makes me wonder if those peers are affected by some sort of ISP level traffic shaping or maybe it has something to do with their local network environment.

@Climbatiz have you tested this on a different ISP, for example if you have mobile broadband or some other different connection you can compare?

**Comment by slook** [comment] 2023-07-09 16:38
This is where the speed is calculated:

https://github.com/nicotine-plus/nicotine-plus/blob/2af4c0f9478bfcd63fce22615cc3dab7a0144e35/pynicotine/transfers.py#L1459

It might not be the right expression to take a `max` of either `1` or the time since `last_update`, if the updates are irregular in certain cases, this might cause the observed variation?

**Comment by slook** [comment] 2024-05-20 11:38
I think the issue presents itself when either one or both of the following conditions are true:
1. the receiving peer has set very low a speed limit set which is significantly less than the maximum possible speed of the established connection, and;
2. the remote peer has a significantly higher speed limit or no speed limit set.

Under extreme circumstances, the difference between fastest and slowest bursts of data is more than is divisible than the amount of data transmitted in under 1 second, resulting in wildly fluctuating values being displayed in the interface. That could either represent how the actual buffer is behaving, or it could be just an erroneous value displayed in the interface, not sure.

**Comment by slook** [comment] 2024-07-21 01:05
Since https://github.com/nicotine-plus/nicotine-plus/commit/1e1a667b7d7edb01ad7983c926a316d35459676f the Speed and Time Left values displayed now seem to be stunningly accurate.

**Comment by Climbatiz** [comment] 2024-07-21 15:44
> Since [1e1a667](https://github.com/nicotine-plus/nicotine-plus/commit/1e1a667b7d7edb01ad7983c926a316d35459676f) the Speed and Time Left values displayed now seem to be stunningly accurate.

is the client reading the disk more since this new build? in previous build i had uploaded 5TB network and the disk was read 1TB, now since getting the new build i'm at 300GB network and 100GB disk, maybe i need to wait a few more days to see if there's a difference

**Comment by slook** [comment] 2024-07-21 18:05
Thanks for testing.

Sorry I don't understand what you mean by the proportion of disk access verses total upload data. What is the source of that data where is it from the Statistics dialog? Please explain your concern using other words.

**Comment by Climbatiz** [comment] 2024-07-21 18:18
i dunno enough to know how it all works but i guess what i mean is "read/write cache", like reading data from memory versus reading the disk, at least what these stats tell me, it says it sent "380GB" in the network but read only "130GB" off the disk, i guess the rest of the data was from memory, or at least that's my understanding of how these things work

![Untitled](https://github.com/user-attachments/assets/f5eca1cc-bab0-469c-a1e3-92e7cf8ba2fd)

**Comment by slook** [comment] 2024-07-21 18:38
It is interesting, this is not a metric that I have considered before, since Linux doesn't really have such a user friendly Task Manager like Windows does that presents all the data in one place like that. I suppose this does illustrate that N+ really is a very busy little client indeed!

Of course the status bar indicators in Nicotine+ only includes the actual shared file transfers themselves and so it doesn't tell anything about the network overhead whatsoever.

**Comment by Climbatiz** [comment] 2024-07-21 18:46
yeah, i don't know enough about read/write cache vs direct r/w, the stats line up for Sent traffic, but i've recieved about 40MB more than i've downloaded today according to Process Explorer, and dispite downloading 90MB the write on the disk was only 50MB, but anyway, i'm just thinking about disk usage, i upload quite alot and off an SSD i recently bought and i'm just wondering how much disk usage i'm using since it is an SSD, but anyway, after some days when i've uploaded a couple of TB i'll know if there's a difference between latest test Nicotine verses what it was, but then again, i dunno what code has changed between releases

![Untitled](https://github.com/user-attachments/assets/eb574f0a-cf12-4c37-80f6-2630d9a3e429)

**Comment by slook** [comment] 2024-07-21 19:07
> reading data from memory versus reading the disk

Nicotine+ doesn't do any caching itself, every time a file needs to be is read then it is accessed from afresh by using standard calls to the operating system (which may or may not do some kind of caching of it's own accord but that is beyond the control of the application).

> i'm just wondering how much disk usage i'm using since it is an SSD

My understanding is that reading from an SSD doesn't cause that much wear, compared to writing that shortens the lifespan every time data is flashed onto it.

> i dunno what code has changed between releases

The entire codebase was refactored in version 3.3.0 and there were very significant changes in the way events are emitted between modules. The purpose of this is to enable the program to cope with modern demands on newer systems than it was originally designed for a couple of decades ago.

The current 3.3.x development cycle is focused on bug fixes and optimizations before new UI features will be added in 3.4.x onwards.

> i'll know if there's a difference between latest test Nicotine verses what it was

Please do keep us posted about your observations. Also, your general opinion about the behaviour/accuracy of the Speed, Time Elapsed and Time Left columns in the Downloads and Uploads tabs would be very much appreciated.

**Comment by Climbatiz** [comment] 2024-07-21 19:15
> Please do keep us posted about your observations. Also, your general opinion about the behaviour/accuracy of the Speed, Time Elapsed and Time Left columns in the Downloads and Uploads tabs would be very much appreciated.

i have noticed in latest 3.3.5dev1 release that the display of Speed/Time Left disappears and then reapeears in this version, i don't recall it happening in previous build

as for transfer speeds, they still fluctuate but at least not at an unusual amount,  guess that just normal, i see speeds like that fluctuate on my ftpd too and i guess my torrent client has just coded its application to not look like it fluctuates much

**Comment by slook** [comment] 2024-07-21 19:54
> the display of Speed/Time Left disappears and then reapeears in this version, i don't recall it happening in previous build

The field is blanked at moments when the values cannot be calculated or are nothing. Technically I suppose this should indicate infinity if it is going to take forever, but in reality it is unlikely that it will never finish.

> coded its application to not look like it fluctuates much

The standard practice seems to be to interpolate an average of the last several values, but that type of method involves a performance and resource penalty of storing many historic data.

However it might be viable at least to make an average out of two values (i.e. the previous and new value) without having to store anything, but nothing like this is currently implemented. The raw value is simply displayed directly from the core protocol handler module.

In a way it is nice for us to see exactly what is happening in the core, but in the long run a smoothed value could be more useful to an end user.

> as for the initial post bug, i don't see it happening at least with the uploads currently visible in my client, so i presume that has been fixed

It is mostly fixed in principle, but you are the first to test this out in the wild. Further refinements will probably be added.

**Comment by Climbatiz** [comment] 2024-07-21 19:58
> The standard practice seems to be to interpolate an average of the last several values, but that type of method involves a performance and resource penalty of storing many historic data.

can't it store the last 1 minute of speeds and present an average, like allowing the user to see both "current speed" and "average speed"

**Comment by slook** [comment] 2024-07-21 20:21
It could do that but I don't think the complexity would be warranted nor desirable, because it might make the interface appear to be unresponsive to changing network conditions.

When the transfer is finished then an average speed of the entire active time is displayed, and is also sent to the server for the 'Upload Speed' stat. This differs from the old behaviour, which only used the last current speed value.

**Comment by Climbatiz** [comment] 2024-07-21 20:34
> When the transfer is finished then an average speed of the entire active time is displayed

ah ok, then a current avg speed is not really that necessary

> The field is blanked at moments when the values cannot be calculated or are nothing

it would i think be better to just show last known value if the calculation can't be shown immedietly, as seeing the values blink in and out is a bit irritating, makes reading the values kinda hard

**Comment by mathiascode** [comment] 2024-07-23 09:15
Two approaches on the top of my head:
- Always calculate the average speed every second
- Freeze the last speed/time left until the next send happens

Regarding network traffic, keep in mind that the Soulseek network does more than just transfer files. Searching and browsing files, chats, and just receiving and sending search results on the distributed network use some bandwidth over time.

**Comment by mathiascode** [comment] 2024-07-23 09:40
I tried the first approach, seems to work well. I'll push it to master soon so you can see how it feels.

**Comment by slook** [comment] 2024-07-23 11:10
> Always calculate the average speed every second, based on amount transferred and elapsed time (maybe this is expected from other file transfer programs?)

Not really, because for larger transfers the average speed becomes less relevant as time goes on, so it is expected to observe the current performance that is happening right now in real time to present a live analysis of any fluctuations in network conditions.

The same goes for estimated time left, which of course needs to be based on the current speed, since the historic performance only remains relevant for a few seconds at most when determining what the approximate speed/eta is likely to be in the future.

**Comment by slook** [comment] 2024-07-23 18:17
https://github.com/nicotine-plus/nicotine-plus/commit/1f63cfd93018014c888949bcbba1db98d05b5616 is a good idea, to usually display the current speed and fallback to the average speed if the current speed is incalculable, that does seem to work well.

However I defer to @Climbatiz to test if we should settle on this solution or if more interpolation is required?

https://nicotine-plus.org/doc/TESTING.html

**Comment by slook** [comment] 2024-07-23 19:40
@mathiascode Finished upload displays `0:01` Time Left...

![image](https://github.com/user-attachments/assets/245d18f0-cd88-442f-8aa0-8f7c1cba35ac)

**Comment by Climbatiz** [comment] 2024-07-23 23:22
i updated to the latest release, although i haven't tested out looking at the screen very much but after afk'ing a bit and coming back to puter it seems Nicotine crashed and left me with these bug reports, dunno what happened as i wasn't on the puter, i suppose i'm suppost to post these elsewhere, but i'll just do it here: (oh and the screens were frozen and i couldn't copy the text, so i'll just post a screenshot of how it looked

![Untitled](https://github.com/user-attachments/assets/560351c5-15fd-4355-b198-2bc32b6d25ad)

**Comment by slook** [comment] 2024-07-23 23:31
None of those seem relevant to the origin of the crash, there must have been another Critical Error dialog stacked behind.

**Comment by Climbatiz** [comment] 2024-07-24 09:58
welll... after relogging, the program hasn't crashed again for about 10hrs now, so whatever crashed it before i don't know what it was

however as to the new build's transfer information there is one thing i've noticed that is a minor bug, which is a transfer some1 has i guess cancelled or something but these transfers will go from a state of "queued" then "transferring" and then "cancelled" and it'll do this 3 times or so and finally just ending up as "cancelled", this is not the bug though, although it is irritating that this happens as every time i clear finished and cancelled transfers this person will do this process again sometime later anyways, i dunno if you guys are aware of that perticular thing but anyways, the thing that happens now cuz of the new transfer code is it'll say like "x gb/s" transfer speed if the person had cancelled the dl after getting some of the data, i guess it says that cuz of the 3 stages i mentioned before, one of them being "transferring", so nicotine currently will think that the previously downloaded data was downloaded in 1 sec and say like "3 gb/s" if the person had already downloaded 3gb of the file

i dunno how you would fix this considering the client goes through a state of "transfer" but immedietly goes next to "cancelled", whatever causes those things to happen, could be some SoulseekQT does or i dunno

anyways, here's a screeny with the thing being shown, although i think i described it to death hehe
![Untitled](https://github.com/user-attachments/assets/d8792886-7d3f-4a50-a62b-7e9d329ba895)

**Comment by Climbatiz** [comment] 2024-07-24 15:32
so i noticed in my system tray icon that Nicotine was disconnected, ie. red circle, and so opened it up and a critical error was up

Nicotine+ Version: 3.3.5.dev2
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'login_status'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 370, in on_window_active_changed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 1042, in on_cancel_auto_away
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 1022, in set_auto_away
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 1026, in create_away_timer

**Comment by slook** [comment] 2024-07-24 16:02
The Critical Error dialog isn't always very helpful, more often than not an error involving a 'NoneType' object will occur as a result of a preceding crash, so it is necessary to check if there are any other popup dialogs stacked underneath before quitting.

**Comment by Climbatiz** [comment] 2024-07-25 07:45
i got the error again, but i haven't updated if there's a new build, i'll check that now, but here's what it said with anything that was underneath:

Nicotine+ Version: 3.3.5.dev2
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'KeyError'>
Value: 'trayicon'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/mainwindow.py", line 375, in on_window_visible_changed
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/trayicon.py", line 1161, in update
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/trayicon.py", line 176, in update

Nicotine+ Version: 3.3.5.dev2
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'send'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2718, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2704, in _loop
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2513, in _process_ready_sockets
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2489, in _process_ready_output_socket
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2653, in _write_data

**Comment by mathiascode** [comment] 2024-07-25 11:47
The large upload speed and crash should be fixed now.

Regarding the state change issue, could you [enable debug logging](https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging) (all categories), capture the behavior in the logs, and send the logs to my email (on my GitHub profile). Please also mention the users and files affected in the email.

**Comment by mathiascode** [comment] 2024-07-26 15:11
Thanks, I got you email. It looks like typical behavior from a Soulseek client that either ran out of disk space, or has download folders configured incorrectly (retries three times before giving up, every 10 minutes). Any luck messaging the user asking what's going on on their end?

**Comment by Climbatiz** [comment] 2024-07-27 00:01
> Thanks, I got you email. It looks like typical behavior from a Soulseek client that either ran out of disk space, or has download folders configured incorrectly (retries three times before giving up, every 10 minutes). Any luck messaging the user asking what's going on on their end?

i'll ask those who it happens with from now on, i've thought of possible reasons, out of space. lengthy dir+name bug or just fat32 or similar and doesn't support 4GB+ files, i've seen this happen all kinds of ways, they might even dl some of the file and then just suddenly stop for whatever reason, in any case, i'll msg the user from now on, trouble is getting a reply, i've tried today asking 3 ppl but none have responded back ; /

**Comment by mathiascode** [comment] 2024-08-01 19:45
In any case, doesn't look like an issue in Nicotine+.

Anything left to do to fix the original issue, or can it be closed?

**Comment by Climbatiz** [comment] 2024-08-02 09:27
i had some crash the other day but everything has been running smoothly, however i did notice this yesterday that my "total" upload stats that used to say like 150TB now says whatever insanely high byte that is ; / gonna have to reset my stats ; /

![Untitled](https://github.com/user-attachments/assets/99ca3617-a515-48b1-b142-112153a47a08)

**Comment by slook** [comment] 2024-08-03 10:24
Perhaps the discrepancy occurred as a result of the crashes you experienced while testing the development builds. Hopefully it won't occur in the stable branch from now on.

> Anything left to do to fix the original issue, or can it be closed?

The nature of the speed fluctuations/bursts are more accurately displayed now, albeit the original issue as reported does still seem to exist in certain scenarios. I suggest we close this issue in favour of issue https://github.com/nicotine-plus/nicotine-plus/issues/3033 to follow this up.

**Comment by mathiascode** [comment] 2024-08-07 12:43
> i had some crash the other day but everything has been running smoothly, however i did notice this yesterday that my "total" upload stats that used to say like 150TB now says whatever insanely high byte that is ; / gonna have to reset my stats ; /

Might've been a fallout in older builds when changes were still being made to the code. Please try the latest build for some time and let us know if the issue happens again.

> I suggest we close this issue in favour of issue #3033 to follow this up.

Sure.

**Closed by mathiascode** 2024-08-07 12:43 UTC
Labels: enhancement
