### ISSUE TITLE
Critical error after run and open Preferences->Network

### ISSUE THREAD

**Issue by uniss2209** [nicotine-plus/nicotine-plus#1844] opened 2022-01-22 13:48 UTC
Nicotine+ version:  3.2.0 portable
Operating System/Distribution: Windows 11

### Steps to reproduce the bug
After run open Preferences->Network

### Additional context
Nicotine+ Version: 3.2.0
GTK Version: 3.24.30
Python Version: 3.9.7 (default, Nov 21 2021, 22:02:56)  [GCC 11.2.0 64 bit (AMD64)]

Type: <class 'AttributeError'>
Value: 'NoneType' object has no attribute 'listenport'
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/dialogs/preferences.py", line 3202, in on_switch_page
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/dialogs/preferences.py", line 93, in set_settings

**Comment by mathiascode** [comment] 2022-01-22 15:17
I suppose this is a consequence of https://github.com/nicotine-plus/nicotine-plus/issues/1843 (Nicotine+ not starting completely).

**Comment by uniss2209** [comment] 2022-01-22 16:16
Yes, this time the program was started from the network drive without error, but when I tried to enter the Preferences, it crashed with this bug report.

**Comment by slook** [comment] 2022-01-22 19:05
How is the `D:/a/` drive mapping derived? I'd imagine this is not a mapped drive on your system?

While this is an interesting observation, this sort of behaviour is to be expected, since Windows doesn't allow the execution of binary programs for normal system users. Do you have a specific use case for running the portable exe over the network @uniss2209 ?

**Comment by uniss2209** [comment] 2022-01-23 09:35
The archive with portable version was unpacked to \\192.168.1.250\install\multimedia\p2p\Nicotine+ and exe was launched from there. 
> specific use case
I always do this with portable programs - it's so convenient for me. I can't do that with Nicotine+. OK, no problem.

**Comment by slook** [comment] 2022-01-24 02:16
Yes it does somewhat defeat the purpose of a portable application package if it cannot be run from any convenient location. On Windows this can be pot luck, depending upon how the GPO is configured on any given system.

I suggest closing this issue in favor of #1843

**Comment by uniss2209** [comment] 2022-01-24 08:06
Well, if trying to make an application work from a network drive takes a lot of time with no guarantee of success, close it (like #1843, by the way).

**Comment by slook** [comment] 2022-01-24 11:47
It doesn't matter how much time it takes to resolve an issue if the outcome is worthwhile, and since your bug reports raise a valid concern then at least one of the related issues should remain open, even if the bug cannot be fixed any time soon.

The main barrier to success is not knowing exactly what the problem is, it could turn out to be something quick and simple, or it could be very complex. I suspect that there is some strange permissions issue whereby the Nicotine+ executable is needlessly causing the Python multiprocessor to elevate, but I am far from certain of this nor how such behaviour can be avoided.

Either way, stable Windows support is important and so more testing is needed.

**Comment by mathiascode** [comment] 2022-01-27 00:22
Closing in favor of https://github.com/nicotine-plus/nicotine-plus/issues/1843

**Closed by mathiascode** 2022-01-27 00:22 UTC
Labels: bug
