### ISSUE TITLE
Crash while running on background

### ISSUE THREAD

**Issue by aburone** [nicotine-plus/nicotine-plus#3130] opened 2024-09-15 04:42 UTC
Nicotine+ version:  3.3.4
Operating System/Distribution: windows

### Describe the bug

Nicotine+ Version: 3.3.4
GTK Version: 4.14.3
Python Version: 3.11.9 (win32)

Type: <class 'MemoryError'>
Value: 
Traceback:   File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2725, in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2492, in _process_ready_sockets
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2433, in _process_ready_input_socket
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2606, in _read_data

### Expected behavior
Not to crash

### Steps to reproduce the bug
Set The program to run on background, after some minutes it'll crash randomly

**Comment by slook** [comment] 2024-09-15 09:30
Closing as duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/3022 it is fixed in 3.3.5.rc1 please try it:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows

**Closed by slook** 2024-09-15 09:30 UTC
Labels: bug, duplicate
