### ISSUE TITLE
"Finish Uploads and Quit" option

### ISSUE THREAD

**Issue by ewauq** [nicotine-plus/nicotine-plus#1454] opened 2021-07-17 22:26 UTC
As mentioned in this [reddit thread](https://www.reddit.com/r/Soulseek/comments/ckdvos/finish_uploads_and_quit/), on the default Soulseek client, you can enable an option called "Finish Uploads and Quit". It waits to finish your current upload and then quit the client.

This is very convenient especially when you want to give the courtesy to your current downloads to finish rather than cut them off abruptly. I usually have to set a shutdown countdown on my computer to give them this possibility, but this is not really reliable.

Even better, we can imagine two options:
- Finish Uploads and Quit the client
- Finish Uploads and Shutdown the computer (which is way better in my use case)

https://www.reddit.com/r/Soulseek/comments/doitz1/what_does_remote_pending_shutdown_mean/
https://www.reddit.com/r/Soulseek/comments/ckdvos/finish_uploads_and_quit/

**Comment by mathiascode** [comment] 2021-07-17 23:39
Closing as duplicate of #885.

**Closed by mathiascode** 2021-07-17 23:39 UTC
Labels: enhancement
