### ISSUE TITLE
[3.3.0.dev5] Nicotine silently crashes/exits when disconnecting external monitor

### ISSUE THREAD

**Issue by Latecomerr** [nicotine-plus/nicotine-plus#2627] opened 2023-08-26 12:40 UTC
Nicotine+ version: 3.3.0.dev5
Operating System/Distribution: Win10x64

### Describe the bug
After ~~an indeterminate amount of time~~ *disconnecting a previously connected external monitor*, Nicotine silently crashes or exits. It disappears from the task bar and the quickbar icon disappears on hover

### Expected behavior
The program remains open unless the user decides otherwise

### Steps to reproduce the bug
Launch the program and ~~let it do its thing for an indeterminate amount of time~~ *disconnect a previously connected external monitor*

### Additional context
Screenshots, logs, stacktraces or relevant information.
I have no idea where the logs are, just let me know where I can get the info you need and I'll provide it  
That said, this is a huge issue since my main m.o. is to leave Slsk running for weeks and just rely on wishlist searches. Given that this is the second time this week that this happened, I'll continue using QT like before

**Comment by slook** [comment] 2023-08-27 06:27
Have you had the same issue also occur with [the current stable version of Nicotine+ 3.2.9 for Windows](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#windows)?

**Comment by mathiascode** [comment] 2023-08-28 15:59
Once I'm home, I'll prepare a special build of Nicotine+ that you can run in the console/terminal. The console output should hopefully provide some insight into the issue.

**Comment by mathiascode** [comment] 2023-08-29 20:30
Try the windows-*-package build at the bottom of this page: https://github.com/mathiascode/nicotine-plus/actions/runs/6016923293

In case you don't know how to run it in the console: extract the zip, navigate to the `Nicotine+\` subfolder the extracted folder, type `cmd` in the Windows Explorer path bar, and run `Nicotine+.exe`.

Once Nicotine+ starts, enable debug logging (all categories, see instructions here: https://nicotine-plus.org/doc/DEVELOPING.html#debug-logging). When Nicotine+ crashes, copy the crash message and a few lines of log output above it (remove any sensitive information such as usernames and IP addresses).

**Comment by Latecomerr** [comment] 2023-08-30 01:29
```
Windows fatal exception: access violation

Thread 0x00002870 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2624 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x0000359c (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 82 in _handle_prompt
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 44 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x0000b17c (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 324 in _run_scheduler
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 975 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Current thread 0x000061e4 (most recent call first):
  File "C:/msys64/mingw64/lib/python3.11/site-packages/gi/overrides/Gio.py", line 42 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 101 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 106 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 211 in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 38 in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/initscripts/console.py", line 16 in run
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 124 in run
```

**Comment by Latecomerr** [comment] 2023-08-30 11:01
>and a few lines of log output above it

The logs were completely uninteresting, simply a lot of `attempt to allocate GtkBox box 000001da59f0ed70 with width 1 and height -46` caused by minimizing the window

**Comment by mathiascode** [comment] 2023-09-02 18:25
I haven't been able to reproduce the issue yet, but I have some questions to hopefully narrow this down a bit:
- Are you uploading or downloading anything when the crash happens?
- Have you joined any chatrooms?
- Do you have any items in your wishlist?
- Does Nicotine+ crash when you're disconnected from the server (Menu -> Disconnect)?
- Are you able to reproduce the issue with a fresh installation/config (completing the Setup Assistant and letting Nicotine+ run)?

**Comment by Latecomerr** [comment] 2023-09-02 18:28
> * Are you uploading or downloading anything when the crash happens?

I don't think so. At least nothing that I have initiated.

> * Have you joined any chatrooms?

I don't think so. Not intentionally at least.

> * Do you have any items in your wishlist?

Yes, many.

> * Does Nicotine+ crash when you're disconnected from the server (Menu -> Disconnect)?

No idea.

> * Are you able to reproduce the issue with a fresh installation/config (completing the Setup Assistant and letting Nicotine+ run)?

I can try! I'll delete my config file (after backing it up) and do the setup assistant and let it do its thing

**Comment by mathiascode** [comment] 2023-09-02 19:37
Thanks! Another thing I remembered is that a notification bubble appears when new wishlist results are found. It could also be worth checking if those are causing issues.

The easiest way to test this would probably be to temporarily join one of the popular rooms (e.g. nicotine), and enable chatroom notifications in Preferences -> User Interface.

**Comment by Latecomerr** [comment] 2023-09-02 21:26
> Thanks! Another thing I remembered is that a notification bubble appears when new wishlist results are found. It could also be worth checking if those are causing issues.
> 
> The easiest way to test this would probably be to temporarily join one of the popular rooms (e.g. nicotine), and enable chatroom notifications in Preferences -> User Interface.

Just did this, no issues whatsoever.  
For what it's worth, the Nicotine crash that I logged happened around 1 AM UTC

**Comment by Latecomerr** [comment] 2023-09-02 21:49
Here's what I'll do, I'll take the newly made config file, but migrate entries that I feel are safe from the old one, and then leave that running

**Comment by mathiascode** [comment] 2023-09-02 22:16
Sure.

> The logs were completely uninteresting, simply a lot of `attempt to allocate GtkBox box 000001da59f0ed70 with width 1 and height -46` caused by minimizing the window

This looks like https://gitlab.gnome.org/GNOME/gtk/-/issues/5724

**Comment by Latecomerr** [comment] 2023-09-02 22:49
```
Windows fatal exception: access violation

Thread 0x000054d8 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2624 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00009948 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 82 in _handle_prompt
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/cli.py", line 44 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00005740 (most recent call first):
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/events.py", line 324 in _run_scheduler
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 975 in run
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "C:/msys64/mingw64/lib/python3.11/threading.py", line 995 in _bootstrap

Current thread 0x000014a0 (most recent call first):
  File "C:/msys64/mingw64/lib/python3.11/site-packages/gi/overrides/Gio.py", line 42 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 101 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/gtkgui/__init__.py", line 106 in run
  File "D:/a/nicotine-plus/nicotine-plus/pynicotine/__init__.py", line 211 in run
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 34 in load_module
  File "D:/a/nicotine-plus/nicotine-plus/nicotine", line 38 in <module>
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/initscripts/console.py", line 16 in run
  File "C:/msys64/mingw64/lib/python3.11/site-packages/cx_Freeze/initscripts/__startup__.py", line 124 in run
```
Program just died the moment I unplugged an external monitor

**Comment by mathiascode** [comment] 2023-09-02 23:02
Good catch, I can confirm Nicotine+ crashes when I unplug an external monitor. Seems like a GTK 4 bug, GTK 3 is not affected.

**Comment by mathiascode** [comment] 2023-09-03 00:39
Reported upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/6080

**Comment by Latecomerr** [comment] 2023-09-03 06:03
I think, unless something else happens, this might actually be the "unpredictable" cause of my initial report because I was just not expecting monitor unplugs to kill applications

I'll keep launching in a cmd window and seeing if something else happens

**Comment by slook** [comment] 2023-09-03 07:04
It might be triggered not only by unplugging the monitor, but also by power saving and other events.

Perhaps there might also be some events logged about it in the Windows Event Viewer.

**Comment by Latecomerr** [comment] 2023-09-03 07:22
> It might be triggered not only by unplugging the monitor, but also by power saving and other events.
> 
> Perhaps there might also be some events logged about it in the Windows Event Viewer.

Feel free to let me know what exactly I'm supposed to click and report in the event viewer and I'll provide relevant things if they're there

**Comment by slook** [comment] 2023-09-03 07:41
Not sure exactly. It will just be any relevant looking Warning or Information system/application events with timestamps that coincide with when the crash occurs. There may of course be none.

**Comment by Latecomerr** [comment] 2023-09-03 11:49
Error
> \lib\libgobject-2.0-0.dll, Version: 2.76.4.0, exception code 0xc0000005

2 seconds later, APPCRASH and error  
> \lib\libgobject-2.0-0.dll, Version: 2.76.4.0, exception code 0xc000041d

1 second later, APPCRASH

**Comment by Latecomerr** [comment] 2023-09-08 09:59
@slook @mathiascode I've set up that one build with console output on another laptop that I don't connect to any external screens and it's been running smoothly so far. Also, on the other machine, it survived several power events such as hibernation and standby modes.

So far the only thing that I know that has caused Nicotine to silently crash is external monitor disconnection, nothing else has caused a dent, so I believe I can stop investigating.

**Comment by mathiascode** [comment] 2023-09-19 18:25
A fix will be available soon: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6412

**Comment by mathiascode** [comment] 2023-09-30 23:40
Should be fixed in the latest development build.

**Closed by mathiascode** 2023-09-30 23:40 UTC
Labels: bug
