### ISSUE TITLE
Gtk:ERROR:../gtk/gtk/deprecated/gtktreeview.c:12838:gtk_tree_view_is_blank_at_pos: code should not be reached

### ISSUE THREAD

**Issue by flyingfishflash** [nicotine-plus/nicotine-plus#2665] opened 2023-09-25 00:05 UTC
Nicotine+ version:  3.3.0.dev.5
Operating System/Distribution: Arch Linux

### Describe the bug
```
[2023-09-24 19:55:30] Loading Python 3.11.5
[2023-09-24 19:55:30] Loading Nicotine+ 3.3.0.dev5
[2023-09-24 19:55:30] Loading GTK 4.12.2
[2023-09-24 19:55:30] Loading plugin system
[2023-09-24 19:55:30] Loaded plugin Nicotine+ Commands
[2023-09-24 19:55:31] Listening on port: 30589
[2023-09-24 19:55:31] Connecting to server.slsknet.org:2242
[2023-09-24 19:55:31] Connected to server server.slsknet.org:2242, logging in…
[2023-09-24 19:55:31] 1767 folders found before rescan
[2023-09-24 19:55:31] Rescanning shares…
[2023-09-24 19:55:32] Rescan complete: 1767 folders found
[2023-09-24 19:55:33] UPnP: Failed to forward external port 30589: No UPnP devices found
[2023-09-24 19:55:33] 1896 privileged users
[2023-09-24 19:55:33] You have no Soulseek privileges. While privileges are active, your downloads will be queued ahead of those of non-privileged users.

(org.nicotine_plus.Nicotine:209198): Gdk-WARNING **: 19:55:50.885: Compositor doesn't support moving popups, relying on remapping
**
Gtk:ERROR:../gtk/gtk/deprecated/gtktreeview.c:12838:gtk_tree_view_is_blank_at_pos: code should not be reached
Bail out! Gtk:ERROR:../gtk/gtk/deprecated/gtktreeview.c:12838:gtk_tree_view_is_blank_at_pos: code should not be reached
Fatal Python error: Aborted

Thread 0x00007f408c9fe6c0 (most recent call first):
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2624 in run
  File "/usr/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007f408d1ff6c0 (most recent call first):
  File "/usr/lib/python3.11/site-packages/pynicotine/cli.py", line 90 in _handle_prompt
  File "/usr/lib/python3.11/site-packages/pynicotine/cli.py", line 52 in run
  File "/usr/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/lib/python3.11/threading.py", line 995 in _bootstrap

Thread 0x00007f40993bf6c0 (most recent call first):
  File "/usr/lib/python3.11/site-packages/pynicotine/events.py", line 325 in _run_scheduler
  File "/usr/lib/python3.11/threading.py", line 975 in run
  File "/usr/lib/python3.11/threading.py", line 1038 in _bootstrap_inner
  File "/usr/lib/python3.11/threading.py", line 995 in _bootstrap

Current thread 0x00007f409a62d740 (most recent call first):
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/widgets/treeview.py", line 696 in on_tooltip
  File "/usr/lib/python3.11/site-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/application.py", line 101 in run
  File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/__init__.py", line 106 in run
  File "/usr/lib/python3.11/site-packages/pynicotine/__init__.py", line 211 in run
  File "/usr/bin/nicotine", line 34 in load_module
  File "/usr/bin/nicotine", line 38 in <module>

Extension modules: gi._gi, cairo._cairo, gi._gi_cairo (total: 3)
Aborted (core dumped)
```

### Additional context

Maybe this should be part of #2014 ?  I'm using wayland/sway. I hadn't used nicotine in quite awhile so I'm not sure what may have prompted it. But it's pretty much unusable unless there's a workaround, as it crashes on any pane that's populated (Search/Upload/Download).

Let me know if you need more information.

**Comment by flyingfishflash** [comment] 2023-09-25 00:14
Maybe upstream GTK issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/6114

**Comment by mathiascode** [comment] 2023-09-25 00:31
Thank you for your bug report. This is a duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2663

I've since reported the issue upstream and added a workaround in Nicotine+. Please update to the latest development version of Nicotine+.

**Closed by mathiascode** 2023-09-25 00:31 UTC
Labels: bug
