### ISSUE TITLE
Having several issues getting all my files to share, or share correctly

### ISSUE THREAD

**Issue by woollarding** [nicotine-plus/nicotine-plus#1686] opened 2021-11-10 15:36 UTC
Nicotine+ version:  3.1.1

Operating System/Distribution: Windows 11

### Describe the bug
The first problem I have is that some sub-folders are shared on the same level as their root folder when viewed with soulseekQT but not with nicotine .. if that makes sense, if not have a screen shots. I also have some other issues with some folders showing up as empty even though there are files in them, and I think that is both on nicotine and QT. Also there is the problem that I think may have been addressed already where file names that are too long or something will give an error.. I did try to uninstall and reinstall, but it seems to have saved some of the settings as my queue and info are still intact.. is there something else I need to do to fully remove at least the share settings? any help is appreciated. 

### Expected behavior
To be able to share files and have them configured correctly or in some cases show up at all. 

### Steps to reproduce the bug
browse my nicotine share with a QT client 

### Additional context
<img width="960" alt="share on nicotine" src="https://user-images.githubusercontent.com/73700658/141143396-55627653-5b50-49a8-8dd1-7434370c1c58.png">
<img width="960" alt="share on QT" src="https://user-images.githubusercontent.com/73700658/141143404-affc7ff7-e79d-45dd-bcc1-24bf1a3605e2.png">
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment] 2021-11-11 00:35
> is there something else I need to do to fully remove at least the share settings?

Delete all the files/folders ending in `*.db` in your `./nicotine` user profile directory. This will force a rebuild of your shares from scratch. If you delete your whole profile then Nicotine+ will go to factory defaults.

> there is the problem that I think may have been addressed already where file names that are too long or something will give an error..

There have been several improvements to the handling of these issues with share scanner in 3.2.0.dev1. If possible please verify that the problem you are having is resolved in the [Unstable](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#unstable) branch, because Nicotine+ 3.2.0 will be released soon.

However there are some unrelated issues with PyInstaller that is currently blocking master release to Stable, and may prevent you from installing the Unstable package. Apparently the [32-bit Unstable package](https://nightly.link/nicotine-plus/nicotine-plus/workflows/packaging/master/windows-i686-package.zip) is easier to install on Windows 10 at the moment, we haven't tested 11 yet, so this would be appreciated if you are able to test this @woollarding.

**Comment by woollarding** [comment] 2021-11-11 01:16
Thanks for the information. I tried deleting the .db files I could find and then rescanned the share, same result. I tried to install the 32-bit dev version and got 'failed to execute script nicotine' which is what the 64-bit version said as well. Ill try to reset to defaults tomorrow and report back.

**Comment by slook** [comment] 2021-11-11 01:51
> I tried to install the 32-bit dev version and got 'failed to execute script nicotine' which is what the 64-bit version said as well.

Thank you for confirming that https://github.com/nicotine-plus/nicotine-plus/issues/1665 is also affecting Windows 11, I feared that this was going to be case. A fix for this startup error is in progress #1639 will hopefully address that issue soon.

> Ill try to reset to defaults tomorrow and report back.

It's not worth doing that until you can run Unstable, because it's unlikely to fix your missing shared folders in Nicotine+ 3.1.1. Even if it does there's no guarantee that you will not encounter the same bug further down the line, although having said that I suppose it might be interesting to know if the problem arises from the outset or if it's something that occurs later.

**Comment by mathiascode** [comment] 2021-11-11 14:48
Could you send me the .db files privately (to my e-mail on my GH profile)?

**Comment by woollarding** [comment] 2021-11-11 16:03
I sent you the .db files, if you don't get them please let me know.

**Comment by mathiascode** [comment] 2021-11-11 20:21
Thanks, I received them. I'll investigate why the folders appear like this in SlskQt.

> Also there is the problem that I think may have been addressed already where file names that are too long or something will give an error

I almost have a working fix for this, but it will probably not be included in the near future. I want to ensure it works properly without breaking stuff like network shares.

**Comment by mathiascode** [comment] 2021-11-13 21:50
The unstable Windows builds are working again. Could you install the latest one, remove the db files and rescan, and see if anything has changed?

**Comment by woollarding** [comment] 2021-11-13 22:26
I installed the 64bit version of the dev client on windows 11 and it's
working so far, side note: I like the debug categories in the right click..
the indexing reported a new error for many files that i have not seen yet..

*[Misc] Ignoring invalid metadata for file*
And it looks like this is going to take a while, so depending on how long
it is, it may be tomorrow before I report the results. Once again I really
appreciate all the effort going into this thing.

**Comment by mathiascode** [comment] 2021-11-13 22:52
Glad to hear it's working on Windows 11. The "Ignoring invalid metadata for file" checks were added in 3.2.0 (the metadata parsing library isn't perfect).

You're welcome, thank you for reporting the issue. :) There are so many large shares with odd files out there that it's difficult to test.

**Comment by woollarding** [comment] 2021-11-13 23:07
ok so list is done, it's still the same as it was heh but i'm glad i can
check out the newest version. if there's anything i can do to assist please
do not hesitate to ask, unfortunately my free time is about all i can offer
as i have almost no practical skills..

**Comment by mathiascode** [comment] 2021-11-13 23:14
In that case, I think this is a bug in SoulseekQt. Nicotine+ and Soulseek NS display the share without issues.

Does SoulseekQt scan and display your share without issues?

**Comment by woollarding** [comment] 2021-11-13 23:43
when i share everything on QT it displays correctly when i get my own list
there (other than the folder i am aware of that has files inside but they
don't show up in share) there are no weird folders out of place that i can
see. also when i look at the QT share from nicotine, the empty folder is
also the only issue i can see.

**Comment by mathiascode** [comment] 2021-11-13 23:47
Could you browse the SoulseekQt user in Nicotine+, save the shares list to disk, and send the file to me (located in ~/.local/share/nicotine/usershares/)? I'd like to compare it with the one generated from the Nicotine+ scanner.

**Comment by woollarding** [comment] 2021-11-14 00:02
sent to the other email. i should mention its been a really long time since
i shared this much on QT, and when i try to close it, it isn't closing. i
will keep it going for a while to see if i am just impatient.. but thought
i would mention that as it wasn't a thing i noticed before

**Comment by mathiascode** [comment] 2021-11-14 00:36
https://github.com/nicotine-plus/nicotine-plus/commit/3fb4d3239d9f0a1325ce9e8f64a099fa5ac646ae should fix the issue with folders appearing at root level in SoulseekQt.

**Comment by mathiascode** [comment] 2021-11-14 01:02
https://github.com/nicotine-plus/nicotine-plus/commit/b6dfe728819eb083fae9d399453f4ec8e25256cc fixes an issue where the rest of the folder wasn't scanned after failing to scan a file in it.

**Comment by woollarding** [comment] 2021-11-14 01:09
Can I download those files from the website and replace the current ones
with them? Or should I just wait for an updated version?

**Comment by slook** [comment] 2021-11-14 01:53
Those are commit references for the repo, they're of no use to you @woollarding 

Just re-download and install from [Unstable installer packages](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows) are generated a short time after every commit.

**Comment by woollarding** [comment] 2021-11-14 01:54
Ok, thanks for the clarification.

**Comment by woollarding** [comment] 2021-11-14 02:47
looks like that has fixed some of the things ! awesome job. my downloaders
thank you as well i am sure heh

**Comment by woollarding** [comment] 2021-11-14 03:05
not sure if this is the correct place to ask, but i cannot find the setting
for the away message.. is it still in there?

**Comment by woollarding** [comment] 2021-11-14 03:10
nevermind, found it ;)

**Comment by mathiascode** [comment] 2021-11-14 04:15
I've made some larger changes to the scanner code in order to improve performance (avoid scanning the file system twice). 

Could you download the latest unstable build, and:
- rescan once, and verify that everything looks fine
- remove the db files, rescan, and verify again?

Thanks! I just want to verify that no regressions were introduced.

**Comment by woollarding** [comment] 2021-11-14 15:30
Not a problem. I Removed the .db folders, updated to the latest version and
scanned, it took a while but looked good on QT, then I deleted the .db
again and scanned and it only took about a minute, still looking good on
QT :) Keep up the good work.

**Comment by woollarding** [comment] 2021-11-14 16:55
not sure if this is something to do with this version, but a banned user
was not able to view my userinfo ..
11:51:32 User sillybaby is reading your user info
11:51:39 [Chat] Private message from user 'sillybaby': it says "You are
banned from downloading my shared files."
would be super helpful if user is able to check info about why they
were banned, saves a lot of typing heh

**Comment by slook** [comment] 2021-11-14 16:58
Thank you for your assistance with this testing and troubleshooting @woollarding this is very helpful for the other users. If you notice anything else that needs fixing for the next release of Nicotine+ then you are welcome to post on here any time.

> it took a while... ...then I deleted the .db again and scanned and it only took about a minute

I have also observed this behaviour, it could be something to do with caching in semidbm, or perhaps drive caching at the OS and/or hardware level.

**Comment by slook** [comment] 2021-11-14 17:14
> would be super helpful if user is able to check info about why they were banned

The mechanisms for the sending and processing of shared file counts statistics is unrelated to this bug. For the latest thread on this topic see https://github.com/nicotine-plus/nicotine-plus/issues/1565, some partial remedies are being considered, such as including the minimum file/folder requirements in the messages. Of course, we have no control over what other clients do.

Given that all the OP's shared folders files are now visible to users after the successful improvements to the scanner, I think this Bug is resolved for now @mathiascode ?

**Comment by mathiascode** [comment] 2021-11-14 17:23
> not sure if this is something to do with this version, but a banned user was not able to view my userinfo .. 11:51:32 User sillybaby is reading your user info 11:51:39 [Chat] Private message from user 'sillybaby': it says "You are banned from downloading my shared files." would be super helpful if user is able to check info about why they were banned, saves a lot of typing heh

It was a somewhat sloppy change in 3.2.0. https://github.com/nicotine-plus/nicotine-plus/commit/616ef28820652a25af601738c876a295abc3b8b7 now shows the ban reason above the user info message instead of replacing it.

Thanks for your help! I'll close this issue.

**Closed by mathiascode** 2021-11-14 17:23 UTC
Labels: bug
