### ISSUE TITLE
3.2.9 - Bitrate button doesn't change/sort, nothing happens

### ISSUE THREAD

**Issue by 0pLuS0** [nicotine-plus/nicotine-plus#2696] opened 2023-10-20 02:05 UTC
Nicotine+ version:  3.2.9
Operating System/Distribution: Slackware 15.0

### Describe the bug
When clicking the Bitrate button, it doesn't change/sort, nothing happens.

### Expected behavior
Clicking on Bitrate should change/sort the order you want it to, either ascending or descending.

When I click on Size and Length, they change ascending or descending.

### Steps to reproduce the bug
Click on Bitrate

### Additional context
Screenshots, logs, stacktraces or relevant information.

Here's a screen shot showing the Bitrate button in between Size & Length.

THANKS

![nicotine](https://github.com/nicotine-plus/nicotine-plus/assets/36190223/25d0282e-80ab-472e-be48-e9bea7f31281)

**Comment by slook** [comment] 2023-10-20 03:24
It will only sorts within the User/Folder sub groups.

Choose File Grouping Mode -> "Ungrouped" to sort the entire list.

**Comment by 0pLuS0** [comment] 2023-10-20 04:25
Are you talking about this Ungrouped in the upper right?

![Nicotine_ungrouped](https://github.com/nicotine-plus/nicotine-plus/assets/36190223/bfd068d3-98fb-4e06-baac-50f2ba13c8a6)

When I use this Ungrouped, then I click on Bitrate, then the Bitrate and Length section disappear.

![Nicotine_disappear](https://github.com/nicotine-plus/nicotine-plus/assets/36190223/bfe6fe3e-4c75-4007-9174-028eedb08b29)

**Comment by slook** [comment] 2023-10-20 08:25
The results near the top have no Bitrate data, so they are sorted first. Scroll down.

**Comment by 0pLuS0** [comment] 2023-10-22 01:02
Besides the Bitrate data not showing, the Length is also not shown.

Here's a screen shot, showing music files/extensions that should be showing Bitrate and Length, so I don't understand why it's like this.

![bitrate_length](https://github.com/nicotine-plus/nicotine-plus/assets/36190223/e27be299-8d25-415a-bb44-2a026aa1f702)

This needs fixing...

THANKS

**Comment by slook** [comment] 2023-10-22 07:17
Those remote peers didn't send any file attribute data.

The only way to establish the information would be to download all of the files and open them up in a player or tag manager, then if data show you can confirm with the remote peers that they have a bug (or missing feature) in whatever version of the client they are running.

**Comment by mathiascode** [comment] 2023-10-22 15:04
Tell people to stop using Soulseek NS, that's the only way to fix it. That ancient client only provides file attributes for mp3 files, on a good day they might even be correct.

**Comment by 0pLuS0** [comment] 2023-10-22 23:37
Ok on the remote peers didn't send any file attribute data.

Also what mathiascode is saying too, the people are also using an older Soulseek version NS, which also causes this?

THANKS

**Comment by slook** [comment] 2023-10-23 01:02
Not really no. You could set a default Result Filter for Bitrate as `!0` but that will also filter out all non-audio files. At least if you are interested in high bitrate files then you will ordinarily sort highest first, so those defective results will be at the bottom of the list.

It is the way it is, I'm afraid.

Closing, since there is no reason to think that this problem would be caused by a bug in Nicotine+.

**Closed** 2023-10-23 01:03 UTC
Labels: question

**Comment by 0pLuS0** [comment] 2023-10-23 23:25
I set the ```Search Results Filter``` - ```Bitrate: !0``` but when I do a search I am seeing seeing Bitrate and Length Columns empty at the top. hmm

**Comment by slook** [comment] 2023-10-24 05:35
That could be https://github.com/nicotine-plus/nicotine-plus/issues/2141 which is fixed in Nicotine 3.3.0.dev:

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Comment by 0pLuS0** [comment] 2023-10-24 21:16
Ok, thanks...

**Comment by mathiascode** [comment] 2023-10-25 02:17
If you want to stay on the stable 3.2.9 release, you can use `1` instead of `!0` as the bitrate filter for now.

> Will this also handle the empty `Length` too?

In most cases, yes, since typically both the length and bitrate are empty. 3.3.0.dev6 adds a duration filter though, which you can set to ensure these results are never shown.

**Comment by 0pLuS0** [comment] 2023-10-25 23:55
For the ```Search Results - Exclude``` I made it like this;

```m3u|jpg|jpeg|mxm|ini|log|cue|txt|m4a|nfo|URL|omx|png|wav|mpg|avi|sfv|md5|cdg|mp4```

Is there just one flag/option I can use, instead of having to define every extension I don't want to see, and only see music files/extensions is all?

THANKS

**Comment by mathiascode** [comment] 2023-10-26 13:05
> Is there just one flag/option I can use, instead of having to define every extension I don't want to see, and only see audio music files/extensions is all?

Not in Nicotine+ 3.2.9, but 3.3.0.dev6 has a generic file type filters, such as "audio", "video", "image" etc.
