### ISSUE TITLE
Double click on username to enter user's shared files

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2104] opened 2022-06-28 04:58 UTC
### Describe the solution you'd like
Currently, double clicking on username in downloads/uploads enters to my shared files which is pretty weird.

**Comment by slook** [comment] 2022-06-28 10:30
When clicking a file in Downloads, the Browse Folder action should navigate to the remote Folder.

When clicking a file in Uploads, the Browse Folder action navigates to the local Folder in your shares, which is expected behaviour since the remote source folder is not known.

**Comment by SnIPeRSnIPeR** [comment] 2022-06-28 18:40
When I clicked on a username, it navigate me to a folder from my PC which downloaded by this user...

![2022-06-29_01-36-54](https://user-images.githubusercontent.com/31162059/176257614-31274a8e-ac1d-4489-9d4d-6b131cb8fa77.png)
![2022-06-29_01-37-05](https://user-images.githubusercontent.com/31162059/176257626-2b8ca320-aa18-41f7-afe2-6798d1be556b.png)

Instead of this (User(s)-Shared Files):

![2022-06-29_01-39-17](https://user-images.githubusercontent.com/31162059/176257896-42b60bc9-bf88-43dd-9bc8-8a4b7ca1b558.png)

**Comment by slook** [comment] 2022-07-31 21:59
Closing since the action for User rows in the transfers view is now always Expand/Collapse, which makes more sense in any case no matter what the default double-click action is set to that applies only to folders and files as appropriate.

**Closed by slook** 2022-07-31 21:59 UTC
