### ISSUE TITLE
Very strange bug with program interface

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2448] opened 2023-03-19 13:17 UTC
Nicotine+ version:  3.2.9
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

Hello! I found a strange bug in Nicotine+ 3.2.9:

![2023-03-19_19-30-16](https://user-images.githubusercontent.com/31162059/226177535-9d42e511-cbf4-4bf9-9752-c8aec6319c92.png)
![2023-03-19_19-30-51](https://user-images.githubusercontent.com/31162059/226177537-54f7d959-ad76-494f-a639-e266f5677476.png)

The list expands left or right for no reason.

**Comment by mathiascode** [comment] 2023-03-19 18:34
The submenu normally expands to the right, but can expand to the left if there isn't enough room. However, if it has expanded to the left once, it seems to keep doing this even when more room becomes available, which might be a GTK 3 bug.

I'm not sure if it's worth spending time looking into this, since the issue is fixed in GTK 4, which our development builds use.

**Comment by SnIPeRSnIPeR** [comment] 2023-03-20 08:50
> The submenu normally expands to the right, but can expand to the left if there isn't enough room. However, if it has expanded to the left once, it seems to keep doing this even when more room becomes available, which might be a GTK 3 bug.
I think, you are right!

> I'm not sure if it's worth spending time looking into this, since the issue is fixed in GTK 4, which our development builds use.
So, this error is already fixed in new versions of Nicotine+?

**Comment by mathiascode** [comment] 2023-03-20 11:52
> So, this error is already fixed in new versions of Nicotine+?

Yes, it's fixed in Nicotine+ 3.3.0.dev4.

**Closed** 2023-03-20 14:08 UTC
Labels: bug
