### ISSUE TITLE
After using Clear on an uploaded item, it gets removed, but then returns

### ISSUE THREAD

**Issue by redactedscribe** [nicotine-plus/nicotine-plus#1745] opened 2021-12-03 00:13 UTC
Nicotine+ version: 3.2.0.rc2
Operating System/Distribution: Windows 11

### Steps to reproduce the bug
1. Clear an uploaded item.
2. Change tab and wait for Uploads tab to be highlighted.
3. Switch to Uploads and notice that the previously cleared uploads have returned.

**Comment by mathiascode** [comment] 2021-12-03 00:38
Is a user re-queuing uploads? Are these uploads finished?

**Comment by redactedscribe** [comment] 2021-12-03 00:44
I should've mentioned that: the files are finished, both read 100%, so I don't think it's anything the user is doing.

**Comment by redactedscribe** [comment] 2021-12-03 07:51
Seems to have stopped happening (using a newer build). Happened multiple times and across launches. Only observed it with two particular files that had been uploaded to a user that I was trying to clear.

**Comment by slook** [comment] 2021-12-04 11:56
It sounds like the user's client didn't know when to stop retrying, perhaps because it never received/processed a message to say the transfer was finished. Is is possible for you to discover the remote user's client version with `CTCP_VERSION` ?

**Comment by redactedscribe** [comment] 2021-12-04 12:32
I don't recall the username unfortunately. Also, I don't know how to do as you asked. Would `CTCP_VERSION` just be written in the logs, or is it a command I'd have to issue somehow?

**Comment by slook** [comment] 2021-12-04 12:37
It wouldn't help much, just it would be interesting to know the version of the other client. You send the command via a private message.

**Comment by slook** [comment] 2021-12-04 13:53
Please re-open this issue if this behaviour happens again, ideally with a transfers debug log.

**Comment by redactedscribe** [comment] 2021-12-07 13:15
> You send the command via a private message.

@slook I'm trying to send `/CTCP_VERSION` via a private chat but Nicotine+ complains "Command /CTCP_VERSION is not recognized".

Could you explain how this command is issued?

**Comment by redactedscribe** [comment] 2021-12-07 13:57
Original upload (10 audio files, 2 images):

```log
17:03:18    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
17:04:36    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
17:05:08    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
17:06:28    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <image>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <image>.<ext>
```

Nothing, and then a ~month (notice start and finish times are the same, but no image transfers):

```log
00:46:42    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
00:46:42    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
00:47:39    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
00:47:39    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
...
```

... and repeats for an hour with 10 minute intervals between each new chunk of the 10 audio files.

And just recently, the log has spam showing the same chunks with 10 minute intervals for 5 hours straight:

```log
01:00:28    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
01:01:29    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
01:02:28    Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
01:02:28    Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload started: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
<time>      Upload finished: user <user>, IP address ('<ip>', <port>), file <audio>.<ext>
...
```

Not sure why only the audio files keep being redownloaded so to speak and the image not.

This is all that transfers.log contained regarding the specific user.

**Comment by slook** [comment] 2021-12-07 18:41
`CTCP VERSION` is sent without the `/` just as a plain message, and without `_` underscore, sorry my mistake.

The transfer.log probably won't be enough to diagnose the issue, we would need the Conn and Msg debug log categories as well, which might be difficult unless the issue can be replicated again.

**Comment by redactedscribe** [comment] 2021-12-07 18:55
I sent `CTCP VERSION` as a message, but it returned nothing.

Anyway. I'll report back if anything else comes up.

**Comment by mathiascode** [comment] 2021-12-07 18:59
> `CTCP VERSION` is sent without the `/` just as a plain message, and without `_` underscore, sorry my mistake.

This will not work. Use the command /ctcpversion instead (note that this is a feature exclusive to Nicotine+).

> The transfer.log probably won't be enough to diagnose the issue, we would need the Conn and Msg debug log categories as well, which might be difficult unless the issue can be replicated again.

You can toggle these debug categories in the right-click menu of the log pane in Nicotine+ 3.2.0. Enable the connection, message and transfer categories.

**Comment by redactedscribe** [comment] 2021-12-08 06:01
Regex-matched every line that _didn't_ contain the user's name, ip, "object at" messages, or the files in question, and deleted them. Only the relevant lines should be left:

```log
XX:31:21 [Msg] <class 'pynicotine.slskmessages.ConnectToPeer'> {'token': 5756, 'user': '<user>', 'conn_type': 'P', 'ip_address': '<user_ip>', 'port': 62463, 'privileged': 0}
XX:31:21 [Conn] Attempting direct connection of type P to user <user> ('<user_ip>', 62463)
XX:31:21 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=6124, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11824), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:21 [Conn] Established connection with user <user>. List of outgoing messages: []
XX:31:22 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Transfer] Checking if file <file> is shared
XX:31:22 [Transfer] Checked upload queue, attempting to upload file <file> to user <user>
XX:31:22 [Transfer] Initializing upload request for file <file> to user <user>
XX:31:22 [Transfer] Requesting to upload file <file> with transfer request None to user <user>
XX:31:22 [Conn] Found existing connection of type P for user <user>, using it.
XX:31:22 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
XX:31:22 [Transfer] QueueUpload request: User <user>, {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Transfer] Checking if file <file> is shared
XX:31:22 [Transfer] QueueUpload request: User <user>, {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Transfer] Checking if file <file> is shared
XX:31:22 [Transfer] QueueUpload request: User <user>, {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Transfer] Checking if file <file> is shared
XX:31:22 [Transfer] QueueUpload request: User <user>, {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Msg] <class 'pynicotine.slskmessages.QueueUpload'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Transfer] Checking if file <file> is shared
XX:31:22 [Transfer] QueueUpload request: User <user>, {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'file': '<file>', 'legacy_client': False}
XX:31:22 [Msg] <class 'pynicotine.slskmessages.TransferResponse'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'allowed': 1, 'req': 175, 'reason': None, 'filesize': None}
XX:31:22 [Transfer] Received response for transfer request 175. Allowed: 1. Reason: None. Filesize: None
XX:31:22 [Conn] Attempting direct connection of type F to user <user> ('<user_ip>', 62463)
XX:31:22 [Conn] Sending message of type <class 'pynicotine.slskmessages.FileRequest'> to user <user>
XX:31:22 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=6076, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11825), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:22 [Conn] Established connection with user <user>. List of outgoing messages: [<pynicotine.slskmessages.FileRequest object at 0x0000024bef6a2190>]
XX:31:22 [Msg] <class 'pynicotine.slskmessages.FileRequest'> {'conn': <socket.socket fd=6076, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11825), raddr=('<user_ip>', 62463)>, 'req': 175}
XX:31:22 [Transfer] Received file request 175
XX:31:22 [Transfer] Received file download request 175 for file <file> from user <user>
XX:31:22 [Msg] <class 'pynicotine.slskmessages.UploadFile'> {'conn': <socket.socket fd=6076, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11825), raddr=('<user_ip>', 62463)>, 'file': <_io.BufferedReader name='<file_path>'>, 'size': 14546753, 'sentbytes': 0, 'offset': 14546753}
XX:31:22 [Transfer] Checked upload queue, attempting to upload file <file> to user <user>
XX:31:22 [Transfer] Initializing upload request for file <file> to user <user>
XX:31:22 [Transfer] Requesting to upload file <file> with transfer request None to user <user>
XX:31:22 [Conn] Found existing connection of type P for user <user>, using it.
XX:31:22 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
XX:31:23 [Msg] <class 'pynicotine.slskmessages.TransferResponse'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'allowed': 1, 'req': 176, 'reason': None, 'filesize': None}
XX:31:23 [Transfer] Received response for transfer request 176. Allowed: 1. Reason: None. Filesize: None
XX:31:23 [Conn] Attempting direct connection of type F to user <user> ('<user_ip>', 62463)
XX:31:23 [Conn] Sending message of type <class 'pynicotine.slskmessages.FileRequest'> to user <user>
XX:31:23 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=6112, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11827), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:23 [Conn] Established connection with user <user>. List of outgoing messages: [<pynicotine.slskmessages.FileRequest object at 0x0000024bf15cdc70>]
XX:31:23 [Msg] <class 'pynicotine.slskmessages.FileRequest'> {'conn': <socket.socket fd=6112, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11827), raddr=('<user_ip>', 62463)>, 'req': 176}
XX:31:23 [Transfer] Received file request 176
XX:31:23 [Transfer] Received file download request 176 for file <file> from user <user>
XX:31:23 [Msg] <class 'pynicotine.slskmessages.UploadFile'> {'conn': <socket.socket fd=6112, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11827), raddr=('<user_ip>', 62463)>, 'file': <_io.BufferedReader name='<file_path>'>, 'size': 15806908, 'sentbytes': 0, 'offset': 15806908}
XX:31:23 [Transfer] Checked upload queue, attempting to upload file <file> to user <user>
XX:31:23 [Transfer] Initializing upload request for file <file> to user <user>
XX:31:23 [Transfer] Requesting to upload file <file> with transfer request None to user <user>
XX:31:23 [Conn] Found existing connection of type P for user <user>, using it.
XX:31:23 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
XX:31:24 [Msg] <class 'pynicotine.slskmessages.TransferResponse'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'allowed': 1, 'req': 177, 'reason': None, 'filesize': None}
XX:31:24 [Transfer] Received response for transfer request 177. Allowed: 1. Reason: None. Filesize: None
XX:31:24 [Conn] Attempting direct connection of type F to user <user> ('<user_ip>', 62463)
XX:31:24 [Conn] Sending message of type <class 'pynicotine.slskmessages.FileRequest'> to user <user>
XX:31:24 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=5788, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11828), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:24 [Conn] Established connection with user <user>. List of outgoing messages: [<pynicotine.slskmessages.FileRequest object at 0x0000024bef06abe0>]
XX:31:24 [Msg] <class 'pynicotine.slskmessages.FileRequest'> {'conn': <socket.socket fd=5788, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11828), raddr=('<user_ip>', 62463)>, 'req': 177}
XX:31:24 [Transfer] Received file request 177
XX:31:24 [Transfer] Received file download request 177 for file <file> from user <user>
XX:31:24 [Msg] <class 'pynicotine.slskmessages.UploadFile'> {'conn': <socket.socket fd=5788, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11828), raddr=('<user_ip>', 62463)>, 'file': <_io.BufferedReader name='<file_path>'>, 'size': 13626200, 'sentbytes': 0, 'offset': 13626200}
XX:31:24 [Transfer] Checked upload queue, attempting to upload file <file> to user <user>
XX:31:24 [Transfer] Initializing upload request for file <file> to user <user>
XX:31:24 [Transfer] Requesting to upload file <file> with transfer request None to user <user>
XX:31:24 [Conn] Found existing connection of type P for user <user>, using it.
XX:31:24 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
XX:31:25 [Msg] <class 'pynicotine.slskmessages.TransferResponse'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'allowed': 1, 'req': 178, 'reason': None, 'filesize': None}
XX:31:25 [Transfer] Received response for transfer request 178. Allowed: 1. Reason: None. Filesize: None
XX:31:25 [Conn] Attempting direct connection of type F to user <user> ('<user_ip>', 62463)
XX:31:25 [Conn] Sending message of type <class 'pynicotine.slskmessages.FileRequest'> to user <user>
XX:31:25 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=764, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11829), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:25 [Conn] Established connection with user <user>. List of outgoing messages: [<pynicotine.slskmessages.FileRequest object at 0x0000024bef3250a0>]
XX:31:25 [Msg] <class 'pynicotine.slskmessages.FileRequest'> {'conn': <socket.socket fd=764, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11829), raddr=('<user_ip>', 62463)>, 'req': 178}
XX:31:25 [Transfer] Received file request 178
XX:31:25 [Transfer] Received file download request 178 for file <file> from user <user>
XX:31:25 [Msg] <class 'pynicotine.slskmessages.UploadFile'> {'conn': <socket.socket fd=764, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11829), raddr=('<user_ip>', 62463)>, 'file': <_io.BufferedReader name='<file_path>'>, 'size': 15635537, 'sentbytes': 0, 'offset': 15635537}
XX:31:25 [Transfer] Checked upload queue, attempting to upload file <file> to user <user>
XX:31:25 [Transfer] Initializing upload request for file <file> to user <user>
XX:31:25 [Transfer] Requesting to upload file <file> with transfer request None to user <user>
XX:31:25 [Conn] Found existing connection of type P for user <user>, using it.
XX:31:25 [Conn] Sending message of type <class 'pynicotine.slskmessages.TransferRequest'> to user <user>
XX:31:26 [Msg] <class 'pynicotine.slskmessages.TransferResponse'> {'conn': <pynicotine.slskproto.PeerConnection object at 0x0000024bf17ab900>, 'allowed': 1, 'req': 179, 'reason': None, 'filesize': None}
XX:31:26 [Transfer] Received response for transfer request 179. Allowed: 1. Reason: None. Filesize: None
XX:31:26 [Conn] Attempting direct connection of type F to user <user> ('<user_ip>', 62463)
XX:31:26 [Conn] Sending message of type <class 'pynicotine.slskmessages.FileRequest'> to user <user>
XX:31:26 [Msg] <class 'pynicotine.slskmessages.InitPeerConn'> {'conn': <socket.socket fd=1452, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11832), raddr=('<user_ip>', 62463)>, 'addr': ('<user_ip>', 62463), 'init': None}
XX:31:26 [Conn] Established connection with user <user>. List of outgoing messages: [<pynicotine.slskmessages.FileRequest object at 0x0000024bef06a940>]
XX:31:26 [Msg] <class 'pynicotine.slskmessages.FileRequest'> {'conn': <socket.socket fd=1452, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11832), raddr=('<user_ip>', 62463)>, 'req': 179}
XX:31:26 [Transfer] Received file request 179
XX:31:26 [Transfer] Received file download request 179 for file <file> from user <user>
XX:31:26 [Msg] <class 'pynicotine.slskmessages.UploadFile'> {'conn': <socket.socket fd=1452, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('<ip>', 11832), raddr=('<user_ip>', 62463)>, 'file': <_io.BufferedReader name='<file_path>'>, 'size': 8247105, 'sentbytes': 0, 'offset': 8247105}
```

Browsing the user for the file's in question finds nothing.

**Comment by slook** [comment] 2021-12-08 14:51
> XX:31:22 [Transfer] Received response for transfer request 175. Allowed: 1. Reason: None. Filesize: None

It seems that the file is no longer shared resulting in `Filesize: None` , causing transfer_file to later return None for the request ID:

> XX:31:24 [Transfer] Requesting to upload file <file> with transfer request None to user <user>

Which results in the cascading error that needs avoiding with both a condition of a complete file already existing and/or the file not being shared anymore, perhaps along with the existing condition of the file not being locally_queued:

https://github.com/nicotine-plus/nicotine-plus/blob/0063a7bb9a6af75528fe0a0a3f575f90ef84165d/pynicotine/transfers.py#L1635-L1641

But the remote filesize nor pre-existance is unknown here at this point, so I don't know how to implement this check.

**Comment by mathiascode** [comment] 2021-12-08 15:54
The `None` transfer request doesn't matter, everything is working as intended here. It used to contain a value, but the newer QueueUpload system we switched to a few months ago doesn't have a transfer request at this point.

If the file wasn't shared, it wouldn't appear in the list of uploads.

I don't see anything that looks strange on our end, apart from the user requeuing the finished uploads again for no reason. @redactedscribe could you send the username and full log to my email address (see my GH profile)?

**Comment by redactedscribe** [comment] 2021-12-08 17:47
@mathiascode Sent.

**Comment by mathiascode** [comment] 2021-12-08 20:32
The user seems to be using SoulseekQt.

The only thing that makes sense to me is some kind of file size mismatch, i.e. your client finishes uploading the file, but the file size is larger on the other user's end for some reason, tricking SoulseekQt into thinking the download ended abruptly. I was able to replicate the behavior observed in your logs by sharing a file in Nicotine+, starting a download in SoulseekQt, disconnecting, replacing the shared file with a smaller one while keeping the same file path, and reconnecting. Since SoulseekQt ignores any changes to the total file size after adding the download, the file sizes no longer match.

Could you ask what the user sees on their end (preferably a screenshot of the downloads)?

**Comment by redactedscribe** [comment] 2021-12-09 06:21
I sent them a message two days ago but they have not replied. If they get back to me, I'll let you know.

**Comment by redactedscribe** [comment] 2021-12-09 08:38
Just an update: Updated Nicotine+ to latest testing build. Renamed the directory that was causing trouble, rescanned shared. After some minutes, the user attempted to re-download the files (requested), but was given the response that the files aren't shared. After 30 minutes, the user hasn't tried to re-download the files. I guess their client now knows it's not worth trying? Will keep an eye on it.

**Comment by mathiascode** [comment] 2021-12-09 16:06
> I guess their client now knows it's not worth trying?

I believe the client stops trying when receiving a "File not shared" status.

**Comment by redactedscribe** [comment] 2021-12-09 16:16
Is it worth trying to pick up the slack of other clients acting weirdly? I.e. do some check on Nicotine+'s end so this loop can't occur? Or just hope the other client will get patched eventually?

**Comment by slook** [comment] 2021-12-09 17:46
In the long-run, generally speaking, implementing workarounds/hacks for bugs/omissions in other network related software often turns out to be counter productive, because the devs of that software will be less likely to know that a bug exists, or if they are aware of it then they would have less motivation to fix it (unless their client/server software is also affected).

Having said that, Nicotine+ is in the special category of an unofficial client for a proprietary network, so it is expected that it should do it's best to behave in accordance with the third party network no matter what (and it does do a good job), otherwise the network admins wouldn't tolerate it. Additionally, since N+ is FOSS, the core fixes implemented into it may well be a useful resource to inspire other devs to make improvements in their software, even if their project is closed source, since it is in everybodys best interests to make sure things run smoothly.

It would be interesting to know if similar undesirable behaviour is observed when transiently changing files are transferred between two Qt clients or not, I guess if does not, then we should try to pick up the slack, even if the bug doesn't belong to us.

When testing for this, it is worth considering that even if a file transfer appears to complete successfully, there's a chance it could still be corrupted if the length and/or contents of it changed mid way as it was written to disk... For sequentially encoded audio files (eg PCM WAV) file corruption usually presents as a nasty digital glitch, and for compressed files (eg MP3) this can result in all sorts of strange/unpredictable errors such as being non-seekable, unplayable, gaps of silence or a visual waveform that doesn't match the audio. Minor defects such as clicks/pops are the worst, because they may not be immediately apparent.

Traditionally, CRC or MD5 hashes are commonly used to verify if files are identical or not, since matching size alone doesn't guarantee bit-for-bit accuracy. There is no such integrity checking mechanism on the slsk protocol, we don't even know the remote file modification date, so all we have to work with is size.

**Comment by redactedscribe** [comment] 2021-12-09 20:17
The user just "re-downloaded" the files again. I guess their client didn't give up in the end. Installing the latest build now seeing as there are related fixes.

**Comment by mathiascode** [comment] 2021-12-09 20:25
Their client probably restarted.

We can't stop these download requests from our end. The only workaround we could potentially implement is to remove uploads from the list if the requested file position is identical to the file size.

**Comment by slook** [comment] 2021-12-09 20:45
It would be a good idea to include the conditions that file is "Finished" and read 100% , as this is good evidence that it did complete successfully in the past.

**Comment by redactedscribe** [comment] 2021-12-09 21:04
> We can't stop these download requests from our end.

I'm hoping by banning the user I won't have to deal with these zombie uploads any more.

**Comment by slook** [comment] 2021-12-21 00:44
Interesting related discussion about issue https://github.com/jpdillingham/Soulseek.NET/issues/604

**Comment by mathiascode** [comment] 2021-12-21 20:13
I don't really want to add workarounds for this right now. Repeatedly removing these uploads immediately after they've been added would be awkward, and the issue isn't common enough to warrant any new logic. Ultimately, it's SoulseekQt's fault for ignoring updated file sizes sent with upload requests.

**Closed by mathiascode** 2021-12-21 20:13 UTC
Labels: bug
