### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by piperb91** [nicotine-plus/nicotine-plus#2851] opened 2024-02-03 10:59 UTC
Nicotine+ Version: 3.3.0
GTK Version: 4.12.5
Python Version: 3.11.7 (darwin)

Type: <class 'BufferError'>
Value: Existing exports of data: object cannot be re-sized
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 848, in _raise_exception
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2685, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2456, in _process_ready_sockets
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2411, in _process_ready_input_socket
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2467, in _process_conn_incoming_messages
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1307, in _process_server_input
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1518, in _send_message_to_server
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2539, in _process_outgoing_message
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 2301, in _process_internal_messages
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 1479, in _server_disconnect
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskproto.py", line 937, in _close_connection

**Comment by slook** [comment] 2024-02-03 11:12
Closing as duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2850

Fixed in Nicotine+ 3.3.1dev1 available at https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos

Thank you for your report @piperb91 please let us know if the latest master build is working okay for you?

**Closed by slook** 2024-02-03 11:12 UTC
Labels: bug, duplicate
