### ISSUE TITLE
missing option to rescan buddy shares

### ISSUE THREAD

**Issue by sysdbugfactory** [nicotine-plus/nicotine-plus#2761] opened 2023-11-20 15:14 UTC
Nicotine+ version:  3.2.2
Operating System/Distribution: debian 12.2 / kde

### Describe the bug

After making a change to my buddy shares, the removed directories still appears when browsing buddy shares.
I did a manual rescan of shares which update the shares but not the buddy shares.
After restarting the application, the now removed directories are still listed.
Despite the lack of documentation I eventually found the config file and checked there but they are not in the config file.

The lack of a button to manually rescan buddy shares seems odd as it used to exist and is now nowhere to be found.

a few hours later I came back to this issue and found out it had eventually updated.

### Expected behavior

I expect the changes to the buddy shares to be acted when I click OK to validate the change.
Alternatively having a rescan buddy shares button as it used to exist.

### Steps to reproduce the bug

start nicotine, remove existing directory from buddy shares, browse buddy shares.
click rescan shares, browes buddy shares.
enable the rescan shares on startup, close nicotine, start nicotine, browse buddy shares.

each time you browse the buddy shares the removed directories still appear.

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment] 2023-11-20 18:13
Please try the [latest stable build Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md) 3.2.9, wherein the issue you reported may have been resolved already.

**Comment by slook** [comment] 2023-11-24 00:56
> missing option to rescan buddy shares

Not a bug, the "Rescan Public Shares" and "Rescan Buddy Shares" functions were removed intentionally in favour of the combined "Rescan Shares" function (whether that was the right decision is perhaps debatable, please re-open the issue if you have a valid use case for those seperate rescanning functions other than working around the old bugs you reported which are likely already fixed in recent versions).

**Closed by slook** 2023-11-24 00:56 UTC
