### ISSUE TITLE
Port forwarding (with UPnP auto port forwarding or manually) stops working on Mac OS X (apple silicon M1) after a few hours

### ISSUE THREAD

**Issue by Vexariboerl** [nicotine-plus/nicotine-plus#2223] opened 2022-10-21 19:42 UTC
Nicotine+ version:  3.2.6rc4 (I tried 3.2.4 and 3.2.5)
Operating System/Distribution: OS X 12.6, Mac Mini M1

### Describe the bug
The Preferences / Network / Use UPnP… is not working on my Mac Mini M1 and an Asus RT-AC68U router.
UPnP is enabled on the router. It works fine with other apps such as Transmission.

### Expected behavior
This option should auto forward the right listening port on the router.
Since it is not working, I unchecked the option and forwarded the ports manually on the router.
I'm just not sure if I should forward only the active listening port or the range that is specified just above (usually 2235 to 2239)

Edit:
(I modified the title to reflect what has been )
Port forwarding stops working after a few hours (~12-24h). This happens with UPnP auto port forwarding enabled, or not with manual port forwarding on the router. This also seems to happen only on M1 Apple silicon Mac as Nicotine+ Windows on the same network is fine, and Nicotine+ OS X on Intel machine is fine as well (on another network).

### Steps to reproduce the bug
Edit:
Start Nicotine+ on a M1 Mac (Mac Mini M1 2020 for me). Port is open for a few hours (usually 12 to 24), then the port is closed. When quitting and relaunching Nicotine+, the port is back to open state but only for a few hours..

### Additional context
Screenshots, logs, stacktraces or relevant information.

**Comment by slook** [comment] 2022-10-22 07:38
To investigate the issue we need to first look at the debug logs:

- Preferences -> Logging -> Log debug messages to file
- Menu -> View -> Show log history pane
- Right-click the log history pane -> Categories -> Enable "Miscellaneous"
- Once you've captured a failed connection attempt, right-click the log history pane -> Open log folder, to see the debug log file.

**Comment by Vexariboerl** [comment] 2022-10-22 18:17
I updated to 3.2.6 and it seems that Preferences / Network / Use UPnP… now opens a port on my Router and clicking on the link to check the port state says the port is open.

But,
after a few hours my Router still shows an opened by NicotinePlus a port but clicking on the check port link says the port is now closed. I checked with another online port check tool just in case.

I then unchecked and rechecked Use UPnP…. Nicotine+ now says the external port was successfully redirected but the port is still closed when using the check port link.

If I quit and restart Nicotine+, then now the port is open.
But this will last only a few hours.

During all this Transmission 3 is opening 2 ports with UPnP and they stayed open on the same computer.

[debug_1666427334.log.zip](https://github.com/nicotine-plus/nicotine-plus/files/9845029/debug_1666427334.log.zip)
[debug_1666462127.log.zip](https://github.com/nicotine-plus/nicotine-plus/files/9845030/debug_1666462127.log.zip)

**Comment by slook** [comment] 2022-10-23 15:21
> But this will last only a few hours.

Can you try to capture a debug log showing around the time that the failure happens?

**Comment by Vexariboerl** [comment] 2022-10-23 15:58
I will try but I'm not sure there will be something in the log – Last time it happened, on the bottom of the Nicotine+ main window, there was still a message saying 
`2022-10-23 14:49:53 UPnP : Le port externe 2245 a été redirigé avec succès vers l'adresse IP locale 192.168.1.17 du port 2245`
but then checking the port said it was closed.
For the moment the port is still open.

I'm including the last 2 debug log files. Maybe there is something in here. I quit and restarted Nicotine at around 10 this morning.
[2022-10-23 debug since 22.10.2022 ~20h15 .zip](https://github.com/nicotine-plus/nicotine-plus/files/9846971/2022-10-23.debug.since.22.10.2022.20h15.zip)

**Comment by Vexariboerl** [comment] 2022-10-23 19:19
Ok, I checked the port status about 30 min ago and it was closed. So I quit and Restarted Nicotine+ (now the port is open again)

I'm including the complete log for this last session, until I restarted (at about 20:45).
I see that in the meantime between my las post (at 18:49), Nicotine said it had successfully redirected the port. Maybe this is the the time it actually failed? Or the time should be somewhere between 15:03:52 and 20:45:32 when I restarted.

[2022-10-23 2 complete debug_1666529391.log.zip](https://github.com/nicotine-plus/nicotine-plus/files/9847348/2022-10-23.2.complete.debug_1666529391.log.zip)

**Comment by slook** [comment] 2022-10-23 19:47
It seems perhaps that the failure happens around the time the lease is renewed. For some reason even though the request is successful maybe there is some conflict with the previous rule.

**Comment by Vexariboerl** [comment] 2022-10-24 20:12
A little bit more info…

I had a look on the UPnP forwards on my router this morning when the port check was saying it is closed. 
It is still listed in the UPnP forwards list.
If I quit Nicotine+, It still stay in the list.
![2022-10-24 10h50 - quit Nicotite+, (not working) port forward stays in router](https://user-images.githubusercontent.com/55237993/197618730-ff2acada-744c-421f-a781-cb85491573f2.png)
If I quit Transmission, Transmission forward disappears from the list.
![2022-10-24 10h51 - quit Transmission and associated port forward dissapears  Nicotine not running but stays](https://user-images.githubusercontent.com/55237993/197618832-2aff446f-fa68-47b7-83c4-b2e063000879.png)

I tried to manually forward the port and disabled UPnP in Nicotine+, but I get the same result.
The port gets closed after a few hours. 
If I restart Nicotine+, the port is back to open.

Any Ideas?

**Comment by mathiascode** [comment] 2022-10-25 18:32
Looking at the screenshots, it is clear that the UPnP lease hasn't expired. Either something else must be blocking the port after a while, or there's a bug somewhere.

> If I quit Nicotine+, It still stay in the list.

This is expected. We don't remove the port forward when quitting Nicotine+, it expires after the lease runs out instead.

What does Soulseek's port checker say about the ports Transmission forwards after a few hours? Replace the port in the URL with the one Transmission uses: http://tools.slsknet.org/porttest.php?port=xxxxx

**Comment by slook** [comment] 2022-11-04 09:21
@Vexariboerl Have you been able to find a configuration which enables you to maintain a stable connection?

Do you have any further observations to offer as to the suspected bug in Nicotine+ being verified as the cause of the UPnP issues you were/are encountering?

**Comment by Vexariboerl** [comment] 2022-11-04 11:37
@slook No unfortunately I haven't found a configuration that maintains a stable connection with Nicotine+ :(

The last 10 day I've been testing this to see if my router has the problem or if it is a Nicotine+ bug.
I've decided to simplify things and disabled UPnP automatic port forwarding on my router and forwarded the needed ports manually.
On my router I also have an OpenVPV server setup (in bridge mode TAP) so I can connect to my home network from my work computer. I decided to not connect for a while to see if this would be a potential troublemaker. So I haven't OVPN connected from work to my routed for a few days so far.
I also upgraded Transmission to v4.0 beta (which is Apple M1 native).
Nicotine+ and Transmission UPnP automatic port forwarding option have also been disabled in the preference.

What I found out so far…
I have let Roon and Transmission run 24/24 for many days and their port seems to stay open. I can confirm this for Roon as I'm able to connect to it from the WAN. Transmission I'm relying on the port check in its preferences (I also tested it with the prttest link I was given 2 post earlier).
Nicotine+ port doesn't seem to stick after roughly a day. If I launch it in the morning, the port becomes closed by the evening. If I quit and relaunch Nicotine+, the port is back to open.

I hope this help a little to figure this out.

**Comment by mathiascode** [comment] 2022-11-06 15:51
Is there any firewall enabled on your system? If so, could you disable it and see if anything changes?

It almost sounds like there's something that attempts to close "inactive" ports (that haven't been rebound) after a while.

**Comment by Vexariboerl** [comment] 2022-11-07 10:28
On my router there is a [firewall option](https://www.asus.com/us/support/FAQ/1013630/) — which is activated at the moment. Is this what you mean? Is it safe to disable this?
![Capture d’écran 2022-11-06 à 21 02 09](https://user-images.githubusercontent.com/55237993/200286937-ca72fadb-c0a0-4703-871f-53bd58e5f064.png)

On the computer where I run Nicotine+ there is also a kind of firewall called [Little Snitch](https://en.wikipedia.org/wiki/Little_Snitch) running but all in/out connections for Nicotine+ have been allowed. I'm wondering how can this one could interfere with my router opened ports.
![Capture d’écran 2022-11-06 à 21 07 15](https://user-images.githubusercontent.com/55237993/200287644-2a33d9d7-2ff1-48c5-b160-18d7c76e8254.png)

**Comment by slook** [comment] 2022-11-07 11:55
> On my router there is a firewall... Is it safe to disable this?

No, it isn't a good idea to disable your router firewall. However it might be an idea to setup an Inbound rule for Nicotine+ ports that are forwarded to the local IP of your client machine.

> On the computer where I run Nicotine+ there is also a kind of firewall called Little Snitch...

This software is known to interfere with Nicotine+ ports (see issue https://github.com/nicotine-plus/nicotine-plus/issues/2154), although that doesn't seem directly related to the problem you are having here, it could be worth disabling Little Snitch to see if it does indeed make any difference or not.

**Comment by Vexariboerl** [comment] 2022-11-07 19:22
> However it might be an idea to setup an Inbound rule for Nicotine+ ports that are forwarded to the local IP of your client machine.

Actually I have a rule set up for Nicotine for about 2 weeks
![Capture d’écran 2022-11-07 à 19 40 01](https://user-images.githubusercontent.com/55237993/200390673-02ec295d-a749-419c-b576-889e99780de6.png)

> Your router's firewall might have a packet logging feature that could help to identify if perhaps it's DDoS protection feature is detecting Soulseek traffic as a false positive. It's up to you if you want to test with this feature of the firewall disabled (but I would recommend you should leave it enabled unless you have other measures in place elsewhere on your network setup).

There is something that looks like a packet logging feature for the router's firewall. I just set it up to log dropped packet and see it I see something in the log a day later.
![Capture d’écran 2022-11-07 à 19 58 14](https://user-images.githubusercontent.com/55237993/200392917-519b4107-9571-4847-b70e-b3d47889b2b2.png)

> This software is known to interfere with Nicotine+ ports in certain scenarios (see issue https://github.com/nicotine-plus/nicotine-plus/issues/2154), although that doesn't seem directly related to the problem you are having here, it could be worth disabling Little Snitch to see if it does indeed make any difference or not.

ok I'll try maybe that later but I really need Little Snitch.
Please note that Roon and Transmission seem to run fine with it.

I also noticed that if I access my router OpenVPN server (from my work imac) Roon port becomes closed as well as Transmission port.
If I don't access my router OpenVPN server then Roon and Transmission port seems fine. Then, only Nicotine+ port gets closed after a few hours.

**Comment by Vexariboerl** [comment] 2022-11-08 08:05
> It's up to you if you want to test with this feature of the firewall disabled (but I would recommend you should leave it enabled unless you have other measures in place elsewhere on your network setup).

I tried to turn off DoS protection on the router for the night yersterday evening with a freshly launched Nicotine+.
This morning Nicotine port was closed.

**Comment by slook** [comment] 2022-11-08 09:44
Thanks for keeping us posted.

> ok I'll try maybe that later but I really need Little Snitch.

This is the next thing to try. It might not be enough just to disable the rule, it could be nessassry to delete the the rule or unload Little Snitch entirely in order to verify if this is leading to the problem or not. If it is, then we will be closer to finding the bug.

**Comment by Vexariboerl** [comment] 2022-11-08 12:59
> This is the next thing to try. It might not be enough just to disable the rule, it could be nessassry to delete the the rule or unload Little Snitch entirely in order to verify if this is leading to the problem or not. If it is, then we will be closer to finding the bug.

Disabling the rule is of no use as then Little Snitch will intercept Nicotine+ incoming and outgoing connections and ask me what to do with it.
For the moment I turned off Little Snitch Network Filter which should tell Little Snitch to stop intercepting incoming or outgoing traffic whether there is an allow or deny rule.
![Capture d’écran 2022-11-08 à 13 44 47](https://user-images.githubusercontent.com/55237993/200570320-0ab08788-f7e1-493b-b2b9-5b4653df037e.png)

I'm not too keen on uninstalling Little Snitch completely as I rely too much on years of accumulated rules.
Also remember that Transmission and Roon work fine alongside Little Snitch.

**Comment by Vexariboerl** [comment] 2022-11-09 19:13
So I turned off Little Snitch's Network filter and let Nicotine run overnight.
I'm just checking now and the port is closed. I quit and relaunched Nicotine and now the port is back to open.

**Comment by mathiascode** [comment] 2022-11-10 12:10
> Also remember that Transmission and Roon work fine alongside Little Snitch.

I don't think the issue with Little Snitch applies in this case. It's mainly an issue when searching for popular things, where closing a peer connection takes a second due to a macOS kernel bug, stalling the network thread for a while.

Could you check if the port is still occupied when this happens? One of these commands should work (verify that they work when the port is open): https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x

**Comment by Vexariboerl** [comment] 2022-11-12 00:10
> Could you check if the port is still occupied when this happens? One of these commands should work (verify that they work when the port is open): https://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x

here is the result when the port is open
`sudo lsof -nP -i4TCP:2245 | grep LISTEN
Nicotine+ 13295 xavier   11u  IPv4 0xbd033e9e7599592d      0t0  TCP *:2245 (LISTEN)`

… and about a day later with the port closed
`sudo lsof -nP -i4TCP:2245 | grep LISTEN
Nicotine+ 13295 xavier   11u  IPv4 0xbd033e9e7599592d      0t0  TCP *:2245 (LISTEN)`

**Comment by mathiascode** [comment] 2022-11-12 02:29
Looks like the port is still bound, so no issues there. Things are not making a lot of sense...

The only obvious difference left compared to the other applications is the port range. Could you try using a port in the 50000-range in Nicotine+, to see if it changes anything?

**Comment by Vexariboerl** [comment] 2022-11-12 21:17
I tried to change my port for one in the >50000 range this morning (before you edited your post :) but now the port is back to closed.

> Could you try disabling DoS protection here? I think it might be rejecting port checkers sometimes, especially since the Soulseek network has a lot of active connections at all times.

I actually already tried this (see my earlier post [here](https://github.com/nicotine-plus/nicotine-plus/issues/2223#issuecomment-1306785839)).
… but what the heck, I'll try this again.

**Comment by Vexariboerl** [comment] 2022-11-13 07:38
Oh well, I guess disabling DoS protection is not the solution
![Capture d’écran 2022-11-13 à 08 28 51](https://user-images.githubusercontent.com/55237993/201511121-cb68d5e6-
![Capture d’écran 2022-11-13 à 08 29 04](https://user-images.githubusercontent.com/55237993/201511245-99420332-24c7-4f58-9ba7-13c620d677d5.png)


Meanwhile Roon port has been running non stop for many days
![Capture d’écran 2022-11-13 à 08 31 24](https://user-images.githubusercontent.com/55237993/201511247-1db67685-fa3c-4cc0-8fa9-5e4761706931.png)

**Comment by mathiascode** [comment] 2022-11-13 13:13
In that case, I'm out of ideas. I'll have to ponder on this for some time.

**Comment by slook** [comment] 2022-11-17 19:12
At this point, it is never going to be possible to troubleshoot this issue unless the problem can be isolated to either of the:

- Runtime environment
- Network environment

Therefore, in order to continue with this investigation, it is going to be necessary to rule out one or both of the above, by means of:

- Running Nicotine+ on a different (non-macOS) machine on the local network, and/or;
- Connectiing the affected machine(s) via a different network that uses a different router.

**Comment by Vexariboerl** [comment] 2022-11-18 10:56
Ok thanks. good points.
I'll run Nicotine+ for a while on my work iMac (not the same machine but different router/network) and see what happens.
I'll see also if I can find a windows machine to install Nicotine on it (on the same network).

**Comment by Vexariboerl** [comment] 2022-11-22 19:41
Here is a little followup with the test suggested by @slook.

1. I installed Nicotine+ on a windows machine on the same network and let it run 24/24 for 2-3 days now. So far the port it is still open.

2. I installed Nicotine+ on my work iMac (Intel, Monterey. Different network, different router) and let it run for a few days as well. So far the port is still open.

**Comment by slook** [comment] 2022-11-24 16:39
Thanks for keeping the issue posted.

It might be useful to find out more about the runtime environment on the affected M1 Mac Mini, such as about the network adaptor is it on WiFi or via LAN (if so is it the 1Gbps or 10Gbps version)?

**Comment by Vexariboerl** [comment] 2022-11-25 10:00
The affected M1 Mac Mini connected to the network via LAN (1Gbps version)
it is connected to a Netgear GS208 Switch (not managed)
which is connected to an Asus RT-AC68U router running Asuswrt-Merlin 386.7_2 firmware
to simplify things UPnP auto activation is disabled on the router and all needed ports are forwarded manually.

I noticed that Transmission (4.0.0-beta.1) has a similar problem as well, port becomes closed after a few hours. Restarting Transmission makes the port open again until next day.
I tried the same Transmission 4 beta 1 on my work Intel iMac (other network and router) and the port holds fine.

But during all this time Roon has been running 24/24 on the M1 Mac Mini for many days and when I check the port it is always open.

**Comment by slook** [comment] 2022-11-26 10:58
Then this has narrowed the problem down to something about the runtime environment of the M1 mac.

In the [latest master](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos) it is now possible to initialize UPnP upon Connect without having to restart the application.

**Comment by Vexariboerl** [comment] 2022-11-26 13:31
Thanks @slook
I just downloaded the latest master. I'll try Disconnect > Connect the next time the port status changes to closed.
UPnP is not enabled in nicotine nor on the router. Does it matter for this test?

![Capture d’écran 2022-11-26 à 14 21 44](https://user-images.githubusercontent.com/55237993/204091228-b4751d2d-51fb-4f39-bac5-bd23026a6424.png)

**Comment by Vexariboerl** [comment] 2022-11-27 10:08
I can confirm that, with the latest master, doing Disconnect > Connect reestablishes the open port.

**Comment by slook** [comment] 2022-11-28 11:24
It is a useful observation that the port gets closed even when UPnP is not enabled.

Does the machine sleep during the time that Nicotine+ is idle? Perhaps even some devices might go into a power saving state, even while the machine appears to be awake.

If we could detect a wakeup from sleep event, then it might be considered prudent to reestablish the connection, now that doing so is trivial.

**Comment by Vexariboerl** [comment] 2022-11-28 13:20
Sleep is disabled on the M1 Mac Mini. I can attest it doesn't sleep as I can access Roon via Roon Arc. Before disabling sleep Roon was not available to Roon Arc after the mac went to sleep.
![Capture d’écran 2022-11-28 à 14 04 28](https://user-images.githubusercontent.com/55237993/204284962-85ee89ad-c63a-48bf-b9a1-2afb0cfa47a0.png)
The only device connected to it that goes into sleep mode is the display and 2 external HDD (that spins down when not used but seem to wake up fine when invoked).

For information, when I tried Nicotine+ on my work intel iMac, which has sleep enabled, the port would stay open after many days and many wake from sleep.
Things seem to be different when you're on a M1 mac. Like I mentioned earlier, Transmission 4 beta (which is M1 native) seems to have a similar problem so this should not be a Rosetta 2 related problem.

Roon developers seem to have found a solution to keep the port open on M1 macs. Maybe they do something like reestablish the connection every 12h?

**Comment by slook** [comment] 2022-11-28 17:23
The Roon core seems to be closed source, so it is probably not possible to determine the mechanisms used to establish and maintain connections.

> Roon developers seem to have found a solution to keep the port open

Since the Roon developers also control their servers, then it would be easy for their systems to detect if the port got closed and do something about it. Nicotine+ can't do this because we don't control the Soulseek server nor run any other phone home services that would enable us to determine the state of client's network environment.

> something like reestablish the connection every 12h?

I suppose with closed source software developers can and do get away with all sorts of hacks and workarounds.

In your case this might be appropriate (and would now be trivial for you to do Disconnect > Connect on a timer in a plugin), however I do not regard such a workaround to be a proper solution because the actual cause of the bug would still remain unknown.

**Comment by Vexariboerl** [comment] 2022-11-30 11:39
Thanks @slook for the detailed explanation about how Roon might pull this off.

> In your case this might be appropriate (and would now be trivial for you to do core.disconnect() then core.connect() on a timer in a plugin)

This could be a temporary solution in the meantime. At least I could leave Nicotine+ running.
Where can I find such a plugin? I don't see any timer in the available ones.

> Perhaps you could gather some logs to help with the reported issue https://github.com/transmission/transmission/issues/2920 or a new issue on the [Transmission issue tracker](https://github.com/transmission/transmission/issues) contribute some conversation on there might be helpful for everybody

I'll certainly do that when I find some time.

**Comment by Vexariboerl** [comment] 2022-12-08 11:15
A little followup from past 8 days…
I upgraded Transmission to version 4.0.0-beta.2 and have been running it for a few days. The port stays open now.
Maybe they could share what they have done to make this work?

**Comment by slook** [comment] 2022-12-08 16:53
https://github.com/transmission/transmission/compare/4.0.0-beta.1...4.0.0-beta.2

**Comment by Vexariboerl** [comment] 2022-12-08 17:31
hopefully there is are hints to help fix the seemingly similar issue in Nicotine+

**Comment by mathiascode** [comment] 2022-12-09 01:40
It's frustrating. There shouldn't be any need to "fix" anything, since we're using a standard listening socket that has worked fine for years, but here we are...

**Comment by Vexariboerl** [comment] 2022-12-09 08:39
I understand your frustration.

I let Transmission run for about 3 days and the port stayed open every time I checked. About once in the morning and in the evening. I even checked using Soulseek Port Check URL in case it would be a false positive.

The only time the port changed to closed was when I connected from my work iMac to my home Mac Mini m1 through my home router using its OpenVPN server in bridge (TAP) mode.
But here I noticed that Roon Port became messed up as well.
It seems to be another problem.

I will try to leave Transmission running longer (not using the OVPN server) and see… one never knows.

**Comment by Vexariboerl** [comment] 2022-12-19 08:52
Here is a follow up for the past week.

I let Transmission 4 beta 2 port run longer than 3 days and I noticed that its port became closed after about 4 days where with Nicotine+ the open port does not last more than 24h on my M1/Monterey

I will report an issue I get in the [Transmission issue](https://github.com/transmission/transmission/issues) tracker like suggested by @slook 

Are there other people using Nicotine+ on an Apple M1/Monterey system reporting similar port issues as I do?

**Comment by mathiascode** [comment] 2022-12-19 17:12
> Are there other people using Nicotine+ on an Apple M1/Monterey system reporting similar port issues as I do?

Unfortunately not.

The Transmission port closing after 4 days is interesting though. How much torrent-related network activity would you estimate you receive every day (number of torrents/peers)? I would assume Nicotine+ receives more connections due to the search system, which handles several search requests per second, and I wonder if this causes something to block the port sooner.

**Comment by Vexariboerl** [comment] 2022-12-19 17:56
> > Are there other people using Nicotine+ on an Apple M1/Monterey system reporting similar port issues as I do?

> Unfortunately not.

Are there any other people using Nicotine+ on an Apple M1/Monterey at all (except me)?   :)

> The Transmission port closing after 4 days is interesting though. How much torrent-related network activity would you estimate you receive every day (number of torrents/peers and amount of data transmitted)? I would assume Nicotine+ receives more connections due to the search system, which handles several search requests per second, and I wonder if this causes something to block the port sooner.

I'm actually seeding 87 torrents, but nearly no activity these past weeks.

**Comment by mathiascode** [comment] 2022-12-19 18:17
> Are there any other people using Nicotine+ on an Apple M1/Monterey at all (except me)? :)

macOS is our least popular OS of the three major ones (GNU/Linux, Windows, macOS), but we have some macOS users, and I assume the number of users on newer machines with Apple silicon is increasing. It's difficult to say how many there are, though.

Some download stats:
https://tooomm.github.io/github-release-stats/?username=nicotine-plus&repository=nicotine-plus
https://formulae.brew.sh/formula/nicotine-plus

**Comment by Vexariboerl** [comment] 2023-01-19 21:52
> It would be interesting to see if the Transmission devs can shed any light on this. Perhaps you could gather some logs to help with the reported issue [transmission/transmission#2920](https://github.com/transmission/transmission/issues/2920) or a new issue on the [Transmission issue tracker](https://github.com/transmission/transmission/issues) contribute some conversation on there might be helpful for everybody.

I posted a new issue on the Transmission issue tracker here:
[Port closed after a few days on M1 mac](https://github.com/transmission/transmission/issues/4618)

**Comment by slook** [comment] 2023-01-20 13:14
Apparently https://github.com/transmission/transmission/commit/06090f113ac5004d4594247c86ff07516af24edf was the resolution to the problem in Transmission, but it is not immediately obvious how that caused the problem, other than it might have something to do with the handling of `TR_BAD_SOCKET`.

**Comment by mathiascode** [comment] 2023-03-04 12:50
What we've established so far:
- It's not a problem with the router, since other machines work fine on the network
- It's most likely not an issue in Nicotine+ or Transmission. Nobody else has reported an issue, and the ports are still occupied by the program.

Is Little Snitch the only network-related application installed on your system? Any other services that could affect the network?

From previous experience, you have to disable network services entirely to prevent them from still affecting the system and causing potential issues. You can do this somewhere in the network preferences on the system. I'm not sure if you're able to do this, but in order to debug this issue further, the only realistic option is to temporarily disable all network services to get the system as close to a fresh experience as possible.

**Comment by Vexariboerl** [comment] 2023-03-05 18:54
> Is Little Snitch the only network-related application installed on your system? Any other services that could affect the network?

So far as I'm aware, Little Snitch was the only network-related application installed on my system, until I installed ZeroTier about a month ago.

> From previous experience, you have to disable network services entirely to prevent them from still affecting the system and causing potential issues. You can do this somewhere in the network preferences on the system. I'm not sure if you're able to do this, but in order to debug this issue further, the only realistic option is to temporarily disable all network services to get the system as close to a fresh experience as possible.

I don't know how to disable network services entirely on my mac. Maybe with something like [LaunchControl](https://www.soma-zone.com/LaunchControl/)?
…
To add an other layer of information: 
I had also tried Nicotine+ (see post [here](https://github.com/nicotine-plus/nicotine-plus/issues/2223#issuecomment-1324156859)) on my work iMac (intel), which didn't seem to have the port closing after a while problem as on my M1 mac.
This work iMac also has Little Snitch installed and running.
I will try again with Nicotine+ 3.3.0.dev4 (and maybe disable sleep on the iMac, on the mac mini M1 sleep is disabled)

**Comment by Vexariboerl** [comment] 2023-03-14 22:09
> I will try again with Nicotine+ 3.3.0.dev4 (and maybe disable sleep on the iMac, on the mac mini M1 sleep is disabled)

OK I've been running Nicotine+ 3.3.0.dev4 on my work iMac (Intel) since my last post (about a week) and the port has stayed open all along. This iMac has also Little Snitch installed and running. ZeroTier is running as well. Auto sleep was disabled on this mac.

**Comment by slook** [comment] 2023-12-18 19:54
> OK I've been running Nicotine+ 3.3.0.dev4 on my work iMac (Intel) since my last post (about a week) and the port has stayed open all along.

Great. Please update to the latest development version and let us know everything is still OK?

https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos

**Comment by slook** [comment] 2023-12-18 20:16
Oh, sorry I think I closed this issue by mistake, the iMac test was a troubleshooting step. I assume the problem still does persist on M1?

**Comment by Vexariboerl** [comment] 2023-12-20 09:39
> Oh, sorry I think I closed this issue by mistake, the iMac (Intel) test was a troubleshooting step. I assume the problem still does persist on M1?

I'm testing on M1 with 3.3.0rc1 and I can confirm the problem is still here. Port closed after about 1 day.

**Comment by Vexariboerl** [comment] 2024-03-17 12:05
I updated my Mac Mini M1 to Sonoma (from Monterey) 1.5 month ago and now the port stays open :)

**Comment by mathiascode** [comment] 2024-03-18 20:21
Thanks, I'll assume this is fixed then. If anyone still runs into the issue on Sonoma, feel free to comment.

**Closed by mathiascode** 2024-03-18 20:21 UTC
Labels: bug
