### ISSUE TITLE
Percent: 100%, Status: Transferring

### ISSUE THREAD

**Issue by bernd-wechner** [Nicotine-Plus/nicotine-plus#3] opened 2015-10-19 10:49 UTC
I queued a few downloads from various and they've sat like that for ages. A seeming bug. The files are all in the .nicotine/incompletefiles folder and prefixed with INCOMPLETE and what looks like it may be a GUID or a very long number in any case. They play fine in Banshee though and so it seems a bug in Nictoine+ which is simply failing to notice they are complete and finalising the transaction. 

As others have noted development seems stalled. If I have time and enough passion I'll try to download, build and diagnose ... but even if I did, I loathe to invest time find and fix a bug only find there is no way to push it into the master branch. If someone is alive and watching this and prepared to ensure such stagnation doesn't mean any fixes are purely personal, and local but contribute to the master branch it's a fair disincentive.

**Comment by bernd-wechner** [comment] 2015-10-19 11:43
Well that was easy. As it stands I did fetch the source, and didn't even need building, just ran it and a lot of messages on the console explaining the problem. I simply had a typo in the Downloads folder, it didn't exist and so Nicotine could not move the completed files there. That is of course worth a small patch to improve usability. Another small bug apparent mind you, is that once fixed it still won't move the completed files until it establishes a connection with the source. Perhaps not a bug who knows, may be closing off the transaction with hash transfer or something before concluding it's 100% and rock solid ...

**Comment by gfarmerfr** [comment] 2016-08-09 21:22
Hi @bernd-wechner 

There's someone to push code now :)

Have you still the patch somewhere  ?

**Comment by bernd-wechner** [comment] 2016-08-09 22:05
I'm glad to see some folk working on it. Alas I'm not sure what you mean 
by "the patch".

Michael Labouebe wrote:

**Comment by gfarmerfr** [comment] 2016-08-09 23:28
Sorry i misread:

> That is of course worth a small patch to improve usability.

I thought you did one on your end :).

**Comment by gfarmerfr** [comment] 2017-01-12 21:36
Hi @bernd-wechner 

With the current master branch I've cleaned up a lot the file/directory choosers so it looks more like "modern" clients. The editable text box is gone so you actually can't do any typo in the folder name unless you manually edit your config file.

At least that's a first step in the right direction but I still need to look into what exactly is happening when a transfer is finished.

**Comment by mathiascode** [comment] 2020-05-19 22:05
Seems like Nicotine+ now creates a download folder if it doesn't exist. I'd say close this issue.

**Comment by kiplingw** [comment] 2020-05-19 23:57
@bernd-wechner, can you try the latest unstable in the PPA and let us know if the issue is still extant?

**Closed** 2020-06-16 10:31 UTC
Labels: enhancement
