### ISSUE TITLE
Critical 'TypeError' on macOS Monterey, N+ won't launch

### ISSUE THREAD

**Issue by indigomarxist** [Nicotine-Plus/nicotine-plus#2785] opened 2023-12-11 21:24 UTC
Nicotine+ version:  
Operating System/Distribution:
macOS Monterey, Nicotine+ Version: 3.2.9.

### Describe the bug
Fresh N+ installation, when I launch the app, I always get hit with the following:

![Screen Shot 2023-12-11 at 2 15 21 PM](https://github.com/nicotine-plus/nicotine-plus/assets/82310801/9e73f8c8-a4fd-4c83-a0f3-e89869f955b0)

### Expected behavior
To return no critical error and operate as expected.

### Steps to reproduce the bug
Fresh installation of N+ on macOS Monterey, then launch the app.

### Additional context
Nicotine+ Version: 3.2.9
GTK Version: 3.24.34
Python Version: 3.10.8 (main, Oct 13 2022, 10:19:13) [Clang 12.0.0 (clang-1200.0.32.29)]

Type: <class 'TypeError'>
Value: could not get a reference to type class
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 110, in on_activate
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/pynicotine.py", line 142, in start
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/privatechat.py", line 114, in load_users
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/privatechat.py", line 103, in show_user
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/privatechat.py", line 130, in show_user
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/privatechat.py", line 229, in __init__
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/widgets/textentry.py", line 69, in __init__
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py", line 384, in init_spell_checker

**Comment by mathiascode** [comment] 2023-12-11 23:06
Do you have Homebrew installed? I wonder if Nicotine+ is loading some files installed by Homebrew that result in conflicts.

Does the development version of Nicotine+ work? https://nicotine-plus.org/doc/TESTING.html#macos

**Comment by indigomarxist** [comment] 2023-12-13 08:09
Yes, I do have homebrew installed. As for the development version, the app crashes on startup, here's the problem report:

```txt
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Nicotine+ [29736]
Path:                  /Applications/Nicotine+.app/Contents/MacOS/Nicotine+
Identifier:            org.nicotine_plus.Nicotine
Version:               3.3.0.dev6 (3.3.0.dev6)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-12-13 01:01:09.8487 -0700
OS Version:            macOS 12.6.6 (21G646)
Report Version:        12
Anonymous UUID:        8EB8B1F4-E115-9E76-4BC2-1AF4C3961520

Sleep/Wake UUID:       28294206-A0E6-4FA1-9A5B-5D4BF682ED53

Time Awake Since Boot: 140000 seconds
Time Since Wake:       8499 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/Library/Frameworks/Python.framework/Versions/3.11/Python'
Referenced from: '/Applications/Nicotine+.app/Contents/MacOS/Nicotine+'
Reason: tried: '/Library/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x10fc3298e __abort_with_payload + 10
1   dyld                          	       0x10fc48a72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10fc48aa4 abort_with_payload + 9
3   dyld                          	       0x10fbf6699 dyld4::halt(char const*) + 615
4   dyld                          	       0x10fbf25b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x10fbf14e4 start + 388


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b2fad5d8  rdx: 0x00007ff7b2fada40
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b2fad620  rsp: 0x00007ff7b2fad5d8
   r8: 0x00007ff7b2fad640   r9: 0x0000000000000000  r10: 0x0000000000000083  r11: 0x0000000000000246
  r12: 0x0000000000000083  r13: 0x00007ff7b2fada40  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010fc3298e  rfl: 0x0000000000000246  cr2: 0x000000010fbf8da4
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
       0x10fbec000 -        0x10fc57fff dyld (*) <2517e9fe-884a-3855-8532-92bffba3f81c> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5
    thread_create: 5
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=668K resident=0K(0%) swapped_out_or_unallocated=668K(100%)
Writable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                              32K        2 
__DATA_CONST                        80K        1 
__LINKEDIT                         240K        4 
__TEXT                             448K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             65.8M       15 



-----------
Full Report
-----------

{"app_name":"Nicotine+","timestamp":"2023-12-13 01:01:10.00 -0700","app_version":"3.3.0.dev6","slice_uuid":"2cbe22c9-b2d6-30d6-a766-4e378add2f22","build_version":"3.3.0.dev6","platform":1,"bundleID":"org.nicotine_plus.Nicotine","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.6 (21G646)","incident_id":"70C6C184-538D-4F7B-AE84-834D66B21622","name":"Nicotine+"}
{
  "uptime" : 140000,
  "procLaunch" : "2023-12-13 01:01:00.9903 -0700",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir7,1",
  "procStartAbsTime" : 143687134420854,
  "coalitionID" : 21987,
  "osVersion" : {
    "train" : "macOS 12.6.6",
    "build" : "21G646",
    "releaseType" : "User"
  },
  "captureTime" : "2023-12-13 01:01:09.8487 -0700",
  "incident" : "70C6C184-538D-4F7B-AE84-834D66B21622",
  "bug_type" : "309",
  "pid" : 29736,
  "procExitAbsTime" : 143695981796031,
  "cpuType" : "X86-64",
  "procName" : "Nicotine+",
  "procPath" : "\/Applications\/Nicotine+.app\/Contents\/MacOS\/Nicotine+",
  "bundleInfo" : {"CFBundleShortVersionString":"3.3.0.dev6","CFBundleVersion":"3.3.0.dev6","CFBundleIdentifier":"org.nicotine_plus.Nicotine"},
  "storeInfo" : {"deviceIdentifierForVendor":"C2089EE2-0ABA-568A-A8DF-0CF4A87D6732","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.nicotine_plus.Nicotine",
  "crashReporterKey" : "8EB8B1F4-E115-9E76-4BC2-1AF4C3961520",
  "wakeTime" : 8499,
  "sleepWakeUUID" : "28294206-A0E6-4FA1-9A5B-5D4BF682ED53",
  "sip" : "disabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/Library\/Frameworks\/Python.framework\/Versions\/3.11\/Python'","Referenced from: '\/Applications\/Nicotine+.app\/Contents\/MacOS\/Nicotine+'","Reason: tried: '\/Library\/Frameworks\/Python.framework\/Versions\/3.11\/Python' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":5,"thread_set_state":0,"task_for_pid":5},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":2181664,"threadState":{"r13":{"value":140701836433984},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701836432960},"cr2":{"value":4559179172},"rdx":{"value":140701836433984},"r10":{"value":131},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4559415694,"matchesCrashFrame":1},"rbp":{"value":140701836432928},"rsp":{"value":140701836432856},"r12":{"value":131},"rcx":{"value":140701836432856},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4559126528,
    "size" : 442368,
    "uuid" : "2517e9fe-884a-3855-8532-92bffba3f81c",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703517421568,
  "size" : 19331678208,
  "uuid" : "f2ce8b0d-f2e7-3c14-88fa-430ab7913380"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=668K resident=0K(0%) swapped_out_or_unallocated=668K(100%)\nWritable regions: Total=9220K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9220K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                              32K        2 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         240K        4 \n__TEXT                             448K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             65.8M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000614
    },
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000231
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir7,1, BootROM 481.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 1.6 GHz, 8 GB, SMC 2.26f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Display: Color LCD, 1366 x 768 (WSGA - Wide eXtended Graphics Array), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445364533303445452D45474345000000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80CE, 0x4B3445364533303445452D45474345000000
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SD0256F, 251 GB
USB Device: USB30Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2
```
`Library not loaded: '/Library/Frameworks/Python.framework/Versions/3.11/Python'` clearly seams to be the issue for the development version, I tried reinstalling python with brew but no luck.

I also tried launching the stable version through the terminal (dragged and dropped the executable from "show package contents").

terminal output for stable (DMG) version:
```fish
** (org.nicotine_plus.Nicotine:29062): WARNING **: 00:52:51.837: Failed to load shared library '/usr/local/Cellar/gspell/1.12.2_1/lib/libgspell-1.2.dylib' referenced by the typelib: dlopen(/usr/local/Cellar/gspell/1.12.2_1/lib/libgspell-1.2.dylib, 0x0009): Symbol not found: (_g_assertion_message_cmpint)
  Referenced from: '/usr/local/Cellar/gspell/1.12.2_1/lib/libgspell-1.2.dylib'
  Expected in: '/Applications/Nicotine+.app/Contents/MacOS/libglib-2.0.0.dylib'
[2023-12-13 00:52:51] Error while scanning folder /Volumes/FUJIFILM/music: [Errno 2] No such file or directory: b'/Volumes/FUJIFILM/music'
[2023-12-13 00:52:51] Error while scanning folder /Volumes/iomslf: [Errno 2] No such file or directory: b'/Volumes/iomslf'
/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/frame.py:384: Warning: cannot retrieve class for invalid (unclassed) type 'void'
[2023-12-13 00:52:51] Rescan complete: 2 folders found
[2023-12-13 00:52:53] UPnP: External port 2234 successfully forwarded to local IP address 192.168.4.28 port 2234
^C[2023-12-13 00:55:32] Quitting Nicotine+ 3.2.9, application closing…
  ~  exit
```
seems to be a `gspell` issue? I tried reinstalling this through homebrew as well,no results either.

**Comment by mathiascode** [comment] 2023-12-13 22:23
The issue should be fixed now. Can you try the latest development version?

**Comment by mathiascode** [comment] 2023-12-15 15:14
Closing, since I've confirmed the issue was fixed on my macOS machine. Let me know if Nicotine+ still isn't launching on your end.

**Closed as completed by mathiascode** 2023-12-15 15:14 UTC
Labels: bug

**Comment by indigomarxist** [comment] 2023-12-21 00:05
yep, works great! thank you so much!
