### ISSUE TITLE
Message code 1003

### ISSUE THREAD

**Issue by oknozor** [Nicotine-Plus/nicotine-plus#876] opened 2020-11-29 09:15 UTC
Hello, 

First of all thank you for the hard work ! I am currently implementing a self hostable soulseek client and I wouldn't be able to without  the work you have already done. 

When sending a "join room" message (code 14) to the soulseek server, it responds with the following message: 

| code | content |
|:------  | :--------  |
| 1003 | "100"    |

This does not seems to be documented in [SLSKPROTOCOL.md](https://github.com/Nicotine-Plus/nicotine-plus/blob/master/doc/SLSKPROTOCOL.md). 

Does this means something like "room joined" ? 

I am using the following version numbers to communicate with the server : 
- major : 157
- minor: 19

Thank you in advance.

**Comment by mathiascode** [comment] 2020-11-29 13:00
Interesting, I've never seen messages under the 1003 message code before. What's the exact message you're sending to the server? I'm having trouble reproducing this.

**Comment by mathiascode** [comment] 2020-11-29 13:02
Normally the server responds with a code 14 message too, while the 1000-range is reserved for error messages.

**Comment by oknozor** [comment] 2020-12-01 12:19
It seems I am not receiving this message anymore.
I am not sure yet, but I might have messed something during while implementing new messages. 
I will double check if the message exist and let you known.

**Comment by mathiascode** [comment] 2020-12-04 01:19
It's also possible that the server code for the CantCreateRoom message should be 1003 instead of 1002. The source code for CantCreateRoom has existed in Nicotine+ for many years, but previously wasn't assigned to a server code and contained no information about where it came from, so I had to guess where the message would be placed.

**Comment by jpdillingham** [comment] 2020-12-11 12:39
It looks like it is sent when you attempt to join a private room in which you are not a member.  You should also get a private message from the server at the same time with the text:

```
The room you are trying to enter (<the room>) is registered as private.
```

**Comment by jpdillingham** [comment] 2020-12-11 13:17
The message contains only the name of the room.  I'm not certain it relates only to private rooms, but I don't know of anything that would prevent a person from joining a public room so I can't tell if a different message is sent in that case.  I'll assume it is generic.

**Comment by mathiascode** [comment] 2020-12-11 15:44
Placing a space at the end of a room name was another way to receive a private message from the server, but I don't think the server message was sent in that case. I'll double check, thanks for the info.

**Comment by mathiascode** [comment] 2020-12-11 16:15
It would seem like message code 1003 is for private rooms only. These are other private messages I've received from the server, but no server message:
- "dev" room: "The room you are trying to enter (dev) is moderated. Please contact one of these moderators if you are interested in being added to the room's member list:
sierracat"
- Creating room with leading or trailing space in name: "Could not create room. Reason: Room name   contains leading or trailing spaces."

**Comment by mathiascode** [comment] 2020-12-11 19:31
@jpdillingham Were you ever able to receive a message with the code 1002 from the server?

**Comment by jpdillingham** [comment] 2020-12-11 22:08
Not yet, I was going to spend some time in WireShark this weekend to determine how to create a private room and once I figure that out I should be able to see how the server reacts to an attempt to create an existing private room.  I think this might be what 138 is for.

**Comment by jpdillingham** [comment] 2020-12-12 16:19
The message sent to create a private room is 14; the same code used to join a room.  The message has a trailing integer used to indicate whether the room is private: 1 = private, 0 = public.  This appears to only be used by the server when joining a room that doesn't exist, and doing so with private = 1 creates a private room and makes you the owner.

Attempting to join an existing room with this message results in the same 1002 and private message as if you try to join a private room you aren't a member of.

I'm not sure how you'd get a 1002, perhaps if the server was preventing your user from creating new rooms.  I confirmed that using trailing or leading spaces or trying to enter `dev` results in a PM only, no server message.

**Comment by mathiascode** [comment] 2020-12-12 16:55
Looks like the integer was never added to the documentation, thanks for the reminder. Since code 1002 was a personal guess (https://github.com/Nicotine-Plus/nicotine-plus/issues/876#issuecomment-738489293), and the official client only recognizes CantConnectToPeer and CantCreateRoom error messages, it probably doesn't exist.

Server code 138 is apparently reserved for transferring room ownership, but I don't think this was ever implemented?

**Closed** 2020-12-16 22:35 UTC
