### ISSUE TITLE
Upload I/O error: cannot fit 'int' into an offset-sized integer

### ISSUE THREAD

**Issue by cookie99999** [nicotine-plus/nicotine-plus#3077] opened 2024-08-08 14:17 UTC
Nicotine+ version:  3.3.4
Operating System/Distribution: Nobara 40 (Fedora fork)

### Describe the bug
A peer has attempted to download a 6.2GB file from me, which results in the error "Upload I/O error: cannot fit 'int' into an offset-sized integer" showing up many times in the log, "Local file error" in the file's status, and eventually a connection timeout. Other files upload without issue.

### Expected behavior
The file should upload properly

### Steps to reproduce the bug
Download this particular file from me

### Additional context
Screenshots, logs, stacktraces or relevant information.
I can provide debug info etc as requested

**Comment by slook** [comment] 2024-08-08 15:10
Thank you for your report.

Please switch to the lastest development build:
https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

The error will probably be the same?

**Comment by cookie99999** [comment] 2024-08-09 01:49
The error is not present in the new version, at least not when I download the file in question myself from a separate account and machine. The original peer cancelled so perhaps it was an error on their end.

**Comment by slook** [comment] 2024-08-09 08:41
This issue is probably a duplicate of a previous issue see https://github.com/nicotine-plus/nicotine-plus/issues/1985#issuecomment-1100097476 for which there is no fix, TLDR:

>Affects any Soulseek NS version, the client was last updated in 2009 and generally can't handle values past the int32 limit. The few times it does is by chance.

> The problematic client is Soulseek NS. If more than 2 GB of a file has been downloaded, and the download aborts/pauses and later continues, Soulseek NS fails to read the size of the incomplete file. It then sends an invalid file offset of -1.
> 
> There's nothing we can do on our end, except improve the error message. If we ignore the offset and start sending data from the beginning of the file, the user ends up with a corrupted file.
> 
> There are two options for Soulseek NS users that want to download >2 GB files:
> 
>  - Download the whole file in one go, never pause the download or disconnect once it passes 2 GB
>  - Switch to a modern Soulseek client that properly supports large files (Soulseek Qt, Nicotine+, slskd, Seeker)

**Closed** 2024-08-09 13:11 UTC
Labels: bug, duplicate
