### ISSUE TITLE
Many file searches wrongly appear as private on the far end

### ISSUE THREAD

**Issue by davidsaada** [nicotine-plus/nicotine-plus#2120] opened 2022-07-05 13:43 UTC
Nicotine+ version:  3.3.0.dev1  •  GTK 3.24.20
Operating System/Distribution: Ubuntu 20.04

### Describe the bug
When searching, I often get many results telling that files are privately shared. i.e. I see "[PRIVATE]" before the file names. When attempting to browse the user's files, I see they are ALL privately shared, meaning that I can't download any of them. Now, chatting with few of these users, they say that they do share the files and don't understand the problem I have. This problem seems to be either on their end (it is always the problem with the same users) or a combination of their shares and my client - can't tell exactly. 

### Expected behavior
Expect these files to be shared. 

### Steps to reproduce the bug
Look for instance for the terms "Sunny Lax Night Sky" or "Guy Mantzur If I Were You" to name a few. Few of the results should appear as private. Got many more examples if this doesn't work.

**Comment by slook** [comment] 2022-07-05 16:05
This sounds like a interoperability issue with the official clients.

@davidsaada If you have already established a dialogue with some users then please ask them if they are willing to assist with further testing and investigations which would help us to debug the issue. If so, then please send the usernames privately via @mathiascode 's email (which is on his GitHub profile). Meanwhile, please test if this affects certain shared folders or if it is the entire shares or perhaps mounted locations on the remote peers machine's or not, etc.

**Comment by mathiascode** [comment] 2022-07-06 00:51
If these files are also private when browsed from a SoulseekQt client, it's either a user error or an issue in SoulseekQt.

**Comment by davidsaada** [comment] 2022-07-06 06:51
So I have set up the SoulseekQt client on my other Windows machine (the old 2019 release, is there a newer one?). Problem appears to be the same. Although the files don't initially appear as "private" (as in Nicotine), attempting to download them says that they are not shared. Again - this seems to apply to ALL user's files. 
The two users I've established a dialogue with have been offline for quite some time. Tried messaging few of the new ones I found, no response yet. Not sure they will respond either (most of the people I tried communicating with in the past never responded).

**Comment by mathiascode** [comment] 2022-07-06 11:16
> "File not shared" is a different state than "[PRIVATE]" items, for example there could be a path name error, incorrect transfer token or other such that may cause some problem.

Private shares also use the "File not shared" status message.

**Comment by davidsaada** [comment] 2022-07-06 12:36
> Does the bug also affect the [current stable release](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DOWNLOADS.md#ubuntudebian) of Nicotine+ 3.2.2?

Stable client behaves pretty much the same. Only difference is that it shows "PRIVATE FILE" before the file name (instead of "PRIVATE" in the unstable release). Otherwise everything else behaves the same way. 

> SoulseekQt shows a lock icon next to private shares. Does it not appear?

Sorry, didn't notice it. It does appear.

> Please enable the "Transfers" log catagory (Log Pane > Right-click > Log catagories > "Transfers") perhaps that will give us some clues.

I've enabled the transfer logging. Just to be clear: Logging pane has a "Log transfers to file" checkbox. Is this the one I need to enable? What do I do with it now?

> If you send me a few usernames, I could investigate.

Is it OK to post them here? If not, I can send them privately.

**Comment by slook** [comment] 2022-07-06 14:03
> I've enabled the transfer logging... What do I do with it now?

It might be possible to look for log messages which indicate if the "File not shared" status is due to the "Reason: " of the file being private or if it is because of some other issue. You can copy+paste lines or log to file (which is in the "logs" folder of your nicotine user-data folder).

If any data you need to post contains personal data such as usernames, please send this privately via Mat's email.

**Comment by mathiascode** [comment] 2022-07-06 18:40
> Never mind, sent them to you by mail.

At least three of the four users you sent have deliberately made their shares private, judging by their user info. I've confirmed that their shares look the same in SoulseekQt and Nicotine+.

There's a minority of users that make their shares private in the attempt to deceive others. I would assume this is the case for the users you mentioned in your original issue report, but I can only speculate.

In any case, since sending private shares in search results is a SoulseekQt feature, and this isn't a technical bug in Nicotine+, I will close this issue. Feel free to report any future issues you find.

**Closed by mathiascode** 2022-07-06 18:40 UTC
Labels: bug
