### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by vide0hanz** [nicotine-plus/nicotine-plus#2853] opened 2024-02-03 17:58 UTC
```
Nicotine+ Version: 3.3.0
GTK Version: 4.12.5
Python Version: 3.11.6 (linux)

Type: <class 'BufferError'>
Value: Existing exports of data: object cannot be re-sized
Traceback:   File "/usr/lib/python3.11/site-packages/pynicotine/gtkgui/application.py", line 848, in _raise_exception
    raise exc_value
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2685, in run
    self._process_ready_sockets(current_time)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2456, in _process_ready_sockets
    self._process_ready_input_socket(sock, current_time)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2411, in _process_ready_input_socket
    self._process_conn_incoming_messages(conn_obj_established)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2467, in _process_conn_incoming_messages
    self._process_server_input(conn_obj)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 1307, in _process_server_input
    self._send_message_to_server(ServerDisconnect())
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 1518, in _send_message_to_server
    self._process_outgoing_message(message)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2539, in _process_outgoing_message
    process_func(msg_obj)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 2301, in _process_internal_messages
    self._server_disconnect()
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 1479, in _server_disconnect
    self._close_connection(self._conns, sock)
  File "/usr/lib/python3.11/site-packages/pynicotine/slskproto.py", line 937, in _close_connection
    conn_obj.ibuf.clear()
```

**Comment by slook** [comment] 2024-02-03 19:25
Closing as duplicate of https://github.com/nicotine-plus/nicotine-plus/issues/2850

Fixed in Nicotine+ 3.3.1dev1 available at https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md

**Closed by slook** 2024-02-03 19:25 UTC
Labels: bug, duplicate
