### ISSUE TITLE
Crash on start on Kubuntu 24.04

### ISSUE THREAD

**Issue by soujaa04** [nicotine-plus/nicotine-plus#3029] opened 2024-06-06 18:33 UTC
Nicotine+ version:  
Operating System/Distribution:
Kubuntu 24.04

### Describe the bug
Nicotine+ 3.3.4 install by ppa:nicotine-team/stable always crash at start 

### Steps to reproduce the bug
clic or start by terminal crash 

### Additional context
Screenshots, logs, stacktraces or relevant information.
a@a:~$ nicotine
[06/06/24 14:31:21] Chargement de Python 3.12.3
[06/06/24 14:31:21] Chargement de Nicotine+ 3.3.4
[2024-06-06 14:31:21] Chargement de GTK 3.24.41
[2024-06-06 14:31:21] Chargement du greffon système
[2024-06-06 14:31:21] Plugin chargé Commandes Nicotine+
[2024-06-06 14:31:21] Écoute du port : 2234
[2024-06-06 14:31:21] En cours de connexion à server.slsknet.org :2242
[2024-06-06 14:31:21] Connecté au serveur server.slsknet.org :2242, ouverture de session en cours…
Fatal Python error: Segmentation fault

Thread 0x00007089616006c0 (most recent call first):
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 1003 in process_scanner_messages
  File "/usr/lib/python3/dist-packages/pynicotine/shares.py", line 1083 in _process_scanner
  File "/usr/lib/python3.12/threading.py", line 1010 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x00007089620006c0 (most recent call first):
  File "/usr/lib/python3.12/selectors.py", line 468 in select
  File "/usr/lib/python3/dist-packages/pynicotine/slskproto.py", line 2488 in _process_ready_sockets
  File "/usr/lib/python3/dist-packages/pynicotine/slskproto.py", line 2725 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x0000708962a006c0 (most recent call first):
  File "/usr/lib/python3/dist-packages/pynicotine/cli.py", line 54 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Thread 0x000070897cc006c0 (most recent call first):
  File "/usr/lib/python3/dist-packages/pynicotine/events.py", line 330 in _run_scheduler
  File "/usr/lib/python3.12/threading.py", line 1010 in run
  File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
  File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap

Current thread 0x000070897de98080 (most recent call first):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 42 in run
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/application.py", line 112 in run
  File "/usr/lib/python3/dist-packages/pynicotine/gtkgui/__init__.py", line 156 in run
  File "/usr/lib/python3/dist-packages/pynicotine/__init__.py", line 224 in run
  File "/usr/bin/nicotine", line 35 in load_module
  File "/usr/bin/nicotine", line 39 in <module>

Extension modules: gi._gi, cairo._cairo, gi._gi_cairo (total: 3)
Erreur de segmentation
a@a:~$ nicotine --version
Nicotine+ 3.3.4
a@a:~$ python3 --version
Python 3.12.3
a@a:~$

**Comment by mathiascode** [comment] 2024-06-08 19:19
Two things to try:
- Start Nicotine+ in headless mode: `nicotine --headless`
- Try a fresh configuration: `nicotine -c temp_config -u temp_user_folder`

Does Nicotine+ crash in these two cases? Have you used Nicotine+ in the past without crashes?

**Comment by soujaa04** [comment] 2024-06-13 01:53
Hi
Some folder in my music folder had wrong permission. That why nicotine crash when he analyse music folser at start.

**Comment by slook** [comment] 2024-06-13 02:21
Nice work troubleshooting to find the cause of the crash.

Please can you explain in more detail, exactly what was the wrong folder permissions, was it to do with incorrect user ownership or group access?

Also, what is the type of filesystem format on the disk where your shared music folders are, such as ext4, btrfs, or etc?

**Comment by mathiascode** [comment] 2024-06-25 20:03
I'll close this issue, since it's out of our control, but providing the details mentioned above would be helpful to find out where in the OS the bug exists.

**Closed by mathiascode** 2024-06-25 20:03 UTC
Labels: bug
