### ISSUE TITLE
Enable GTK3 while running Orca by default

### ISSUE THREAD

**Issue by Mudb0y** [nicotine-plus/nicotine-plus#2652] opened 2023-09-17 18:14 UTC
Nicotine+ version:  3.3.0
Operating System/Distribution: Arch Linux

### Describe the bug

Currently, there's lots of accessibility issues revolving around GTK4 applications. They've been slowly getting fixed, but with my brief testing of Nicotine+3.3.0, I've noticed lots of accessibility issues that simply aren't there while using 3.2.29 with GTK3

I would advice checking for weather or not Orca is running, and changing the default from GTK4 to 3 if that's the case.

I don't know enough about the differences between GTK3 and 4 to say for certain if the issues stem from Nicotine or GTK it self, but most of them don't exist while using GTK3.

Let me know if there's anything I can do / test to help-out more.

If I find any other bugs, I'll make sure to report them. Maybe it would be worth it to create a meta issue for accessibility issues if any more are present?

**Comment by slook** [comment] 2023-09-17 20:08
You can manually switch the GTK version with an environment variable, as such:

```
cd nicotine-plus
NICOTINE_GTK_VERSION=3 ./nicotine
```

You can also run 3.2.9 with GTK 4, to some degree, but don't expect it to work very well. At least, maybe it will be interesting for debugging purposes. A lot has changed in 3.3.0, so it is possible that some new problems are caused within Nicotine+.

It doesn't seem like it would be helpful to force back the GTK version just yet, because that way we will never make any progress for improving accessibility. If things are really that bad, then we will consider your suggestion to force back the GTK version. However, it will be preferable that with your help we can find some fixes, or at least some work-arounds to whatever the specific issues are.

The Nicotine+ project does occasionally contribute some fixes upstream to the GTK project, so it would be worthwhile to identify exactly where the bugs are, and then the appropriate action can be taken to fix them.

Please do explain the detail of the accessibility issues you are facing. It will do for now for us to discuss it here in this thread.

**Comment by mathiascode** [comment] 2023-09-18 21:34
Regressions I've noticed so far in the GTK 4 version:
- Lists/treeviews are silent (need to port them to the new GtkColumnView widget)
- Menu buttons not read properly in GTK 4.10 and older
- Tooltips on some buttons not read in GTK 4.12
- Lines in textviews not being read in newer GTK 4 versions

Anything else?

**Comment by mathiascode** [comment] 2023-09-19 03:49
Everything I've found so far should be either fixed or worked around, except for treeviews and textviews. If there are more remaining issues aside from these two, please report them.

**Comment by Mudb0y** [comment] 2023-09-22 17:30
Unfortunately I've had to get rid of my Linux install, but as far as I remember that was all. I'll get an install running soon on a VM and will do some more testing.

**Closed** 2023-12-04 19:20 UTC
Labels: bug

**Comment by hboetes** [comment] 2024-02-10 15:42
- in the tab control, where one can select between pages, aka search, buddies, rooms, interests, etc, pressing arrow keys to move to other tabs focuses controls of the page, without giving the user a chance to switch to the tab they're actually interested in. The fix, perhaps focus the new tab only when someone actively selected it with enter, or don't automatically switch focus to the page elements and let the user do so with tab
- if accidentally landing on the buddies list due to the previously described issue, there's a widget which traps keyboard focus, so accessibility tools can't get out of there, the only solution is to close the app and reopen it
- some toggle buttons don't read properly until you shift+tab back to them, for example the button to add filters, don't know why it's a toggle button, but yeah
- when adding a filter, sometimes information is repeated as if there are two widgets with the same name and label, just perhaps different roles in some cases, for example combo box. Except the file format, everything in there exhibits this behaviour
 - the settings screen sometimes has issues with selections, where pressing the down arrow on a category might focus unrelated controls

That's about it, but keep in mind that I only used the file sharing part of the service, so I might be missing on some details outside that mode of operation.
