### ISSUE TITLE
Bad user experience with Windows-like buttons on Nicotine 3.3.0

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [nicotine-plus/nicotine-plus#2880] opened 2024-02-15 13:13 UTC
Nicotine+ version: 3.3.0
Operating System/Distribution: Windows 10 LTSC 2021 (21H2)

In new version of Nicotine+ I need to click twice on windows-like buttons (_ [] X) to start them working. Just try to open Settings, after that you cannot exit this tab clicking once on (X) button. This bug occurs wherever these buttons are.

**Comment by SnIPeRSnIPeR** [comment] 2024-04-04 22:04
3.3.2 same problem

**Comment by slook** [comment] 2024-04-04 23:35
And 3.3.3rc2 https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows ?

**Comment by SnIPeRSnIPeR** [comment] 2024-04-05 08:30
> And 3.3.3rc2 https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#windows ?
> 
> What is GTK version displayed in Menu > Help > About Nicotine+ dialog?
Hmm, I haven't installed it yet...

3.3.2
GTK 4.12.5   •   Python 3.11.8

**Comment by mathiascode** [comment] 2024-04-05 12:11
Reported upstream: https://gitlab.gnome.org/GNOME/gtk/-/issues/6614

**Comment by slook** [comment] 2024-04-11 19:49
Upstream issue was just closed with https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7114

**Comment by mathiascode** [comment] 2024-04-20 13:07
Sorry, this missed the GTK 4.14.3 release. Might have to wait until Nicotine+ 3.3.4 for the fix.

**Comment by SnIPeRSnIPeR** [comment] 2024-04-20 17:08
> Sorry, this missed the GTK 4.14.3 release. Might have to wait until Nicotine+ 3.3.4 for the fix.
So long time to wait...

**Comment by mathiascode** [comment] 2024-04-21 16:50
Looks like we have to wait for GTK 4.14.4 for a macOS fix: https://gitlab.gnome.org/GNOME/gtk/-/issues/6642

The Nicotine+ 3.3.3 release will be delayed until GTK 4.14.4 is released, but this issue should be fixed by then.

**Comment by mathiascode** [comment] 2024-05-05 10:28
This is fixed now.

**Comment by mathiascode** [comment] 2024-05-06 10:45
The fix had to be reverted when downgrading GTK 4 to fix https://github.com/nicotine-plus/nicotine-plus/issues/3000.

**Comment by SnIPeRSnIPeR** [comment] 2024-05-06 17:54
Some bad things appear on 3.3.4... When I close Statistics and make fast click on [X] to close app, the button doesn't work on first click.

**Comment by mathiascode** [comment] 2024-05-06 20:11
As I said above...

**Comment by mathiascode** [comment] 2024-05-10 19:50
I might have been unclear. The issue was fixed in GTK 4.14.4, but this version also had a regression in scrolling performance, which required us to temporarily downgrade to GTK 4.14.3.

GTK 4.14.5, which will be included in Nicotine+ 3.3.5, includes fixes for both issues.

**Comment by SnIPeRSnIPeR** [comment] 2024-05-10 22:50
> I might have been unclear. The issue was fixed in GTK 4.14.4, but this version also had a regression in scrolling performance, which required us to temporarily downgrade to GTK 4.14.3.
> 
> GTK 4.14.5, which will be included in Nicotine+ 3.3.5, includes fixes for both issues.
> 
> Note that GTK 4.14.5 has not been released yet.

Wow, true detective like :)

**Comment by mathiascode** [comment] 2024-08-17 10:07
Should be fixed, at last.

**Closed by mathiascode** 2024-08-17 10:07 UTC
Labels: bug
