### ISSUE TITLE
Cannot browse another user's files in MacOS 15.0 (24A335) 

### ISSUE THREAD

**Issue by seu-mktg** [nicotine-plus/nicotine-plus#3134] opened 2024-09-17 05:29 UTC
Nicotine+ Version: 3.3.4
Operating System/Distribution: MacOS 15.0 (24A335) 

### Describe the bug

Cannot browse another user's files in MacOS Sequoia

### Steps to reproduce the bug

1. Search a username
2. From the user profile, click "Browse files"
3. Error

### Expected behavior

1. Nicotine user is taken to a list of the searched user's files

### Additional context
Nicotine+ Version: 3.3.4
GTK Version: 4.14.4
Python Version: 3.12.3 (darwin)
Type: <class 'OSError'>
Value: [Errno 22] Invalid argument
Traceback:   File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/gtkgui/application.py", line 884, in _raise_exception
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1010, in run
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/userbrowse.py", line 99, in _parse_local_shares
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3050, in parse_network_message
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3085, in _parse_network_message
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3075, in _parse_result_list
  File "/Users/runner/work/nicotine-plus/nicotine-plus/pynicotine/slskmessages.py", line 3075, in <lambda>

**Comment by mathiascode** [comment] 2024-09-17 15:56
Duplicate of #3063, but keeping this issue open for visibility.

**Comment by seu-mktg** [comment] 2024-09-21 05:15
@mathiascode Many thanks!

**Closed** 2024-09-22 17:46 UTC
Labels: bug, duplicate

**Comment by mathiascode** [comment] 2024-09-22 18:36
For anyone running into this issue, the latest release (3.3.5) contains a fix: https://nicotine-plus.org/doc/DOWNLOADS.html#macos

**Comment by slook** [comment] 2024-12-15 17:15
@mathiascode Unpin
