### ISSUE TITLE
MacOS search shows 86 results, same search on Linux shows 1500+

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [nicotine-plus/nicotine-plus#2470] opened 2023-03-31 18:06 UTC
Nicotine+ version:  3.2.9
Operating System/Distribution: Apple M1 Ventura 13.2.1

Hi !

### Describe the bug

Search for "Sasha" on MacOS shows 69 results yet on my other machine (Linux) the same search get's 1500+ results. Both machines are on same network. The only "unusual" thing is that I have my connection on each machine going down an SSH tunnel to my own VPS. 

### Expected behavior

Number of search results returned should be same on each machine.

### Steps to reproduce the bug

Compare search results on MacOS Nicotine+ to Linux Nicotine+

### Additional context
The Soulseek ports are not open for either machine. I also have uPnP turned off in Nicotine+.

**Comment by slook** [comment] 2023-03-31 18:54
Unfortunately it is unlikely that this bug would ever be fixed in the 3.2.x branch, since the fix will likely be too complex and development is now happening only in the master branch.

Please install the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos) 3.3.0.dev5 onto your machines and run your tests again to verify that the issue still exists, then we can work on it from there.

**Comment by Michael-Z-Freeman** [comment] 2023-04-01 11:18
> Unfortunately it is unlikely that this bug would ever be fixed in the 3.2.x branch, since the fix will likely be too complex and development is now happening only in the master branch.
> 
> Please install the [latest unstable build of Nicotine+](https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/TESTING.md#macos) 3.3.0.dev5 onto your machines and run your tests again to verify that the issue still exists, then we can work on it from there.
> 
> Also, please report your Python and GTK versions of each machine (in Help > About Nicotine+).

OK I'll do that.

I also clarified the issue more. AFAIK what is happening is that on Linux the SSH tunnel is being used which gets around some local network restrictions (setup by adding SSH tunnel directly to Kubuntu network manager). However on MacOS the SSH tunnel is never used therefore Nicotine+ never uses the Proxy/SSH tunnel (which was setup using this guide - https://www.hostdime.com/kb/hd/security/browsing-the-internet-through-an-ssh-tunnel-on-macos ) so the local network restrictions are still in place.

**Comment by slook** [comment] 2023-04-01 11:57
Thank you for the clarification.

Is the "Public IP address" in Preferences > Network incorrectly displaying your local IP address?

**Comment by Michael-Z-Freeman** [comment] 2023-04-01 12:02
> Thank you for the clarification.
> 
> Is the "Public IP address" in Preferences > Network incorrectly displaying your local IP address?

Yes. MacOS is setup to use the SSH tunnel through proxy setup (see attachment ) which everything on the system should go through.
<img width="726" alt="MacOS Proxy Setting" src="https://user-images.githubusercontent.com/951566/229287468-8e7ebffb-4883-45b4-956e-5240e1902a04.png">

**Comment by slook** [comment] 2023-04-01 12:44
Is the value displayed in Nicotine+ Preferences > Menu > Public IP address = "127.0.0.1" ?

**Comment by Michael-Z-Freeman** [comment] 2023-04-02 11:11
> Is the value displayed in Nicotine+ Preferences > Menu > Public IP address = "127.0.0.1" ?

N0, the value is "195.194.77.170" which is my usual local IP address, not the SSH tunnel address.

**Comment by slook** [comment] 2023-04-02 13:38
Are you using the "Network interface" option in Nicotine+ Preferences > Network to bind to a specific network adapter?

**Comment by Michael-Z-Freeman** [comment] 2023-04-02 17:14
> Are you using the "Network interface" option in Nicotine+ Preferences > Network to bind to a specific network adapter?

No. It's been left on default (nothing in the field) apart from me experimenting by changing it to the MacOS loopback network but that did not fix the problem and I don't think it was going to anyway.

**Comment by slook** [comment] 2023-04-02 17:42
Neither did I, the reason I asked is because the function for interface binding does contain the only OS specific cases during the local address discovery process:

https://github.com/nicotine-plus/nicotine-plus/blob/b441e601ecc9f31c32402af367a210d514eccc46/pynicotine/slskproto.py#L345-L363

I don't think this method is invoked unless a Network interface is specified for binding.

The public facing address isn't actually discovered until the server connection is established:
https://github.com/nicotine-plus/nicotine-plus/blob/b441e601ecc9f31c32402af367a210d514eccc46/pynicotine/core.py#L353

That is the address value which is displayed in the Preferences dialog, i.e. it is the address the server has for your machine.

**Comment by mathiascode** [comment] 2023-04-02 18:10
Before we start delving further into specifics, I'd like to see what's going on under the hood. Could you enable debug logging (Connections and Messages, https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#debug-logging), restart Nicotine+, perform a search, and send the logs to my email on my GitHub profile?

**Comment by Michael-Z-Freeman** [comment] 2023-04-02 18:36
> Before we start delving further into specifics, I'd like to see what's going on under the hood. Could you enable debug logging (Connections and Messages, https://github.com/nicotine-plus/nicotine-plus/blob/master/doc/DEVELOPING.md#debug-logging), restart Nicotine+, perform a search, and send the logs to my email on my GitHub profile?

Log sent ! I did try setting the interface to "en0", which is the main Wifi interface, but it made no difference.

**Comment by mathiascode** [comment] 2023-04-30 16:26
Sorry, I forgot to reply. Logs seemed fine, connections seem to be established. Are you able to connect to individual users (e.g. view user info/profile or browse files of users in the nicotine room)?

**Comment by Michael-Z-Freeman** [comment] 2023-06-27 16:40
> Sorry, I forgot to reply. Logs seemed fine, connections seem to be established. Are you able to connect to individual users (e.g. view user info/profile or browse files of users in the nicotine room)?

No, I cannot browse or look at profiles. However current chat room messages are visible.

I just checked how MacOS does the proxy. AFAIK any app should just go straight to the proxy and there's not anything special that it has to do.

**Comment by mathiascode** [comment] 2023-10-05 21:21
Can you check if the latest unstable build makes any difference? https://nicotine-plus.org/doc/TESTING.html#macos

**Comment by Michael-Z-Freeman** [comment] 2023-10-06 09:27
> Can you check if the latest unstable build makes any difference? https://nicotine-plus.org/doc/TESTING.html#macos

Same result. On my Linux machine keyword "sasha" search results 1500+. On Mac 50.

Toggling "automatically forward ports" and changing to various network interfaces in drop down list makes no difference.

The fix must be quite simple. On my Mac everything else uses proxy with no problem.

Also I really need this fix as I'm a DJ that uses Nicotine for track research which involves downloading old DJ mixes and discovering gems that everyone has forgotten about. My Linux laptop is not my work machine and is very slow. The Mac is my work machine, however at the moment I'm on an academic network that has strict rules about file sharing applications, hence the need to use the tunnel/proxy which goes out to my hosting provider which is external to the campus.

**Comment by mathiascode** [comment] 2023-10-06 13:08
I sent some instructions via email to hopefully get logs where it's easier to pinpoint the issue.

**Comment by Michael-Z-Freeman** [comment] 2023-11-26 08:47
> SoulseekQt

I can't see the email. Why not just put the instructions here ?

I'll try SoulseekQt.

**Comment by Michael-Z-Freeman** [comment] 2023-11-28 07:13
With the SSH tunnel proxy on there's the same problem with SoulseekQt;"Sasha" returns very few results when there should be thousands.

**Comment by slook** [comment] 2023-12-18 19:50
Its difficult to know what to do about this. Given the problem exists also in SoulseekQt (and regardless if the connection is routed through a VPN?), then I suggest we unfortunately conclude that this issue as not a bug in Nicotine+.

**Closed by slook** 2023-12-18 19:50 UTC
Labels: bug
